### ISSUE TITLE
No results message don't show and disappear on the right time.

### ISSUE THREAD

**Issue by pedrotvr** [bithost-gmbh/ngx-mat-select-search#10]
Hey, 

In the first place well done, great job with this. 

I'm using and testing your component and you have a problem with the no results message, so if you write a word you don't have in the list the result only appears if you change focus from the box, and if you escape one char to have results the message only disappear when you put focus out. 

You can see that in the images bellow.

Thanks 

![whatsapp jpg](https://user-images.githubusercontent.com/9569121/37613276-8325bf06-2b9f-11e8-8efc-291bcbcedd09.jpeg)
![whatsapp image](https://user-images.githubusercontent.com/9569121/37613277-83405280-2b9f-11e8-86aa-0485cbbb6991.jpg)
![whatsapp i jpg](https://user-images.githubusercontent.com/9569121/37613278-835c0412-2b9f-11e8-9691-6edc5eaabf6c.jpeg)

**Comment by macjohnny** [comment]
hi @pedrotvr 
thanks for reporting
I guess this is closely related to https://github.com/bithost-gmbh/ngx-mat-select-search/issues/4

**Comment by macjohnny** [comment]
@pedrotvr can you verify this issue is also resolved with `1.0.1` ?

**Comment by pedrotvr** [comment]
@macjohnny Yes, it's fixed. 🗡

Take care can't do npm update for your plugin... have to make re-install to get last version.

**Comment by macjohnny** [comment]
@pedrotvr which command did you use to update?
if you are using npm version 5+, you find a local `package-lock.json` in your repository with fixed version, so to update you would need to set the version explicitly:
```
npm install ngx-mat-select-search@1.0.2
```
