### ISSUE TITLE
"No results" missing if ngx-mat-select-search wrapped in <mat-option>

### ISSUE THREAD

**Issue by mstawick** [bithost-gmbh/ngx-mat-select-search#101]
If `ngx-mat-select-search` is wrapped in `<mat-option>`, the "No results" label will not show. It looks like it's just cut-off.

This can be seen in stackblitz examples. The `Single selection` example is broken, since it's wrapped, and the `Multiple selection` works fine, since it's not.

Thanks for this great component.

**Comment by macjohnny** [comment]
@mstawick thanks a lot for reporting this issue. I am about to release a fixed version.

**Comment by macjohnny** [comment]
the fix was release in `1.5.2`
