### ISSUE TITLE
Support for template driven forms

### ISSUE THREAD

**Issue by Gustav0ar** [bithost-gmbh/ngx-mat-select-search#103]
Please add support template driven forms. When I try to use the library right now I get:

> There is no directive with "exportAs" set to "ngModel"

`<ngx-mat-select-search #bankSearchSelect="ngModel"></ngx-mat-select-search>`

**Comment by macjohnny** [comment]
You can simply use it like this:

<ngx-mat-select-search [(ngModel)]=„searchKeyword“>

**Comment by Gustav0ar** [comment]
I know but that way I can't get the event when text change. The other way I could reference in the component and get the event.

**Comment by macjohnny** [comment]
You can get the change event like this:
<ngx-mat-select-search ngModel (ngModelChange)=„myFunction($event)“>

**Comment by Gustav0ar** [comment]
Yeah, I know. Thanks for the help.

**Comment by macjohnny** [comment]
@Gustav0ar glad to hear it worked. Feel free to add a star if you like the project.

**Comment by TheParad0X** [comment]
This should be in the docs :) 👍

**Comment by macjohnny** [comment]
@TheParad0X it actually is: https://github.com/bithost-gmbh/ngx-mat-select-search#api
> The `MatSelectSearchComponent` implements the [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) interface.

this means you can use it with either reactive forms or template driven forms.
maybe we should explicitly mention the `ngModel` part

**Comment by TheParad0X** [comment]
Yes, I was looking for ngModel with CTRL+F and did not find anything. A simple example using ngModel would be really helpful, especially for beginners who are more likely to use over reactive forms imho

**Comment by macjohnny** [comment]
@TheParad0X I added an example to the readme in https://github.com/bithost-gmbh/ngx-mat-select-search/pull/126
