### ISSUE TITLE
Error in to select value

### ISSUE THREAD

**Issue by btd1337** [bithost-gmbh/ngx-mat-select-search#105]
After selecting a filtered option, the formcontrol receives the value, but the field clears and displays the mat-select placeholder.

Formcontrol after select filtered option

```
"responsable": {
    "id": "1485fb3f-dd93-450f-b7bb-0057d86c2c54",
    "name": "John Doe",
  },
```

Component code:

```
<mat-form-field id="responsable">
        <mat-select
          formControlName="responsable"
          placeholder="{{ 'global.responsable' | translate }}"
          #singleSelect
        >
          <mat-option>
            <ngx-mat-select-search
              [formControl]="cooperatorFilteringCtrl"
              [placeholderLabel]="'Buscar...'"
              [noEntriesFoundLabel]="'Nenhum colaborador correspondente'"
            ></ngx-mat-select-search>
          </mat-option>
          <mat-option
            *ngFor="let responsable of (filteredCooperators$ | async)"
            [value]="responsable"
            >{{ responsable.name }}
          </mat-option>
        </mat-select>
</mat-form-field>
```

```
private cooperatorsFilteringCtrl() {
    return this.cooperatorFilteringCtrl.valueChanges
      .pipe(
        takeUntil(this.onDestroy),
        debounceTime(400),
        this.filterCooperator(),
        map((page) => page.items),
        map((items) => items.map((data) => data.person)),
      )
      .subscribe(this.filteredCooperators$);
  }
```

```
private filterCooperator() {
    return switchMap((value) => {
      if (value) {
        const req = { size: 4, query: value };
        return this.cooperatorService.querySummary(req);
      }
      return of({ items: [] });
    });
  }
```

**Comment by macjohnny** [comment]
* you can use the `clearSearchInput` input to prevent clearing the search input when the dropdown is closed, which triggers another query due to your 
```typescript
private cooperatorsFilteringCtrl() {
    return this.cooperatorFilteringCtrl.valueChanges
...
}
```
part. Set it to false as follows:
```html
<ngx-mat-select-search
             [clearSearchInput]="false"
 ></ngx-mat-select-search>
```

* alternative: use a custom `compareWith` function for the `mat-select`, since you are creating new objects in each new query, so the `===` comparison will yield `false`. See e.g. https://github.com/bithost-gmbh/ngx-mat-select-search/blob/c5eb9163a12b100aeebe3c32518668bdb0963a5e/src/app/examples/01-single-selection-example/single-selection-example.component.ts#L73

**Comment by btd1337** [comment]
@macjohnny Well, It now the component doesn't clearing after select in dropdown, this is good.

But, when load view that contain object with a default value it not is displayed. The mat-select placeholder is displayed. How to fix this?

Thank you in advance.

```
<mat-form-field id="responsable">
        <mat-select
          formControlName="responsable"
          placeholder="{{ 'global.responsable' | translate }}"
          #singleSelect
        >
          <mat-option>
            <ngx-mat-select-search
              [formControl]="cooperatorFilteringCtrl"
              [placeholderLabel]="'Buscar...'"
              [noEntriesFoundLabel]="'Nenhum colaborador correspondente'"
              [clearSearchInput]="false"
            ></ngx-mat-select-search>
          </mat-option>
          <mat-option
            *ngFor="let responsable of (filteredCooperators$ | async)"
            [value]="responsable"
            >{{ responsable.name }}
          </mat-option>
        </mat-select>
 </mat-form-field>
```

```
public ngAfterViewInit() {
    this.setInitialValue();
}
```

```
protected setInitialValue() {
    this.filteredCooperators$
      .pipe(
        take(1),
        takeUntil(this.onDestroy),
      )
      .subscribe(() => {
        this.singleSelect.compareWith = this.compResponsables;
      });
  }
```

```
public compResponsables = (val1: any, val2: any) => val1 && val2 && val1.id === val2.id;
```

```
```
public ngOnInit() {
    this.cooperatorsFilteringCtrl();
}
```
```
private cooperatorsFilteringCtrl() {
    return this.cooperatorFilteringCtrl.valueChanges
      .pipe(
        takeUntil(this.onDestroy),
        debounceTime(400),
        this.filterCooperator(),
        map((page) => page.items),
        map((items) => items.map((data) => data.person)),
      )
      .subscribe(this.filteredCooperators$);
  }
```
```
private filterCooperator() {
    return switchMap((value) => {
      if (value) {
        const req = { size: 4, query: value };
        return this.cooperatorService.querySummary(req);
      }
      return of({ items: [] });
    });
 }
```

**Comment by macjohnny** [comment]
you need to set the `compareWith` property again after the data is loaded. please have a look at the examples:
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/c5eb9163a12b100aeebe3c32518668bdb0963a5e/src/app/examples/01-single-selection-example/single-selection-example.component.ts#L64-L75

**Comment by macjohnny** [comment]
could you please provide a minimal example on stackblitz? you can use https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example as a starting point

**Comment by macjohnny** [comment]
I can't figure out where in your code you set the actual initial value...

**Comment by btd1337** [comment]
Minimal example here: https://stackblitz.com/edit/github-axr2a8

**Comment by macjohnny** [comment]
@btd1337 the example doesn't seem to be working...

**Comment by macjohnny** [comment]
moreover, I still can't find the place where you are setting an initial value. Please give me more precise information about
- what you want to do
- where you implemented some code that should do that

**Comment by btd1337** [comment]
Is here:

```
public ngOnInit() {
    this.isEditingCheck();
}
```

```
private isEditingCheck() {
    if (this.activatedRoute.snapshot.data.task) {
      this.task = this.activatedRoute.snapshot.data.task;
      this.isEditing = true;
      this.form.patchValue(this.task);
    }
  }
```

In all other fields this works properly, but in `responsable` field that use `ngx-mat-select-search` don't work.

**Comment by macjohnny** [comment]
You need to make sure that you are setting a value that is among the available options at the moment of setting, otherwise `mat-select` will reject this value. I suggest you load the pre-selected value and initialize the filtered list afterwards

**Comment by btd1337** [comment]
I will try. Thank you!
