### ISSUE TITLE
[FEATURE] Define noEntriesFoundLabel  globally

### ISSUE THREAD

**Issue by Lempkin** [bithost-gmbh/ngx-mat-select-search#106]
It would be nice if we could define noEntriesFoundLabel  value globally, and not on each field  :)

**Comment by macjohnny** [comment]
@Lempkin you could write your own directive e.g. like
```typescript
@Directive({
  selector: 'ngx-mat-select-search'
})
export class MatSelectSearchLabelDirective {
  constructor(@Self() @Inject(MatSelectSearchComponent) private matSelectSearch: MatSelectSearchComponent) {
    this.matSelectSearch.noEntriesFoundLabel = 'no entries found';
  }
}
```
If the value needs to change e.g. due to a language change, you would need to trigger change detection. currently you would need to do it as follows:
```typescript
(this.matSelectSearch as any).changeDetectorRef.markForCheck();
```

Does this help you?

**Comment by macjohnny** [comment]
version [1.5.3](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/1.5.3) allows to access the `ChangeDetectorRef` as 
```typescript
this.matSelectSearch.changeDetectorRef.markForCheck();
```
therefore the solution proposed should work. 
Please let me know if there is anything else, so I could reopen this issue.
