### ISSUE TITLE
[BUG] mat-select-search-no-entries-found persists after panel closes

### ISSUE THREAD

**Issue by aroblu94** [bithost-gmbh/ngx-mat-select-search#107]
**Describe the bug**
 `mat-select-search-no-entries-found` class persists after panel closes. This causes a blank-mat-option-like space before real mat-options until clicking on "X" button to clear filter.

**To Reproduce**
(based on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example)
1. Click on the first select input
2. Search for something doesn't exists (like "aaaa")
3. Un-blur the input (both pressing `ESC` or clicking away), the selector closes
4. Open selector again
=> The list will have a blank option on top (see attached screenshot)

**Expected behavior**
The `_reset()` function should be fired also on blur

**Screenshots**
Before
<img width="321" alt="schermata 2019-02-27 alle 17 51 36" src="https://user-images.githubusercontent.com/6624657/53507541-638ba380-3ab8-11e9-91d3-997be4cea45f.png">

After
<img width="330" alt="schermata 2019-02-27 alle 17 41 32" src="https://user-images.githubusercontent.com/6624657/53507124-97b29480-3ab7-11e9-8c40-b8ee3b91f45e.png">

**Desktop**
 - OS: MacOS 10.14.3
 - Browser: Chrome
 - Version: 72.0.3626.119

**Notes**
This doesn't happen if there're search results or if the "X" key is clicked to reset the search.

**Comment by macjohnny** [comment]
Thanks a lot for reporting this issue!
Would you like to file a PR to fix the issue?

**Comment by aroblu94** [comment]
Sorry I'm a bit late, I didn't see your response. 
Waiting for the fix to be pushed on production, thanks! :)

**Comment by macjohnny** [comment]
@aroblu94 i will release version 1.5.3 later today

**Comment by macjohnny** [comment]
the fix was released with version [1.5.3](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/1.5.3)
