### ISSUE TITLE
[FEATURE] Disabling no entries found element

### ISSUE THREAD

**Issue by juan-db** [bithost-gmbh/ngx-mat-select-search#108]
It might sometimes be beneficial to disable the no entries found element, for example if you'd like to insert your own element. In my case I have a list of entries and if none of the match the search I want to have an option along the lines of "Add new item".

A boolean input on the ngx-mat-select-search component which is checked in the ngIf for the no entries found element.

In terms of alternatives, I couldn't think of a more elegant alternative.

I'm willing to add this and submit a PR as it most likely wouldn't be much work.

**Comment by macjohnny** [comment]
@juan-db you can actually achieve this by setting `[noEntriesFoundLabel]="null"`

See 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/84f20b10a0f656c5e7a32cc2b2da9ffa2e372aff/src/app/mat-select-search/mat-select-search.component.ts#L475-L487

maybe we could add a note to the readme?

**Comment by juan-db** [comment]
That might be a good idea. I just noticed the note in the documentation comment for noEntriesFoundLabel itself. I should've looked harder before creating the issue, sorry.

**Comment by macjohnny** [comment]
@juan-db if you like the project, feel free to give it a star

**Comment by macjohnny** [comment]
the fix was released with version [1.5.3](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/1.5.3)
