### ISSUE TITLE
[BUG] Static Injector Error

### ISSUE THREAD

**Issue by vijaynet10** [bithost-gmbh/ngx-mat-select-search#112]
**ERROR Error: Uncaught (in promise): 
Error: StaticInjectorError(AppModule)[MatSelectSearchComponent -> MatSelect]: 
  StaticInjectorError(Platform: core)[MatSelectSearchComponent -> MatSelect]: 
    NullInjectorError: No provider for MatSelect!**

Error: StaticInjectorError(AppModule)[MatSelectSearchComponent -> MatSelect]: 
  StaticInjectorError(Platform: core)[MatSelectSearchComponent -> MatSelect]: 
    NullInjectorError: No provider for MatSelect!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (vendor.js:55483)
    at resolveToken (vendor.js:55721)
    at tryResolveToken (vendor.js:55665)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (vendor.js:55562)
    at resolveToken (vendor.js:55721)
    at tryResolveToken (vendor.js:55665)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (vendor.js:55562)
    at resolveNgModuleDep (vendor.js:62797)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (vendor.js:63485)
    at resolveDep (vendor.js:63850)
    at resolvePromise (polyfills.js:3136)
    at resolvePromise (polyfills.js:3093)
    at polyfills.js:3195
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2743)
    at Object.onInvokeTask (vendor.js:58236)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2742)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (polyfills.js:2510)
    at drainMicroTaskQueue (polyfills.js:2917)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (polyfills.js:2822)
    at invokeTask (polyfills.js:3862)

**Comment by macjohnny** [comment]
can you post your template?
I think you are missing the `<mat-select>` element wrapping the ``<ngx-mat-select-search>`:
```html
<mat-select [formControl]="bankCtrl" placeholder="Bank" #singleSelect>
    <mat-option>
      <ngx-mat-select-search [formControl]="bankFilterCtrl"></ngx-mat-select-search>
    </mat-option>
    <mat-option *ngFor="let bank of filteredBanks | async" [value]="bank">
      {{bank.name}}
    </mat-option>
  </mat-select>
```

**Comment by vijaynet10** [comment]
<mat-select placeholder="User Name" [(ngModel)]="listlogin"
                        name="list" required #singleSelect>  
                 <mat-option>
                    <ngx-mat-select-search [formControl]="operatorFilterCtrl" ></ngx-mat-select-search>
                  </mat-option> 
                    <mat-option *ngFor="let list of filteredoperators | async" [value]="list">
                           {{list.text}}
                    </mat-option>
            </mat-select>

**Comment by vijaynet10** [comment]
this is my template and i didn't miss  <mat-select>

```
<mat-select placeholder="User Name" [(ngModel)]="listlogin" name="list" required #singleSelect>  
	<mat-option>
		<ngx-mat-select-search [formControl]="operatorFilterCtrl" ></ngx-mat-select-search>
	</mat-option> 
	<mat-option *ngFor="let list of filteredoperators | async" [value]="list">
		{{list.text}}
	</mat-option>
</mat-select> 
```

**Comment by macjohnny** [comment]
@vijaynet10 did you include the `MatSelectModule`, i.e. does it work without the `<ngx-mat-select-search>` item?
can you please provide an example on stackblitz based on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

**Comment by vijaynet10** [comment]
`MatSelectModule `already included..
`import { MatSelectModule } from '@angular/material/select';`

**Comment by macjohnny** [comment]
is it also included in your `@NgModule` imports where you also import the `NgxMatSelectSearchModule`, e.g.

https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/fe48c3e0b65d03ec402c2f806dc315d75d7f08f7/src/app/app.module.ts#L30

**Comment by vijaynet10** [comment]
it is included  @NgModule imports  and NgxMatSelectSearchModule

**Comment by macjohnny** [comment]
please post more of your code. I am pretty sure this is not a bug but rather wrong usage.

**Comment by macjohnny** [comment]
can you please provide an example on stackblitz based on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

**Comment by vijaynet10** [comment]
**@ AppModule**

```
imports: [
    BrowserModule,
    RouterModule.forRoot(approutes, { useHash: true }),
    MatFormFieldModule, MatInputModule,
    BrowserAnimationsModule,
    MatButtonModule,
    MatCheckboxModule,
    MatSelectModule,
    FormsModule,
    HttpClientModule,
    MatTableModule,
    MatPaginatorModule,
    MatDialogModule,
    MatCardModule,
    MatIconModule,
    MatMenuModule,
    FlexLayoutModule,
    MatChipsModule,
    PinchZoomModule,
    MatTabsModule,
    MatDatepickerModule,
    MatRadioModule,
    MatGridListModule,
    SignaturePadModule,
    MatSnackBarModule,
    MatStepperModule,
    StorageServiceModule,
    ReactiveFormsModule.withConfig({ warnOnNgModelWithFormControl: 'never' }),
    NgxLoadingModule.forRoot({}),
    MatAutocompleteModule,
    NgxMatSelectSearchModule
  ]

```
**HTML Template:** 
```
<div class="signin-wrapper">
  <div class="signin-box">
    <h2 class="slim-logo"><a href="#">Order Login<span>.</span></a></h2>
    <h2 class="signin-title-primary">Welcome back !</h2>

    <form class="example-form">
      <mat-select placeholder="User Name" [(ngModel)]="listlogin" name="list" required #singleSelect>
        <mat-option>
          <ngx-mat-select-search [formControl]="operatorFilterCtrl"></ngx-mat-select-search>
        </mat-option>
        <mat-option *ngFor="let list of filteredoperators | async" [value]="list">
          {{list.text}}
        </mat-option>
      </mat-select>

      <mat-form-field>
        <input matInput placeholder="Password" [type]="hide ? 'password' : 'text'" [(ngModel)]="operpassword" name="list"
          required>
        <mat-icon class="pointer" matSuffix (click)="hide = !hide">{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
      </mat-form-field>
    </form>
    <br>
    <button mat-button class="btn btn-primary btn-block btn-signin" (click)="logincheck()">Sign In</button>
  </div><!-- signin-box -->
</div>
```
**Component.TS**

```
import { FormControl } from '@angular/forms';
import { AppconfigserviceService } from './../service/appconfigservice.service';
import { LoginserviceService } from './../service/loginservice.service';
import { Listitem } from './../class/listitem';
import { ReturnStatus } from './../class/return-status';
// import { Component, OnInit, Inject, ViewChild } from '@angular/core';
import { AfterViewInit, Component, Inject , OnDestroy, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { LoginPasswordPojo } from '../class/login-password-pojo';
import { LOCAL_STORAGE, WebStorageService } from 'angular-webstorage-service';
import { ReplaySubject, Subject } from 'rxjs';
import { take, takeUntil } from 'rxjs/operators';
import { MatSelect } from '@angular/material';



@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent implements OnInit, AfterViewInit, OnDestroy {

  public operpassword: string;
  hide = true;
  public operatorpassword: string;
  public returnstatus: ReturnStatus = new ReturnStatus();
  listlogin: Listitem = new Listitem();
  loginpasswordpojo: LoginPasswordPojo = new LoginPasswordPojo();
  public listloginarray: Array<Listitem> = new Array<Listitem>();
  public data: any = [];
  public operatorFilterCtrl: FormControl = new FormControl();
  public filteredoperators: ReplaySubject<Listitem[]> = new ReplaySubject<Listitem[]>(1);
  @ViewChild('singleSelect') singleSelect: MatSelect;
/** Subject that emits when the component has been destroyed. */
protected _onDestroy = new Subject<void>();

  constructor(private loginservice: LoginserviceService, private route: Router,
    private appconfigservice:  AppconfigserviceService,
    @Inject(LOCAL_STORAGE) private storage: WebStorageService) {
    this.loadusername();
   }

   ngOnInit() {
    if (this.appconfigservice.islog()) {
      this.route.navigate(['/home']);
    }
  }
  ngAfterViewInit() {
    this.setInitialValue();
  }
  ngOnDestroy() {
    this._onDestroy.next();
    this._onDestroy.complete();
  }

  loadusername() {
    this.loginservice.loadusername().subscribe ( data => {
        this.returnstatus = data;
        this.listloginarray = this.returnstatus.returnObject;
        this.filteredoperators.next(this.listloginarray.slice());
        this.operatorFilterCtrl.valueChanges
        .pipe(takeUntil(this._onDestroy))
        .subscribe(() => {
          this.filterOperators();
        });



    } , error => {alert(error); }
    );
  }

  protected filterOperators() {
    if (!this.listloginarray) {
      return;
    }
    // get the search keyword
    let search = this.operatorFilterCtrl.value;
    if (!search) {
      this.filteredoperators.next(this.listloginarray.slice());
      return;
    } else {
      search = search.toLowerCase();
    }
    // filter the banks
    this.filteredoperators.next(
      this.listloginarray.filter(operator => operator.text.toLowerCase().indexOf(search) > -1)
    );
  }


  protected setInitialValue() {
    this.filteredoperators
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe(() => {
        // setting the compareWith property to a comparison function
        // triggers initializing the selection according to the initial value of
        // the form control (i.e. _initializeSelection())
        // this needs to be done after the filteredBanks are loaded initially
        // and after the mat-option elements are available
        this.singleSelect.compareWith = (a: Listitem, b: Listitem) => a && b && a.value === b.value;
      });
  }





  logincheck() {
    try {
      if (this.operpassword === '') {
        alert('Password is mandatory');
      } else {
        this.loginservice.logincheck(this.listlogin.value).subscribe ( data => {
          this.returnstatus = data;
          this.loginpasswordpojo = this.returnstatus.returnObject[0];
          if (this.loginpasswordpojo.javapassword !== '') {
              this.operatorpassword = this.loginpasswordpojo.javapassword;
          } else {
            this.operatorpassword = this.loginpasswordpojo.operpassword;
          }
          if (this.operpassword === this.operatorpassword) {
              this.operpassword = '';
              localStorage.setItem('currentUser', JSON.stringify(this.listlogin));
            // sessionStorage.setItem('currentUser', this.listlogin.text);
            // sessionStorage[this.listlogin.text] = this.listlogin.value;
              window.location.reload();
              this.route.navigate(['/home']);
          } else {
            alert('Invalid Password');
            this.operpassword = '';
          }
        } , error => {alert(error); });

      }
    } catch (error) {
      alert(error);
  }

  }

}

```

**Comment by macjohnny** [comment]
please change your import to

import { MatSelectModule } from '@angular/material';

moreover, make sure that `node_modules/@angular/material` exists and `node_modules/ngx-mat-select-search/node_modules/@angular/material` does not exist. if it does, you might have installed the devDependencies

**Comment by vijaynet10** [comment]
MatSelectModule  already included @ ngmodule 
```
@NgModule({
  declarations: [
    AppComponent,    HomeComponent,    LoginComponent,
    StoneComponent,    OrderproductimageComponent,    OrderviewComponent,
    IssuetosmithComponent,    IssuetosmithdialogComponent,    OrderentryComponent,
    OrdercancelComponent,    OrdereditComponent,    DuplicateprintComponent,
    OrderentrystoneComponent,    OrderentrypaymentComponent,    OrdercustomersignComponent,
    OrderauthorizersignComponent,    OrderentrystepperComponent,    ProposeddiaglogComponent,
    InstructiondialogComponent,    NumberonlyDirective,  ],
  imports: [
    BrowserModule,    RouterModule.forRoot(approutes, { useHash: true }),
    MatFormFieldModule, MatInputModule,    BrowserAnimationsModule,
    MatButtonModule,    MatCheckboxModule,    **MatSelectModule**,
    FormsModule,    HttpClientModule,    MatTableModule,    MatPaginatorModule,
    MatDialogModule,    MatCardModule,    MatIconModule,    MatMenuModule,
    FlexLayoutModule,    MatChipsModule,    PinchZoomModule,    MatTabsModule,
    MatDatepickerModule,    MatRadioModule,    MatGridListModule,
    SignaturePadModule,    MatSnackBarModule,    MatStepperModule,
    StorageServiceModule,    ReactiveFormsModule.withConfig({ warnOnNgModelWithFormControl: 'never' }),
    NgxLoadingModule.forRoot({}),    MatAutocompleteModule,
    **NgxMatSelectSearchModule**

  ], entryComponents: [
    StoneComponent,    OrderproductimageComponent,    IssuetosmithdialogComponent,
    OrderentrystoneComponent,    OrderentrypaymentComponent,    OrdercustomersignComponent,
    OrderauthorizersignComponent,    ProposeddiaglogComponent,    InstructiondialogComponent,
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: initializeApp,
      deps: [AppconfigserviceService], multi: true
    }, AppconfigserviceService, DatePipe,
  ],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA]
})
export class AppModule { }
```

**Comment by macjohnny** [comment]
Can you please not ignore half of my suggestions? Otherwise it will be very difficult to find the problem in your project.

**Comment by vijaynet10** [comment]
**Both Folder exists inside the node_modules**, without folder exists it wont run...

![material folder](https://user-images.githubusercontent.com/4167992/53938728-24bca580-40d7-11e9-8a3f-d3337392e902.png)
![ngx-mat-select-search](https://user-images.githubusercontent.com/4167992/53938730-25553c00-40d7-11e9-94b4-c4c49a8ae6c7.png)

**Comment by macjohnny** [comment]
please read my comment carefully:
>  make sure that `node_modules/@angular/material` exists and `node_modules/ngx-mat-select-search/node_modules/@angular/material` does not exist.

**Comment by vijaynet10** [comment]
i am sure about that , _node_modules/@angular/material_ exists and `node_modules/ngx-mat-select-search/node_modules/@angular/material` does not exist.

**Comment by macjohnny** [comment]
can you please copy the relevant parts of your code provide an example on stackblitz based on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?

**Comment by vijaynet10** [comment]
I Have deleted the node_modules folder and i ran the `npm install` **its working now** , thanks for the support and great invention ... have a great day...

**Comment by whtrbit** [comment]
Had the same issue in spec. When trying to reproduce on Stackblitz the same error occurred in implementation. It turned out that we cannot import MatFormField and MatSelect from @angular/material factory:
`import { MatFormFieldModule, MatSelectModule } from '@angular/material';`
Instead you need import from form-field and select sub factories:
`
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
`

**Comment by charlesritchea** [comment]
@macjohnny I'm seeing this with 6.0.0 (I'm still on legacy material) and none of the suggestions here worked. Debugging indicated that the MatLegacySelect class it's looking for is technically a different class from the one provided by DI. Everything is the same 15.0.0 version so there's no obvious reason for this. I noticed that NgxMatSelectSearchModule doesn't import MatLegacySelectModule itself. Is that an oversight or intentional?

**Comment by macjohnny** [comment]
@charlesritchea version 6.0.0 should work with MatLegacySelectModule@15, see https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/CHANGELOG.md#600

can you open a new bug and add the relevant parts of your package.json, module imports etc?

**Comment by charlesritchea** [comment]
I won't be able to do that and I found a workaround, but shouldn't an NgModule import the Angular Material modules that are needed?

**Comment by macjohnny** [comment]
in https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/ngx-mat-select-search.module.ts#L29-L35, all angular material modules used in the template of ngx-mat-select-search are imported

**Comment by charlesritchea** [comment]
MatSelectModule is used and not imported isn't it? We don't have to keep talking about this but just an observation

**Comment by macjohnny** [comment]
no the component itself is not used in the template, just the MatSelect component symbol is injected
