### ISSUE TITLE
[BUG] TypeError: "n._noEntriesFound is not a function"

### ISSUE THREAD

**Issue by filipklepo** [bithost-gmbh/ngx-mat-select-search#113]
When using version 1.5.2 and 1.5.3, error from title occurs and page does not render properly. Template I am using is the following one:

```html
<mat-select placeholder="Advanced search fields" [multiple]="true" [formControl]="paramsMultiCtrl"
                                        #multiSelectParams>
                                <ngx-mat-select-search [formControl]="paramsMultiFilterCtrl" placeholderLabel="Attribute..."></ngx-mat-select-search>
                                <mat-option *ngFor="let param of filteredParamsMulti | async" [value]="param">
                                    {{param}}
                                </mat-option>
</mat-select>
```

When using version 1.5.0 and 1.5.1 there are no errors (I did not try older versions). From "stack trace" in console, error occurs on rerendering. This is obviously a version-related problem and I can't provide more context since this was a quick version downgrade fix.

**Desktop (please complete the following information):**
 - OS: Ubuntu 17.10
 - Browser: Chromium 67.0.3396.99, Mozilla Firefox 67.0a1

**Comment by macjohnny** [comment]
@filipklepo @jfwork could you please post the stack trace?
I cant reproduce your issue with e.g. https://stackblitz.com/edit/github-mdpasw?file=src/app/examples/02-multiple-selection-example/multiple-selection-example.component.html

here is a comparison what changed between `1.5.1` and `1.5.2`, so there are changes related to `_noEntriesFound()`: https://github.com/bithost-gmbh/ngx-mat-select-search/compare/1.5.1...1.5.2

However, I still can't figure out why the error is thrown in your code. could you please try and help me find the cause of the error by posting more details?

**Comment by filipklepo** [comment]
Stack trace: 
`TypeError: "n._noEntriesFound is not a function"
    Um https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    updateDirectives https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    detectChanges https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    ngOnInit https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    __tryOrUnsub https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    r https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    __tryOrUnsub https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    emit https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    writeValue https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Ao https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    ngOnChanges https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    vr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    vr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    vr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    zr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Sy https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    updateDirectives https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Tr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Sr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Tr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Mr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Tr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Sr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    detectChanges https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    tick https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    tick https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    invoke https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    onInvoke https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    invoke https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    run https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    run https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    r https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    __tryOrUnsub https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    next https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    emit https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    Yt https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    onHasTask https://oss.dev.zg.iskon.hr/b2b/main.dcd6074763da50a7e76f.bundle.js:1
    hasTask https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    _updateTaskCount https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    _updateTaskCount https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    runTask https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1
    d https://oss.dev.zg.iskon.hr/b2b/polyfills.1df2a7478888e7d09648.bundle.js:1`

**Comment by filipklepo** [comment]
Stack trace:
`TypeError: "n._noEntriesFound is not a function"
    Um https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    updateDirectives https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    detectChanges https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    ngOnInit https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    __tryOrUnsub https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    r https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    __tryOrUnsub https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    emit https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    writeValue https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Ao https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    ngOnChanges https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    vr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    vr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    vr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    zr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Sy https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    updateDirectives https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Tr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Sr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Tr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Mr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Tr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Sr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    yr https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    detectChanges https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    tick https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    tick https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    invoke https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    onInvoke https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    invoke https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    run https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    run https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    r https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    __tryOrUnsub https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    _next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    next https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    emit https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    Yt https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    onHasTask https://myapp/main.dcd6074763da50a7e76f.bundle.js:1
    hasTask https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    _updateTaskCount https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    _updateTaskCount https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    runTask https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1
    d https://myapp/polyfills.1df2a7478888e7d09648.bundle.js:1`

**Comment by macjohnny** [comment]
@filipklepo could you paste the relevant parts of your code into the stackblitz example?

**Comment by macjohnny** [comment]
@filipklepo I still wasn't able to reproduce your situation. I kindly ask you to free some of your time to help me finding the problem and release a bugfix if necessary.

**Comment by macjohnny** [comment]
@filipklepo could you help me please?

**Comment by macjohnny** [comment]
it seems that in your case there was a mismatch between the component code and the template code. Could you re-try again, making sure to re-start the angular cli after updating the component? Most likely some code was not correctly refreshed.
If the issue occurs again, please post it here, so I will re-open the issue.
