### ISSUE TITLE
[FEATURE] Searching spinner

### ISSUE THREAD

**Issue by mstawick** [bithost-gmbh/ngx-mat-select-search#114]
**Is your feature request related to a problem? Please describe.**
Display indication during async search operations

**Describe the solution you'd like**
New `@Input searching: boolean = false` could be added, which would cause a mat-spinner to be displayed as matSuffix, in the place where (x) clear icon is shown

**Describe alternatives you've considered**
Allow custom styling of the search input field, though this is more complex.

**Additional context**
When search needs to hit the server and involve debounce on typed in text, it's a much nicer experience when an indication is shown that something is happening.

If you think this can be added, I can code it.

**Comment by macjohnny** [comment]
sounds good. looking forward to your PR

**Comment by macjohnny** [comment]
@mstawick this feature was released with version `1.6.0`
