### ISSUE TITLE
How i can place the filtered selected elements on the end of the model?

### ISSUE THREAD

**Issue by gustavovitor** [bithost-gmbh/ngx-mat-select-search#118]
Hello everyone!

Well, how i can do this? Today, after filter the elements and select the values, that values is includes on my model but on the init of the array (positions 0,1 [...]), how i can change it? I need that after select value, this values go to end of the array model. I'ts possible today?

Using sort comparator i can change it, but this work fine out of the filter, but on the "merge" of the filtered and selected itens with the control itens, i dont know i can do. Anybody can help me?

**Comment by macjohnny** [comment]
can you please provide a minimal example of your code based on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html

As far as I understand your issue, I suggest you to listen to the change event and handle adding removing elements from your selection list in a custom `handleSelectionChange()` method:
```html
<mat-select (selectionChange)="handleSelectionChange($event)">
``` 
(see https://material.angular.io/components/select/api#MatSelect)

**Comment by macjohnny** [comment]
the behavior you describe is due to 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/4b92230643c50a777be5128b1fea014e9abace43/src/app/mat-select-search/mat-select-search.component.ts#L431-L438

**Comment by gustavovitor** [comment]
> can you please provide a minimal example of your code based on https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html
> 
> As far as I understand your issue, I suggest you to listen to the change event and handle adding removing elements from your selection list in a custom `handleSelectionChange()` method:
> 
> ```
> <mat-select (selectionChange)="handleSelectionChange($event)">
> ```
> 
> (see https://material.angular.io/components/select/api#MatSelect)

I have made a simple sortComparator for my mat-select: 
`sortFunc(a, b) { return 1; }`

Put this function into your code and you can see the behavior. All of the filtered and selected elements is going to the first position on control array.

**Comment by macjohnny** [comment]
I suggest you  to handle the selection change individually, with the example in my previous comment.

**Comment by gustavovitor** [comment]
@macjohnny thanks! Work's fine.
