### ISSUE TITLE
[BUG] Using clearSearchInput=false with ngx-mat-select-search outside of a mat-option makes it unusable when search yields no result

### ISSUE THREAD

**Issue by Mabiro** [bithost-gmbh/ngx-mat-select-search#121]
**Describe the bug**
When keeping the active search on close (clearSearchInput=false) while the ngx component is not part of a mat-option, the select then has 0 options, which makes it un-openable.
**To Reproduce**
1. Go to https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example 
2. Set the first sample's ngx-mat-select-search out of the mat-option
3. Make it [clearSearchInput]="false"
4. Type in a search that returns no result then close the panel
5. You can't open up the select again

**Expected behavior**
You should be able to modify your search after reopening the empty select.

**Additional context**
One way I was able to make it work on my implementation was disable the noEntriesFoundLabel div and make one of my own which was wrapped into an option. Maybe something similar could be made here, to ensure there is always atleast one option present?

**Comment by macjohnny** [comment]
How about you add a <mat-option *ngIf=„(filteredOptions| async)?.length === 0></mat-option>“?

**Comment by macjohnny** [comment]
I would say it isn't a bug since you can have this extra dummy option when there are no search results to allow opening the panel again

**Comment by Mabiro** [comment]
@macjohnny Yeah, the dummy option works for me, thank you!
