### ISSUE TITLE
How to use with reactive froms

### ISSUE THREAD

**Issue by akvaliya** [bithost-gmbh/ngx-mat-select-search#122]
I am not much familiar with this component. So correct me if i am wrong.

I tried to use it with reactive forms like below & it's not working

```
<mat-form-field>
  <mat-label [textContent]="translationObj.memberProfileGender"></mat-label>
  <mat-select formControlName="GenderId">
    <mat-option>
      <ngx-mat-select-search></ngx-mat-select-search>
    </mat-option>
    <mat-option *ngFor="let food of foods" [value]="food.value">
      {{food.viewValue}}
    </mat-option>
  </mat-select>
</mat-form-field>
```

My question is that in example that is provided does filtering itself.

How to proper use of this component. Is it just textbox for search & we have to implement filtering our-self?

Not sure how to use it.

**Comment by macjohnny** [comment]
you need to filter the list of options yourself, with the value that you can get from 
```html
<ngx-mat-select-search [formControl]="bankFilterCtrl"></ngx-mat-select-search>
```

See this example: 
https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/master/src/app/examples/01-single-selection-example/single-selection-example.component.html

**Comment by macjohnny** [comment]
it is planned to have a simpler approach for automatic filtering: https://github.com/bithost-gmbh/ngx-mat-select-search/issues/104

**Comment by akvaliya** [comment]
So for now this component does not provide automatic filtering list. Any idea when this feature will be available. I need many select with search in my project & it just time consuming.

**Comment by macjohnny** [comment]
currently, we have no due date for this, but if you want you can help me implementing.
closing this issue as it is tracked in #104
