### ISSUE TITLE
[FEATURE] "No value selected"

### ISSUE THREAD

**Issue by TheParad0X** [bithost-gmbh/ngx-mat-select-search#128]
**Describe the solution you'd like**
It would be nice to have the possibility to choose an "empty" option. So far, once I have selected an option, I cannot unselect it.

Instead of adding a value "No value selected" to my options manually, ngx-mat-select-search should provide the functionality as an @Input(). Something along the lines of "allowNoSelection". A placeholder for the name of this options should be configurable.

Example:
allowNoSelection=true,
emptySelectionPlaceholder='No value selected"

Cheers

**Comment by macjohnny** [comment]
I consider this rather difficult to achieve properly, as the input field only provides the search keyword, but does/can not modify the options themselves

**Comment by TheParad0X** [comment]
You are right. I wrapped your component in my own and it contains the options. I'll close this
