### ISSUE TITLE
[FEATURE] Add flag to disable "adjustScrollTopToFitActiveOptionIntoView" on every options change

### ISSUE THREAD

**Issue by drakeBear** [bithost-gmbh/ngx-mat-select-search#130]
I create a component based on ngx-mat-select-search and [https://github.com/orizens/ngx-infinite-scroll](url) to implement a lazy-loading server search that triggers on scroll to the end of the panel. But on every matSelect.options change it scroll panel to active element:
```js
this._options = this.matSelect.options;
this._options.changes
    .pipe(takeUntil(this._onDestroy))
    .subscribe(() => {
    const keyManager = this.matSelect._keyManager;
    if (keyManager && this.matSelect.panelOpen) {

        // avoid "expression has been changed" error
        setTimeout(() => {
        // set first item active and input width
        keyManager.setFirstItemActive();
        this.updateInputWidth();

        // set no entries found class on mat option
        if (this.matOption) {
            if (this._noEntriesFound()) {
            this.matOption._getHostElement().classList.add('mat-select-search-no-entries-found');
            } else {
            this.matOption._getHostElement().classList.remove('mat-select-search-no-entries-found');
            }
        }

        this.adjustScrollTopToFitActiveOptionIntoView();
        }, 1);

    }
    });
});
```
This causes inconvenience when using lazy loading if active element is at the top of the options list.

I suggest to add flag, something like "scrollToActiveOnOptionsChanged" to control this behavior.

May be i missed something and i can control this somehow for now?

**Comment by macjohnny** [comment]
@drakeBear sounds good.
do you want to create a PR?

**Comment by macjohnny** [comment]
by the way, in the mean time you can simply use version `1.6.0`, which does not contain the `this.adjustScrollTopToFitActiveOptionIntoView();` part

**Comment by drakeBear** [comment]
> @drakeBear sounds good.
> do you want to create a PR?
@macjohnny 
Yes, i will make it.

> by the way, in the mean time you can simply use version 1.6.0, which does not contain the 
> this.adjustScrollTopToFitActiveOptionIntoView(); part
Thanks, i already make fix for my component.

**Comment by macjohnny** [comment]
> Yes, i will make it.

great, so I will release a new version as soon as your PR is merged.

**Comment by macjohnny** [comment]
this is implemented in version `1.7.1`

**Comment by odravison** [comment]
Hello, @macjohnny .

I'm using `ngx-mat-select-search@1.8.0`
and this new feature doesn't work.

Do you know if there is some problem with this feature?

**Comment by macjohnny** [comment]
@odravison can you please open a new issue and describe the problem and reproduction steps?

**Comment by odravison** [comment]
Sure!

**Comment by spanigrahi04** [comment]
I'm using the ngx-mat-select-search and if I scroll the dropdown list from keyboard the highlighted option disappears after 10 down scrolls from top.

**Comment by macjohnny** [comment]
@spanigrahi04 could you please open a new issue with an example?
