### ISSUE TITLE
[FEATURE] 508/screen reader support for mat-select-search-input

### ISSUE THREAD

**Issue by tonyholt** [bithost-gmbh/ngx-mat-select-search#137]
When utilizing the 508 testing tool WAVE for Chrome, there's an issue where the mat-select-search-input does not have a label.  This may also be an issue when utilizing screen reading for the mat-select-search.  

Could we add an @Input string to optionally supply an aria-label for the mat-select-search input?  We could default it to "dropdown search".  This way, the screen readers and other 508 tools will not have issue with this textbox.  I have a commit on a fork that illustrates where I'd like the input to be utilized:

https://github.com/tonyholt/ngx-mat-select-search/blob/6ec0468f8401d864d16660a607727115f4ecb468/src/app/mat-select-search/mat-select-search.component.html#L17

**Comment by macjohnny** [comment]
sounds good. do you want to open a PR for this?

**Comment by tonyholt** [comment]
Sure.  I didn't fully build out the @Input, but I will try that out and issue a PR with my changes.  Thank you for the quick response

**Comment by macjohnny** [comment]
reminder: please add the input to https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/README.md#inputs

**Comment by tonyholt** [comment]
@macjohnny, we can wait until the next release.  I'll hopefully create the PR soon.

**Comment by macjohnny** [comment]
@tonyholt any update on this?

**Comment by tonyholt** [comment]
https://github.com/bithost-gmbh/ngx-mat-select-search/pull/142
