### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by FURQAN2050** [bithost-gmbh/ngx-mat-select-search#141]
is there any way to deselect the item from array list. and not need to open the dropdown and deselect selected  option.?

**Comment by macjohnny** [comment]
Please post an example of your code

**Comment by FURQAN2050** [comment]
![DeepinScreenshot_select-area_20190426143241](https://user-images.githubusercontent.com/31932590/56800096-adcc9f00-6833-11e9-810b-ee7f5e186e48.png)

**Comment by FURQAN2050** [comment]
I want to deselect the item from the circled close button.

**Comment by macjohnny** [comment]
you can use `this.matSelectCtrl.setValue()`, see e.g. https://github.com/bithost-gmbh/ngx-mat-select-search/issues/96#issuecomment-453016659
However, This question is unrelated to mat-select-search, so I close it.
