### ISSUE TITLE
Example for ngx-mat-select-search with grouping option

### ISSUE THREAD

**Issue by vjpc** [bithost-gmbh/ngx-mat-select-search#15]
Hi Mat,

It will be really helpful if you could  please share example for ngx-mat-select-search with grouping option (Select with option groups).

Thanks,
Vijay

**Comment by vjpc** [comment]
@macjohnny  I am new to angular and tried with your github code to modify it for group but finding difficult to do it. It will be nice if you can share one. Thanks.

**Comment by st-clair-clarke** [comment]
@macjohnny @vjpc 
I too would like to have an example for the mat-select with groups. I have been also unsuccessful in generating a filttered select with the groups.

For @macjohnny, instead of using an array of inputs such as your Bank[] array, the shape of the input will now have to be like the one below:

```
export interface Pokemon {
  value: string;
  viewValue: string;
}

export interface PokemonGroup {
  disabled?: boolean;
  name: string;
  pokemon: Pokemon[];
}
```

An example is at [https://material.angular.io/components/select/overview](https://material.angular.io/components/select/overview)

Were you succesful @vjpc? I would also like to see your example.

**Comment by maechler** [comment]
@st-clair-clarke You can place the `ngx-mat-select-search` component, just as you would without option groups, as the first child of `mat-select`. The model and the filter function look a little different then in the existing examples however. I will add an example for this.

**Comment by st-clair-clarke** [comment]
Thanks. Looking forward to your working example ASAP.

Cheers

**Comment by st-clair-clarke** [comment]
Thanks for your help. Working great. I saw where I was making the mistakes.

**Comment by st-clair-clarke** [comment]
Hi.
Again appreciate your help. I am going to request some tweaking to keep your package more in line with material2 select. Please let me know what you think.

Compare your domain models to that of material2 for the select component:

interface Bank {
  id: string;
  name: string;
}
... would/should ? represent the shape of a select option as shown below:

export interface ISelectOption {
  value: string
  viewValue: string
}

.. your 

interface BankGroup {
  name: string;
  banks: Bank[];
}
... would/should ? represent the shape of a select option group:

export interface ISelectOptionGroup {
  disabled?: boolean
  icon?: string
  name: string
  options: Array<ISelectOption>
}

If this is done then your package would be using similar models to material2 select.

Do let me know what you think. And thanks again.

Cheers

**Comment by maechler** [comment]
@st-clair-clarke Thanks for your suggestion! I think it could make sense to adopt the `material2` interfaces.. @macjohnny What do you think?

**Comment by st-clair-clarke** [comment]
I will do that.

NB. Could you please expose the place holder for the search box. Currently it is always saying 'Suche'.

Cheers

**Comment by st-clair-clarke** [comment]
Adjust to material2 interface - Done!

**Comment by maechler** [comment]
@st-clair-clarke Please see https://github.com/bithost-gmbh/ngx-mat-select-search#labels to change the placeholder label.

**Comment by vjpc** [comment]
@st-clair-clarke I had a very specific requirement for grouping and found it difficult to implement using ngx-mat-select. So instead used the mat-autocomplete.

**Comment by st-clair-clarke** [comment]
@vjpc Hi vjpc. Are you saying that you use the mat-autocomplete to implement a form of grouping selection? Could you please share an example, preferable a link to a stackblitz demo?
Cheers

**Comment by macjohnny** [comment]
example added in https://github.com/bithost-gmbh/ngx-mat-select-search/pull/66
