### ISSUE TITLE
Removing/Clearing the selected item

### ISSUE THREAD

**Issue by bsheriff** [bithost-gmbh/ngx-mat-select-search#151]
Hi, I am looking to provide the users of my application with a default "None" option, or after selecting an item, I would want to give the user the ability to clear out the item and have the dropdown return to its original state with only the placeholder of the input displaying.  As of now when I select an item from the ngx-mat-select-search I cannot seem to find a way to remove that item and clear out the selection.  Is there some way I can do this, maybe I am missing something?

Any help and/or recommendations would be appreciated.

Thank You!

**Comment by macjohnny** [comment]
please provide your code as a stackblitz example. you can start with https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

if I correctly understand your question, you can simply add a
```html
<mat-option [value]="null">None</mat-option>
```
selecting it will reset the selected option.
see e.g. https://stackblitz.com/edit/github-bncv5j?file=src%2Fapp%2Fexamples%2F01-single-selection-example%2Fsingle-selection-example.component.html

**Comment by bsheriff** [comment]
Great thank you macjohnny I just wasn't sure where inside of my mat-form-field that I should be placing the "None" mat-option.
