### ISSUE TITLE
[BUG] disableOptionCentering is not working

### ISSUE THREAD

**Issue by harshadray** [bithost-gmbh/ngx-mat-select-search#155]
**Describe the bug**

[disableOptionCentering](https://material.angular.io/components/select/api) api property with this package is not working. 

**To Reproduce**
Apply [disableOptionCentering](https://material.angular.io/components/select/api) api property on mat-select.

https://stackblitz.com/edit/github-oxoguc

**Expected behavior**

It should open after to the bottom of selector instead top of it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 74.0.3729.169

**Smartphone (please complete the following information):**
Not Tested.

**Additional context**

**Comment by macjohnny** [comment]
This is what happens in your example:
![image](https://user-images.githubusercontent.com/5589029/59275433-9cf9b080-8c5c-11e9-8e7f-689b50b8367c.png)


as far as I can see this is the behavior of `<mat-select disableOptionCentering>`, see e.g. https://stackblitz.com/edit/components-issue-1ycmzd?file=app/app.component.html

![image](https://user-images.githubusercontent.com/5589029/59275605-ee09a480-8c5c-11e9-82c7-0d34a09178f4.png)


Or am I missing something?
