### ISSUE TITLE
[BUG] only one option selection

### ISSUE THREAD

**Issue by viethoanganh79** [bithost-gmbh/ngx-mat-select-search#156]
when i search in this component, result just only 1 option, it not fire event when i click this option result

**Comment by macjohnny** [comment]
Please provide a more specific description of your problem.
Please post an example of your code, if possible as a stackblitz app. You can use this as a template:  https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

**Comment by viethoanganh79** [comment]
tks, i using two way binding, its error :v
