### ISSUE TITLE
Label not shown when appearance='outline' [BUG]

### ISSUE THREAD

**Issue by mungpara** [bithost-gmbh/ngx-mat-select-search#159]
**Describe the bug**
When appearance='outline' is applied on mat-form-field, label is hidden or not floated.

**Comment by macjohnny** [comment]
@mungpara thanks for reporting. would you like to implement a fix for this?

**Comment by mungpara** [comment]
> @mungpara thanks for reporting. would you like to implement a fix for this?

fixed

 i forgot to add mat-label in mat-form-field

**Comment by macjohnny** [comment]
did you close the issue because you found a solution? can you share the solution?
