### ISSUE TITLE
Add button to noEntriesFoundLabel

### ISSUE THREAD

**Issue by djanesch** [bithost-gmbh/ngx-mat-select-search#16]
Dear @macjohnny !

First of all great work and very usefull extension.

I don't know if and how it is possible but for one of my business cases I have the request to create an new option if it is not found.
Therefor I thought it would be the best way to just show a create-button after the message but currently the content of noEntriesFoundLabel is only text

I have also create a stackblitz for better understanding:
https://stackblitz.com/edit/github-fej2be?file=src%2Fapp%2Fapp.component.ts

Best regards Daniel

**Comment by macjohnny** [comment]
Hi @djanesch 
you can simply add the button before the options and only show it when the filtered list is empty:

```html
    <mat-select [formControl]="bankCtrl" placeholder="Bank" #singleSelect>
        <ngx-mat-select-search [formControl]="bankFilterCtrl"></ngx-mat-select-search>
        <button mat-button *ngIf="!(filteredBanks | async)?.length" color="accent">create option</button>
        <mat-option *ngFor="let bank of filteredBanks | async" [value]="bank">
          {{bank.name}}
        </mat-option>
      </mat-select>
    </mat-form-field>
```

**Comment by djanesch** [comment]
@macjohnny nice solution, have not considered these one.

**Comment by macjohnny** [comment]
@djanesch if you want to prevent the `noEntriesFoundLabel` to be shown, simply set it to an empty string or `null`.
