### ISSUE TITLE
[BUG] Problems when handle multiple values. 

### ISSUE THREAD

**Issue by antoniofaienza93** [bithost-gmbh/ngx-mat-select-search#160]
**Description**
[x] Bug

**Current behavior** 
I have many values that i want manage with a multiple selection drop down. If i use the example's code, my drop down is too slot (~6000 value). For this i have change the example code in this way: 

```
ngOnInit() {
    // set initial selection
    this.dataMultiCtrl.setValue([]);

    // load the initial state list
    this.filteredDataMulti.next(this.data.features.slice(0,50));

    // listen for search field value changes
    this.dataMultiFilterCtrl.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe(() => {
        this.filterDataMulti();
      })
  }
 .... same example code ...
protected filterDataMulti() {
    if (!this.data) {
      return;
    }
    // get the search keyword
    let search = this.dataMultiFilterCtrl.value;
    if (!search) {
      this.filteredDataMulti.next(this.data.features.slice(0, 50));
      return;
    } else {
      search = search.toLowerCase();
    }

    let res = this.data.features.filter(d => d.properties.name.toLowerCase().indexOf(search) > -1);

    if (res.length > 50) {
      res = res.slice(0,50);
    }

    // filter the banks
    this.filteredDataMulti.next(res);
  }
```
For this reason if I select multiple values ​​that belong to the same range it work well, but if it exceeds the range it cancels the previous selections.

```
<h3>Multiple selection</h3>
      <p>
        <mat-form-field>
          <mat-select [formControl]="dataMultiCtrl" placeholder="Doors" [multiple]="true" (ngModelChange)="optionSelected($event)" #multiSelect>
            <ngx-mat-select-search 
              [formControl]="dataMultiFilterCtrl" 
              [placeholderLabel]="'Find doors...'"
              [noEntriesFoundLabel]="'no matching found'" 
              >
              <mat-icon ngxMatSelectSearchClear>delete</mat-icon>
            </ngx-mat-select-search>
            <mat-option *ngFor="let d of filteredDataMulti | async" [value]="d.properties"  > <!-- In this point we select the level of detail of Filter i.e d.properties-->
              {{d.properties.name}}
            </mat-option>
          </mat-select>
        </mat-form-field>
      </p>
      <p>
        Selected Door:
      </p>
      <ul *ngFor="let d of dataMultiCtrl?.value">
        <li>{{d.name}}</li>
      </ul>
```
As It can be seen I use `(ngModelChange)="optionSelected($event)" ` to trigger the event and emit the result to other component (my leaflet map) to filter the result. 
```
optionSelected(e){
    this.selectedValue.emit(e)
  }
```

How can I handle too many values ​​without giving me problems?

**Used Version**
```
Angular CLI: 7.3.7
Node: 11.9.0
OS: win32 x64
Angular: 7.2.11
"ngx-mat-select-search": "^1.7.6"
```

**Comment by macjohnny** [comment]
when changing the selection, any previously selected option that is not among the available options anymore is cleared, which is why we implemented a selection-restoration mechanism 

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/54b4fd5ff93e2ae9b631ec0501f0c618ddf86c1f/src/app/mat-select-search/mat-select-search.component.ts#L455-L491

you could copy and adapt this code to handle the situation you describe

**Comment by macjohnny** [comment]
I close this since this isn't something we could solve in `ngx-mat-select-search`.
But maybe you can increase the performance when showing all 6000 options at once and use virtual scroll.
