### ISSUE TITLE
Replace '@angular/material' root imports

### ISSUE THREAD

**Issue by wlucha** [bithost-gmbh/ngx-mat-select-search#161]
As of Angular Material 8, root imports of `'@angular/material'` are deprecated. Please change all imports of `'@angular/material'` to specific entry-points imports. 

https://github.com/angular/components/blob/master/CHANGELOG.md#800-osmium-octothorpe-2019-05-28

**Comment by macjohnny** [comment]
Thanks, we will do this when angular material 9 will be released to maximize the period of backwards compatibility

**Comment by macjohnny** [comment]
this is fixed in version `2.0.0`
