### ISSUE TITLE
[FEATURE] Clear text via keyboard

### ISSUE THREAD

**Issue by tbriggs928** [bithost-gmbh/ngx-mat-select-search#162]
**Describe the solution you'd like**
As I am typing to filter the list, I would like to be able to press Shift + Home keys to highlight the text, then Delete key to clear the text.

**Describe alternatives you've considered**
Currently use the X to clear the text, but for some people it is quicker, more intuitive to clear via the keyboard.

**Comment by macjohnny** [comment]
this can be achieved by using the following input:
```
  /**
   * Prevents home / end key being propagated to mat-select,
   * allowing to move the cursor within the search input instead of navigating the options
   */
  @Input() preventHomeEndKeyPropagation = false;
```
can you try if this resolves your request?

**Comment by macjohnny** [comment]
@tbriggs928 does the `preventHomeEndKeyPropagation` input resolve your issue?

**Comment by macjohnny** [comment]
this behavior can be achieved with `[preventHomeEndKeyPropagation]="true"`

**Comment by tbriggs928** [comment]
Thanks for the advice.

The [preventHomeEndKeyPropagation]="false" input allows the Home/End keys to move to first/last item in the list.

But it doesn't change the behavior in the Search box itself.  For example, if I type "ABC123" in the search box to filter the results, then decide I want to search for something else, I have to either click the X to clear the search, or backspace to delete each character.  I was hoping I'd be able to do it via the keyboard by pressing Shift+Home to highlight the text, then press Delete.    I just realized I can press Ctrl +A to highlight the text, then delete it, so there is a way to do this in the keyboard, so not that big a deal, but a regular mat-input let you use Shift+ Home or Shift+End to select text so I was wondering if there was a way to do it in this control as well.  If not, it's fine as is.

Thanks again.

**Comment by macjohnny** [comment]
I tried with shift+home/end and it worked. Which browser/os are you facing issues with?
