### ISSUE TITLE
[BUG] ERROR TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by smartHasmukh** [bithost-gmbh/ngx-mat-select-search#163]
**Describe the bug**
```
ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at FormControlDirective._angular_forms__WEBPACK_IMPORTED_MODULE_30__.FormControlDirective.ngOnChanges (utility-lib.js:1395)
    at checkAndUpdateDirectiveInline
```

Getting error 

I have used this one [Demo](https://stackblitz.com/edit/mat-select-search)

I am using Angular 8
Package.json file

```
    "@angular/animations": "^8.0.1",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "^8.0.1",
    "@angular/compiler": "^8.0.1",
    "@angular/core": "^8.0.1",
    "@angular/forms": "^8.0.1",
    "@angular/http": "^6.1.7",
    "@angular/material": "^8.0.1",
    "@angular/material-moment-adapter": "^8.0.1",
    "@angular/platform-browser": "^8.0.1",
    "@angular/platform-browser-dynamic": "^8.0.1",
    "@angular/router": "^8.0.1",
    "ngx-mat-select-search": "^1.7.6",

```

**Comment by macjohnny** [comment]
Please use the most recent version of `ngx-mat-select-search`, see https://github.com/bithost-gmbh/ngx-mat-select-search#how-to-use-it

does the error still occur with the most recent version?

**Comment by macjohnny** [comment]
can you post your example code as a stackblitz-example?

**Comment by macjohnny** [comment]
could you please provide more information about the line of code where the error occurs?
this could e.g. be in 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/54b4fd5ff93e2ae9b631ec0501f0c618ddf86c1f/src/app/mat-select-search/mat-select-search.component.ts#L389
if the select panel is not defined due to some reason.

**Comment by macjohnny** [comment]
@smartHasmukh can you provide more information?

**Comment by smartHasmukh** [comment]
@macjohnny I will update soon

**Comment by macjohnny** [comment]
@smartHasmukh please provide more information so that I can reopen the issue
