### ISSUE TITLE
Close Icon in ngx-mat-select-search Is not working in a Specific Component

### ISSUE THREAD

**Issue by Elahe73** [bithost-gmbh/ngx-mat-select-search#165]
I'm using ngx-mat-select-search module for being able to have a searchable select in my application. It's working properly and no errors are generated. In one of my specific components that I've rendered it in another one the "Close" icon in the aearch area is not working properly. It show "Close" instead of an icon. I've imported "NgxMatSelectSearchModule" and "MatIconModule" in the related module and also tried importing them into the module of the parent component but it didn't help.

**Comment by macjohnny** [comment]
the `NgxMatSelectSearchModule` imports the `MatIconModule`
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/54b4fd5ff93e2ae9b631ec0501f0c618ddf86c1f/src/app/mat-select-search/ngx-mat-select-search.module.ts#L21
so it is not necessary to import the `MatIconModule` in your module.

It is strange, I have no clue how this situation could occur.

Can you reproduce the situation in a stackblitz example? You can start with https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

**Comment by Elahe73** [comment]
I'm not sure if I can reproduce the situation  but I'll try :)

**Comment by macjohnny** [comment]
in the meantime, you could post the relevant parts of your code and a screenshot of the issue

**Comment by macjohnny** [comment]
@Elahe73 can you provide more information? One explanation could be an error/exception that occurs somewhere, preventing the remaining components from being rendered properly. Does anything show up in the log?

**Comment by macjohnny** [comment]
@Elahe73 please provide more information so that I can reopen the issue.

**Comment by muditaggarwal2001** [comment]
I had the same issue but I was able to get around this problem by including 'https://fonts.googleapis.com/icon?family=Material+Icons' in the app. It seems the example above also has it in index.html file of the app. If the library has dependency on it, then I believe documentation should have specified it.

**Comment by macjohnny** [comment]
@muditaggarwal2001 thanks for the info. Do you want to improve the docs?

**Comment by muditaggarwal2001** [comment]
Sure, no problem. But, shouldn't that style be made part of library instead avoiding the extra step for the app owners to add a global style?

**Comment by macjohnny** [comment]
The icon fonts/styles should be configured globally when setting up angular material.
See 
- https://material.angular.io/components/icon/overview

**Comment by muditaggarwal2001** [comment]
@macjohnny you are right.
Sure, I can update the readme file for it.
