### ISSUE TITLE
[BUG] _co._isToggleAllCheckboxVisible is not a function

### ISSUE THREAD

**Issue by iGitScor** [bithost-gmbh/ngx-mat-select-search#168]
**Describe the bug**

After adding the search in mat-select[multiple], in a build mode, the select doesn't work at all

**Expected behavior**

Handle multiple (with example in the documentation if I did something wrong)

**Screenshots**

<img width="826" alt="Capture d’écran 2019-08-05 à 12 18 35" src="https://user-images.githubusercontent.com/2276944/62457526-57002b00-b77b-11e9-9405-fc01672f1c9f.png">

**Desktop (please complete the following information):**

Chrome, Firefox, Mac OS

**Additional context**
Multiple select

**Comment by macjohnny** [comment]
could be similar like this one: https://github.com/bithost-gmbh/ngx-mat-select-search/issues/113

@iGitScor can you make sure you started a new build process after updating? it seems that there is mismatch between the component code and the template code.

**Comment by iGitScor** [comment]
Hi @macjohnny,

thank you for your response

Here is the template code
```html
<mat-select multiple [(ngModel)]="inquiry.students">
    <mat-select-trigger>
        {{inquiry.students ? inquiry.students[0].firstname : ''}}
        <span *ngIf="inquiry.students?.length > 1" class="example-additional-selection">
                    (+{{inquiry.students.length - 1}} {{inquiry.students?.length === 2 ? 'other' : 'others'}})
                  </span>
    </mat-select-trigger>
    <ngx-mat-select-search ngModel [placeholderLabel]="'Search a student'" (ngModelChange)="filterStudents($event)" [showToggleAllCheckbox]="false"></ngx-mat-select-search>
    <mat-option *ngFor="let coursier of searchedStudents" [value]="student">{{student.name}} {{student.firstname}}</mat-option>
</mat-select>
```

And the component code

```ts
public filterStudents(search) {
  if (search === '') {
    this.searchedStudents = this.students;
  } else {
    this.searchedStudents = this.searchedStudents.filter((student) => student.name.toLowerCase().match(`${search.toLowerCase()}`) || (student.firstname && student.firstname.toLowerCase().match(`${search.toLowerCase()}`)));
  }
}
```

Could you explain me the mismatch ?

**Comment by macjohnny** [comment]
I was referring to a mismatch between the `ngx-mat-select-search` component code and template, not your template, which should not need any update.
can you make sure you completely stopped your build, cleared any caches, and start a new build?

**Comment by iGitScor** [comment]
Yep, I make it on another machine (and also our staging machine) with the same result.

Do you know how to clear the caches you mention ?

**Comment by macjohnny** [comment]
I don't have any details about your build process, so I cannot answer your question.

But apart from that, did you try to check out your project on a different machine, followed by a `npm install` and got the same result?

**Comment by macjohnny** [comment]
try to remove your `node_modules` folder and install the dependencies again.

**Comment by iGitScor** [comment]
`npm install` followed by `ng build` for each deployment

After your advice, the component works like a charm, thank you
