### ISSUE TITLE
Tree shaking rxjs

### ISSUE THREAD

**Issue by mtraynham** [bithost-gmbh/ngx-mat-select-search#17]
[This line](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/app.component.ts#L8) uses a re-export of the `take` & `takeUntil` operators.  Ultimately, it's also including the entirety of the `rxjs/operators` path, without a way for Webpack to tree-shake unused dependencies.

It can be changed to:
```ts
import { take } from 'rxjs/operators/take';
import { takeUntil } from 'rxjs/operators/takeUntil';
```

This reduces my bundle by ~271KB, as seen in the images below.

Before
![beforetreeshake](https://user-images.githubusercontent.com/5741321/38563260-670fecd0-3caa-11e8-8195-7073b4249bd9.png)

After
![aftertreeshake](https://user-images.githubusercontent.com/5741321/38563265-6a923002-3caa-11e8-8271-a17e130363bc.png)

**Comment by macjohnny** [comment]
@mtraynham thanks for reporting this solution! I will release a new version soon.

**Comment by mtraynham** [comment]
@macjohnny One thing, I just tried it locally.  Seems to be using the old `import` in the esm5 bundle.  Maybe the old build got pushed for the new version?

**Comment by mtraynham** [comment]
Ohh I see why, I initially bugged the `app.component.ts` and not the [mat-select-search.component.ts](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts), whoops!

**Comment by macjohnny** [comment]
@mtraynham thanks for pointing this out again. here you go with `1.0.5`
