### ISSUE TITLE
[BUG] input field not focused in bootstrap modal

### ISSUE THREAD

**Issue by gagan95** [bithost-gmbh/ngx-mat-select-search#170]
I'm not able to use ngx-mat-select-search on bootstrap modal since it is not focusing on the input field same issue as provided in https://github.com/angular/components/issues/15093 
kindly update it

**Comment by macjohnny** [comment]
can you please provide a stackblitz example (you can use https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example as a starting point) and describe the reproduction steps in detail?
is it an IE only issue?
can you post the relevant code snippets?

**Comment by gagan95** [comment]
![screencapture-localhost-4200-layout-report-2019-08-28-17_28_34](https://user-images.githubusercontent.com/26519250/63854181-357d1280-c9ba-11e9-998f-a97d21c679b3.png)

the code is working fine in normal html but when i'm using the it in modal( pop up ) i'm facing the issue as input is not focusing

**Comment by macjohnny** [comment]
which browser are you using? what is your code?

**Comment by macjohnny** [comment]
how about adding 
```css
:-ms-input-placeholder.mat-select-search-input {
  -ms-user-select: text !important;
}
```
to your global styles?

**Comment by gagan95** [comment]
no i tried it too its not working

**Comment by macjohnny** [comment]
it will be very difficult to analyze this issue if you don't provide any code snippets.

**Comment by gagan95** [comment]
` 
<mat-select class="form-control mb-1" formControlName="insurance_name" name="insurance_name" placeholder="Insurance" #singleSelect>
                                            <ngx-mat-select-search formControlName="bankFilterCtrl" [placeholderLabel]="'Search Insurance'" [noEntriesFoundLabel]="'No matching records found'"></ngx-mat-select-search>                  <mat-option disabled>
                                                Insurance Name </mat-option>
                                            <mat-option *ngFor="let bank of filteredBanks | async" [value]="bank">
                                                {{bank.name}}
                                            </mat-option>
                                        </mat-select>`

**Comment by macjohnny** [comment]
please provide a reproduction on stackblitz (you can use https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example as a starting point) as the snippet looks ok.

**Comment by macjohnny** [comment]
@gagan95 did you find a solution to your problem? if so, please share some details.

**Comment by gagan95** [comment]
there is a issue in loading the css and js file hierarchy once i checked in stackblitz i got the solution thanks for the response @macjohnny

**Comment by JJGR93** [comment]
> there is a issue in loading the css and js file hierarchy once i checked in stackblitz : https://stackblitz.com/edit/github-xvcxhc i got the solution thanks for the response @macjohnny

Hi! Could you please let me know how did you fixed this problem? Im having it using the ngx-mat-select-search in an UIkit modal. Thank you beforehand!
