### ISSUE TITLE
[BUG] Custom Content doesn't work properly with multi select

### ISSUE THREAD

**Issue by ceyhunn** [bithost-gmbh/ngx-mat-select-search#172]
**Describe the bug**
When I search any text  Clear button and custom content are in the  same place.

**To Reproduce**
1. Go to [https://stackblitz.com/edit/github-fwviup](https://stackblitz.com/edit/github-fwviup)
2. Search any text
3. See design problem.

**Expected behavior**
It would be nice to make custom content be hidden when searching.
**Screenshots**
![Screenshot from 2019-10-01 11-54-02](https://user-images.githubusercontent.com/5506156/65944369-99c04580-e442-11e9-9d2d-a205b8d56efb.png)

**Desktop (please complete the following information):**
OS: Linux -> Manjaro Gnome,
Browser: Chromium
Version: 76

**Comment by macjohnny** [comment]
how about adding `<div class="mat-select-search-custom-header-content" *ngIf="!bankMultiFilterCtrl.value">`?
See https://stackblitz.com/edit/github-fwviup-bkqy9w?file=src/app/examples/06-multiple-selection-select-all-example/multiple-selection-select-all-example.component.html

**Comment by ceyhunn** [comment]
Fantastic, but in firefox there is a design problem

**Comment by macjohnny** [comment]
> but in firefox there is a design problem

what is the problem?

**Comment by ceyhunn** [comment]
> > but in firefox there is a design problem
> 
> what is the problem?

![Screenshot from 2019-10-01 12-27-30](https://user-images.githubusercontent.com/5506156/65946356-0a696100-e447-11e9-96ea-848a8772e9b8.png)

**Comment by macjohnny** [comment]
> Also if I disable multi select option, custom content is started from new line.

you can add this to your global css:

```css
.mat-select-search-inner {
  display: flex;
}
```
or use absolute positioning of your custom content:
```css
.mat-select-search-custom-header-content {
  position: absolute;
}
```

**Comment by macjohnny** [comment]
I can't reproduce the firefox issue, this is what it looks like:
<img width="400" alt="mat-select-search-custom-header-firefox" src="https://user-images.githubusercontent.com/5589029/65946562-b9517100-e436-11e9-9e1f-f15bbe5f595c.png">

I suggest you adjust the styling of `.mat-select-search-custom-header-content` in your css code

**Comment by ceyhunn** [comment]
Yes, I will do. Thank you very much for fast answer.

**Comment by macjohnny** [comment]
happy to help. so can we close this issue?`
by the way, please consider giving this project a star if you like it.

**Comment by ceyhunn** [comment]
This is just demo app that I customized. I will implement this in my project. Thank you so much..
