### ISSUE TITLE
Ivy & Mat-select-search not working?

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [bithost-gmbh/ngx-mat-select-search#173]
**Describe the bug**
The library is not working together with ivy?
![image](https://user-images.githubusercontent.com/1098243/66787414-e8122180-eee3-11e9-94f0-34988ca315e6.png)
Weird because I tested out an upgrade to ivy 2 months ago and had to abandon because of too many issues, but this was not one of them at that time.

**To Reproduce**
well just run the latest ivy build: 9.0.0-next.10, while compiling I get the error (see screenshot)

**Expected behavior**
Take a guess :-p

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LanderBeeuwsaert** [comment]
oh yeah, just want to add: really nice library!

**Comment by macjohnny** [comment]
Thanks for reporting, I will have a look at it

**Comment by LanderBeeuwsaert** [comment]
hehe, what a response time, thanks!

**Comment by macjohnny** [comment]
if you like the project, consider giving it a star ;-)

**Comment by LanderBeeuwsaert** [comment]
:) done!
