### ISSUE TITLE
[BUG] Can't build for production

### ISSUE THREAD

**Issue by Dev4mir** [bithost-gmbh/ngx-mat-select-search#178]
**Describe the bug**
When i try to build for production this error shows up:-
ERROR in ./node_modules/ngx-mat-select-search/fesm2015/ngx-mat-select-search.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

**Desktop:**
 - OS: Linux debian
 - Browser: chrome

**Dependencies**

`"@angular/common": "8.2.8",
"@angular/compiler": "8.2.8",
"@angular/core": "8.2.8",
"@angular/cli": "^8.3.6",
"@angular/compiler-cli": "8.2.8",
"ngx-mat-select-search": "^2.0.0"`

Can anyone help?

**Comment by macjohnny** [comment]
Which version of angular devkit-builder are you using?

**Comment by Dev4mir** [comment]
@macjohnny 
`"@angular-devkit/build-angular": "0.803.6"`

**Comment by macjohnny** [comment]
the production build (`ng build --prod`) of the example app (https://github.com/bithost-gmbh/ngx-mat-select-search-example) seems to work. The following versions are used:
https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/0e45058db56c1af0fe920ac3e188737ffa3df426/package.json#L14-L34

@Dev4mir can you please update to the latest `@angular/cli`, `@angular-devkit/build-angular` and `@angular/core` and see if the problem still persists?

**Comment by Dev4mir** [comment]
Thanks @macjohnny I updated my app with `ng update @angular/cli @angular/core` and now the build for production is working fine.
