### ISSUE TITLE
Ivy compiler - ERROR in No suitable injection token for parameter 'changeDetectorRef' of class 'MatSelectSearchComponent'. no type or decorator]

### ISSUE THREAD

**Issue by st-clair-clarke** [bithost-gmbh/ngx-mat-select-search#179]
**Describe the bug**
When the new ivy compiler is added to angular 8 app, it fails to compile with the message - ERROR in No suitable injection token for parameter 'changeDetectorRef' of class 'MatSelectSearchComponent'.
no type or decorator

**To Reproduce**
Opt-in Ivy by editing the tsconfig.app.json and add a section of angularComplierOptionand set the enableIvyto true. for new Angular CLI projects, you can just use the --enableIvy flag when running your ng newscript.

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": true
  }
}
```

**Expected behavior**
Ivy compiler to compile all packages without errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/3227590/67266536-4c456000-f465-11e9-8002-71ca7d53670d.png)

**Desktop (please complete the following information):**

**Comment by macjohnny** [comment]
Thanks for reporting this issue.
I can reproduce the error with the current master of the example app (`angular/core@8.2.11` (with ivy preview enabled) and `ngx-mat-select-search@2.0.0`) (https://github.com/bithost-gmbh/ngx-mat-select-search-example/tree/2.0.0)

With `angular/core@9.0.0.next-10` (which has ivy enabled)  `ngx-mat-select-search@2.0.0` it works fine: https://github.com/bithost-gmbh/ngx-mat-select-search-example/tree/angular-9-ivy

I guess this is some build-related problem.

So far, the solution would be to use 
* `ngx-mat-select-search@1.8.0` for `@angular/core: < 8.0.0` or `@angular/core:^8.0.0` with ivy enabled
* `ngx-mat-select-search@2.0.0` for `@angular/core: ^8.0.0` without ivy or `@angular/core:^9.0.0` with ivy

**Comment by PritiMaurya** [comment]
@macjohnny I am not able to reproduce by using ngx-mat-select-search@2.0.0

I am using     "@angular/cli": "^8.3.19",

**Comment by macjohnny** [comment]
@PritiMaurya can you please open a new issue and provide all the necessary information?
