### ISSUE TITLE
question: how to translate [placeholderLabel]="'Select Category'"

### ISSUE THREAD

**Issue by JomalJohny** [bithost-gmbh/ngx-mat-select-search#180]
**[placeholderLabel]="'Select Category'" angular translation label not working**
I have issues in Internationalization (i18n) in Angular, The select search label [placeholderLabel]="'Select Category'" is not translating. Provide a description about how to translate this placeholder

**Comment by macjohnny** [comment]
this should answer your question: https://stackoverflow.com/a/57374124
can you please post your code?

**Comment by JomalJohny** [comment]
Thanks for the update. it's resolved my issues
https://stackoverflow.com/questions/57369486/angular8-i18n-for-placeholderlabel-text/57374124#57374124

**Comment by JomalJohny** [comment]
Thanks for the update. it's resolved my issues
https://stackoverflow.com/questions/57369486/angular8-i18n-for-placeholderlabel-text/57374124#57374124

**Comment by macjohnny** [comment]
@JomalJohny glad it works. can you please mark https://stackoverflow.com/questions/57369486/angular8-i18n-for-placeholderlabel-text/57374124#57374124 as the accepted answer?
