### ISSUE TITLE
[BUG] ToggleAllCheckbox doesn't use correct theme color

### ISSUE THREAD

**Issue by LoganDupont** [bithost-gmbh/ngx-mat-select-search#183]
**Describe the bug**
When I try to add `color="accent"` to the mat-form-field of "Multiple selection with select All Checkbox" the accent color is not set on the ToggleAllCheckbox in ngx-mat-select-search.

**To Reproduce**
See _Multiple selection with Select All Checkbox_ in this [demo](https://stackblitz.com/edit/github-kd99xm) and toggle the AllCheckbox in the ngx-mat-select-search. You will see that the color is not set correctly and the primary color will be used.

**Expected behavior**
The ToggleAllCheckbox should be in the correct color. In this example it should be the accent color

**Comment by macjohnny** [comment]
@LoganDupont thanks for reporting the issue. would you like to implement a fix for this?

**Comment by LoganDupont** [comment]
@macjohnny Well, I had a look at the code and it seems that the creators are using a mat-select which means that the  color attribute needs to be provided. So I guess we will need a new input to set the theme color on the mat-select but i'm not sure if that's the best solution?

**Comment by macjohnny** [comment]
I think the color attribute of the mat-select could be reused

**Comment by macjohnny** [comment]
a fix was released with version `2.1.0`
