### ISSUE TITLE
[FEATURE] Performance improvements

### ISSUE THREAD

**Issue by tricasoft** [bithost-gmbh/ngx-mat-select-search#185]
**Performance with cdk-virtual-scroll-viewport**

**Comment by macjohnny** [comment]
@tricasoft can you give more details about what you want to tell us?

**Comment by tricasoft** [comment]
When having a big list of items you want to show (which is the case when you need a search), the performance drops significantly. After click you have to wait a bit until the dropdown is displayed.
If we could use the https://material.angular.io/cdk/scrolling/overview together with this component it would greatly improve performance.

**Comment by macjohnny** [comment]
could you set up a reproduction example on stackblitz, starting with  https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?
moreover, would you be willing to provide a fix for this issue?

**Comment by tricasoft** [comment]
I was wrong, it is working as expected:

<mat-form-field>
	<mat-select formControlName="ctrl" placeholder="Ctrl" #singleSelect (selectionChange)="ctrlList()">

	  <mat-option>
	    <ngx-mat-select-search [formControl]="filter"></ngx-mat-select-search>
	  </mat-option>
	  <cdk-virtual-scroll-viewport [itemSize]="42" [style.height.px]=4*42>
	    <mat-option *cdkVirtualFor="let ct of ctList" [value]="ct">{{ct.name}}</mat-option>
	  </cdk-virtual-scroll-viewport>
	</mat-select>
</mat-form-field>

You can, maybe, add this info into documentation or another example on stackblitz.

Thanks!

**Comment by macjohnny** [comment]
@tricasoft would you like to open a pr to add n example?

**Comment by tricasoft** [comment]
@macjohnny what do you mean by pr?

**Comment by macjohnny** [comment]
a pull-request on github to add an example to https://github.com/bithost-gmbh/ngx-mat-select-search/tree/master/src/app/examples

**Comment by tricasoft** [comment]
I made a stackblitz here: https://github-qbzntq.stackblitz.io
You can see the first example is modified to use the cdk-virtual-scroll-viewport
There is an issue: if you search for "q" and click on "Bank Q (Germany)", the value (bellow) will be set correctly, but the value in the select is not set appropriately, the placeholder appears as if there is no selected value.
Is this related to cdk-virtual-scroll-viewport? I use cdk-virtual-scroll-viewport with normal Select component and it's working as expected.

Thanks!

**Comment by macjohnny** [comment]
I think the issue is rather related to mat-select itself

**Comment by tricasoft** [comment]
Well, maybe you're better suited to report a bug on this?
