### ISSUE TITLE
[BUG] Accessibility issue where screen-readers can only see 'blank'

### ISSUE THREAD

**Issue by TroyHouston** [bithost-gmbh/ngx-mat-select-search#186]
If you use a screenreader (I am using [NVDA](https://www.nvaccess.org/download/)) and try to navigate the dropdown using the keyboard it will always read out 'blank' for each item (or the value entered into the search field).

However if the dropdown is not opened then it does read out the value properly.

See both scenarios in action below

**To Reproduce**
1. Install NVDA
1. Go to the [demo site](https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html)
2. Open NVDA
3. Tab to the selector
3. Press spacebar to open the dropdown
3. Use the arrow keys to navigate the dropdown, each option will be read as 'blank' (or the value entered into the search field)

**Expected behavior**
I would expect the screen-reader to be able to navigate and read out all the options in the list whether the dropdown is open or closed.

**Example Gif**
![SelectSearchA11y](https://user-images.githubusercontent.com/4496632/69205686-8c584980-0baf-11ea-906d-49a6f16b58f7.gif)

**Desktop**
 - OS: Windows 10
 - Browser: Chromium Edge (Also found in other browsers)
 - Version: 80.0.334.2

**Comment by macjohnny** [comment]
@TroyHouston thanks for reporting this issue. I think the problem is that the input field is focused.
Would you like to try and find a solution to tell the screen reader to e.g. read the entered search value and the currently highlighted select value?

**Comment by macjohnny** [comment]
@ZacaryPaynter thanks for the fix, it was released with version `2.1.0`
