### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ashike12** [bithost-gmbh/ngx-mat-select-search#187]
**Describe the bug**
Looks like input has default placeholder 'Suche'

**To Reproduce**
go there and don't type anything, you will find the issue
https://stackblitz.com/edit/mat-select-search?file=app%2Fmat-select-search%2Fmat-select-search.component.ts
**Expected behavior**

should have a option for placeholder

**Screenshots**
i found default text in MatSelectSearchComponent.
![ngx-select-search](https://user-images.githubusercontent.com/22310513/69727912-9baa3a80-114d-11ea-9a44-5080f2802370.PNG)

**Additional context**
Same problems with no entries found

**Comment by macjohnny** [comment]
See https://github.com/bithost-gmbh/ngx-mat-select-search#inputs and https://github.com/bithost-gmbh/ngx-mat-select-search#labels
