### ISSUE TITLE
[BUG] Testing with Jest - cannot inject MatSelect

### ISSUE THREAD

**Issue by mptyspace** [bithost-gmbh/ngx-mat-select-search#188]
**Bug**
I found an issue when switching from karma/jasmine to Jest. After the switch it warned me it couldn't find MatSelect.

**Resolution**
After some digging I managed to resolve the issue by changing the imports from @angular/material/select to @angular/material.
Since the latter is no longer the preferred import style, is it possible this can be resolved?

**specifications**
package json config (and installed)
```
"dependencies": {
    "@angular/animations": "^8.2.7",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "^8.2.7",
    "@angular/compiler": "^8.2.7",
    "@angular/core": "^8.2.7",
    "@angular/forms": "^8.2.7",
    "@angular/material": "^8.2.0",
    "@angular/platform-browser": "^8.2.7",
    "@angular/platform-browser-dynamic": "^8.2.7",
    "@angular/router": "^8.2.7",
    "core-js": "^2.6.9",
    "hammerjs": "^2.0.8",
    "ngx-mat-select-search": "^1.8.0",
    "rxjs": "^6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.5",
    "@angular/cli": "^8.3.5",
    "@angular/compiler-cli": "^8.2.7",
    "@angular/language-service": "^8.2.7",
    "@types/jest": "^24.0.23",
    "@types/node": "^10.14.15",
    "codelyzer": "^5.0.1",
    "jest": "^24.9.0",
    "jest-junit": "^9.0.0",
    "jest-preset-angular": "^8.0.0",
    "node-sass": "^4.11.0",
    "protractor": "^5.4.2",
    "ts-node": "^8.3.0",
    "tslint": "^5.18.0",
    "typescript": "3.5.3"
  }
```

**Comment by macjohnny** [comment]
which versions of angular, angular material and ngx-mat-select-search are you using?

**Comment by mptyspace** [comment]
> which versions of angular, angular material and ngx-mat-select-search are you using?

Updated with specifications

**Comment by macjohnny** [comment]
`ngx-mat-select-search@1.8.0` uses the `@angular/material` import, while `ngx-mat-select-search@2.0.0` uses the `@angular/material/select` import, so could you try updating ngx-mat-select-search to version `2.0.0`?

**Comment by mptyspace** [comment]
That'll do the trick then, thanks. I noticed I have a few other tests with similar issues, and it's about the similarity of the import.
