### ISSUE TITLE
Issues on uppermost toggleSelectAll checkbox still checked even if the list of data names are all unchecked(UI)

### ISSUE THREAD

**Issue by Donzkie24** [bithost-gmbh/ngx-mat-select-search#189]
![image-2019-12-04-16-34-54-663](https://user-images.githubusercontent.com/45349148/70233202-0b957200-1799-11ea-911b-3c76d459919e.png)

**Comment by macjohnny** [comment]
the checked state of the "check all" checkbox has to be controlled in your application and passed as an input parameter:
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/d19c777ded98457cbdd4be476246ae96c52d7f02/src/app/mat-select-search/mat-select-search.component.ts#L159-L160
