### ISSUE TITLE
Is it possible to collapse grouping options 

### ISSUE THREAD

**Issue by gomteshhatgine** [bithost-gmbh/ngx-mat-select-search#191]
I want to add collapse grouping options in select

like in
[https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fexamples%2F04-option-groups-example%2Foption-groups-example.component.html](url)

Here **Single selection with option groups** 
I want collapse groups in select
Is there any way to implement
please help
Thanks

**Comment by macjohnny** [comment]
can you please give more detailed information about what you want to achieve?
a sketch or an example might be useful

**Comment by gomteshhatgine** [comment]
I want to implement like here **Collapsible with Search:**
[https://codepen.io/sathomas/pen/VpJeEo](url)

Like this : 
![Screenshot from 2019-12-10 17-33-29](https://user-images.githubusercontent.com/10737306/70528160-8da7e100-1b73-11ea-9fec-54b01bc299c5.png)

**Comment by macjohnny** [comment]
I don't think there is such a feature in the mat-select (https://material.angular.io/components/select/overview)

However, you could try to combine mat-tree (https://material.angular.io/components/tree/overview) with an overlay (https://material.angular.io/cdk/overlay/overview)

I am closing this as this is not directly related to ngx-mat-select-search
