### ISSUE TITLE
Ngx-mat-select-search keyboard interaction

### ISSUE THREAD

**Issue by saravanacs** [bithost-gmbh/ngx-mat-select-search#192]
Hi ,
I'm using ngx-mat-select-search in my project. Its working fine. Now, searching filtered data to i click tab button in keyboard to select the search item. Default set, 'enter' button click to select the item. I also need tab button click to select the item in ngx-mat-select-search. Please suggest any ideas . 
Happy coding ..!!

My screenshot here,
![image](https://user-images.githubusercontent.com/43574327/70592654-94306a00-1c00-11ea-9773-bb1180968d27.png)

**Comment by macjohnny** [comment]
This behavior was implemented in mat-select, see https://github.com/angular/components/issues/17442

**Comment by saravanacs** [comment]
@macjohnny 
Environment
Angular/cli version - 8.3.9

**Comment by macjohnny** [comment]
which version of `@angular/material` are you using?
the fix was released in [@angular/material@9.0.0-rc.1](https://github.com/angular/components/releases/tag/9.0.0-rc.1)

**Comment by saravanacs** [comment]
![image](https://user-images.githubusercontent.com/43574327/70599321-debae200-1c12-11ea-999f-a784dd19bfb5.png)


My angular/material version is 8.2.3 sir.

**Comment by saravanacs** [comment]
@macjohnny Thanks for your reply sir. I'll update my angular material version 9 and let you know . Is working or not sir
