### ISSUE TITLE
How can I change Place holder for Search and Records not found

### ISSUE THREAD

**Issue by gomteshhatgine** [bithost-gmbh/ngx-mat-select-search#193]
I want to show place holder like "Search" and "Not Found" after no result match with search text
Currently it is showing like **Suche** and **Keine Optionen gefunden**
I.e. I want change this text as shown in image

![Screenshot from 2019-12-11 23-52-27](https://user-images.githubusercontent.com/10737306/70648914-19a03280-1c72-11ea-8587-475cd628da04.png)

![Screenshot from 2019-12-11 23-52-14](https://user-images.githubusercontent.com/10737306/70648877-02614500-1c72-11ea-93f3-963c9cba343d.png)

**Comment by macjohnny** [comment]
Please have a look at the readme:
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/README.md#labels

**Comment by gomteshhatgine** [comment]
Thanks
