### ISSUE TITLE
Selected option will be hidden under the search input field.

### ISSUE THREAD

**Issue by vinodhreddygs** [bithost-gmbh/ngx-mat-select-search#199]
Hi, 

Selected option is hiding under the search input field when opening the options panel.
Is there any way to show drop down along with search input field under the selected option.

Thanks in advance.

**Comment by macjohnny** [comment]
the behavior you describe should be enabled by default and can be disabled with 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/4138c7523db4b580bb641840d08331808e14a781/src/app/mat-select-search/mat-select-search.component.ts#L158-L159

can you please provide a stackblitz example (you can start with https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example)?

**Comment by macjohnny** [comment]
@vinodhreddygs can you please provide more information?

**Comment by macjohnny** [comment]
When there is more information available, allowing to properly investigate the issue, I will be happy to re-open it
