### ISSUE TITLE
Horizontal scrollbar flashes on opening and closing animation

### ISSUE THREAD

**Issue by sylvaingi** [bithost-gmbh/ngx-mat-select-search#2]
During the opening and closing animations of the mat-select's options panel, when using ngx-mat-select-search an horizontal scrollbar appears then disappears in the panel.

The issue can be seen with the provided example at https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

**Comment by macjohnny** [comment]
@sylvaingi thanks for reporting. would you like to try to improve this?

**Comment by sylvaingi** [comment]
I'll try to have a deeper look in the upcoming weeks. I've quickly tried to isolate the root issue, without success.

**Comment by macjohnny** [comment]
@sylvaingi I noticed that also the width of the search field extends beyond the option overlay while opening / closing. I guess it is the search field width that causes the scroll bar to appear.

**Comment by macjohnny** [comment]
@alexandrupaul7 thanks for solving the issue. I will publish a new version on npm tomorrow.
