### ISSUE TITLE
Select all option required

### ISSUE THREAD

**Issue by mallik482** [bithost-gmbh/ngx-mat-select-search#20]
How can I select all options from the dropdown

**Comment by macjohnny** [comment]
@mallik482 what do you mean by 
>  select all options from the dropdown

do you wan't to programatically select all options in multi-select mode?
how is this related to `ngx-mat-select-search`?

**Comment by macjohnny** [comment]
I don't think this is related to `ngx-mat-select-search`, so I am closing this for now.
@mallik482 if you still think this is an issue, please open a new issue and provide more details on what you want to achieve, what you have tried so far, code, etc.
