### ISSUE TITLE
Search is not working with dynamic data

### ISSUE THREAD

**Issue by shaukath** [bithost-gmbh/ngx-mat-select-search#204]
Loading dynamic data on scroll to mat options , in this scenario search is not working.

If I change the data randomly then also search is not working.

**Comment by macjohnny** [comment]
Can you please provide an example?

**Comment by shaukath** [comment]
Add some data to mat options, while scrolling I am pushing some more data to same options array after that search is not working

**Comment by macjohnny** [comment]
I think this is a duplicate of https://github.com/bithost-gmbh/ngx-mat-select-search/issues/200
Please continue the discussion there.
A contribution/fix would be appreciated.
