### ISSUE TITLE
ngx-mat-select-search "Keine Optionen gefunden" message not replace

### ISSUE THREAD

**Issue by HrshPtl** [bithost-gmbh/ngx-mat-select-search#206]
- I follow this way to install NgxMatSelectSearch ( https://github.com/bithost-gmbh/ngx-mat-select-search )
- NgxMatSelectSearch  working fine
- Whenever data not found in select list is given "Keine Optionen gefunden" message
![Capture](https://user-images.githubusercontent.com/38342527/73354401-a606c300-42bb-11ea-8f0d-1fa1ad00bd13.PNG)

- But i want this message in English like "No records found"
- There are no way to replace this message

**Comment by macjohnny** [comment]
see https://github.com/bithost-gmbh/ngx-mat-select-search#labels
