### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by tcetin** [bithost-gmbh/ngx-mat-select-search#211]
I am facing this error when try to `ng build --prod` production build.

`TypeError: Cannot read property 'kind' of undefined`

How can I solve this error?

**Comment by macjohnny** [comment]
see https://github.com/bithost-gmbh/ngx-mat-select-search/issues/178
please update `@angular-devkit/build-angular` to a newer version.

**Comment by macjohnny** [comment]
@tcetin please let me know if this works for you. if it doesn't, i will re-open the issue.

**Comment by tcetin** [comment]
`An unhandled exception occurred: Job name "..getProjectMetadata" does not exist.` problem is causing after updated.

**Comment by macjohnny** [comment]
can you please post all versions used with `ng --version`?

**Comment by tcetin** [comment]
```

Angular CLI: 8.3.5
Node: 10.16.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.5
@angular-devkit/core         8.3.5
@angular-devkit/schematics   8.3.5
@schematics/angular          8.3.5
@schematics/update           0.803.5
```

**Comment by macjohnny** [comment]
can you please update to `@angular-devkit/build-angular@0.803.24`?
you can run
```
ng update @angular/core@8 @angular/cli@8 @angular-devkit/build-angular@0.803
```

**Comment by tcetin** [comment]
Ok it worked with  updating "@angular-devkit/build-angular": "0.803" in `npm` dependencies.
Thanks

**Comment by loncho67880** [comment]
> can you please update to `@angular-devkit/build-angular@0.803.25`?
> you can run
> 
> ```
> ng update @angular/core@8 @angular/cli@8 @angular-devkit/build-angular@0.803
> ```

Thank you, i copied this versions and woked good: https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/0e45058db56c1af0fe920ac3e188737ffa3df426/package.json#L14-L34
