### ISSUE TITLE
[BUG] Angular 6 : How to combine serverside and multiple selection

### ISSUE THREAD

**Issue by ngthaiduong31191** [bithost-gmbh/ngx-mat-select-search#212]
Hi all, I get some issues when implement ngx-mat-select-search. 
I'm using angular 6. My ngx-mat-select-search is 1.7.5
When add it in a component :<app-search></app-search> and embed this to app.component. I got error
Angular: 'ngx-mat-select-search' is not a known element

Please help me. thank you so much.

**Comment by macjohnny** [comment]
You need to import the NgxMatSelextSearchModule

**Comment by ngthaiduong31191** [comment]
> You need to import the NgxMatSelextSearchModule

Where I have to import it? sorry i'm just new in this one.

**Comment by macjohnny** [comment]
you need to import it in your app module, see https://github.com/bithost-gmbh/ngx-mat-select-search#how-to-use-it

**Comment by ngthaiduong31191** [comment]
> you need to import it in your app module, see https://github.com/bithost-gmbh/ngx-mat-select-search#how-to-use-it

Thank you for your reply. 
I have a mistake. 
So by the way. Is it possible to combine server side and multiple select. 

Thank you

**Comment by macjohnny** [comment]
@ngthaiduong31191 you can combine server-side search and multiple select, simply use `[multiple]="true"` as in the examples https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/master/src/app/examples/02-multiple-selection-example/multiple-selection-example.component.html#L5

what you need to do to implement server-side search, is to do something like this:
```typescript
// listen for search field value changes
    this.bankServerSideFilteringCtrl.valueChanges
      .pipe(
        filter(search => !!search),
        tap(() => this.searching = true),
        takeUntil(this._onDestroy),
        debounceTime(200),
        switchMap(search => this.myApiService.getFilteredBanks(search))
      )
      .subscribe(filteredBanks => {
        this.searching = false;
        this.filteredServerSideBanks.next(filteredBanks);
      })
```
