### ISSUE TITLE
[BUG] Restoring of old selection does not use `compareWith`

### ISSUE THREAD

**Issue by Springrbua** [bithost-gmbh/ngx-mat-select-search#215]
**Describe the bug**
In [mat-select-search.component.ts#L552](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L552), the previously selected values are restored, if they have been removed by the new filter.
However, the used logic does not use the `compareWith`-function of the `mat-select` and so different instances of the same object cause problems.
In my case, if I search for a value I make a request to the server, resulting in new instances of the objects. If I deselect an already selected object, it won't be removed. Additionally, selected objects, which match the current search term, are added again, resulting in two instances being part of the value.

**To Reproduce**
Here is a [stackblitz based on ngx-mat-select-search-example](https://github-pjetju.stackblitz.io)

1. Open the select and select the first 2 banks (`Bank A (Switzerland)` and `Bank B (Switzerland)` ).
2. Search for `Switzerland`
3. Deselect `Bank A (Switzerland)`
4. In the `Selected Banks` `Bank A (Switzerland)` is still selected, `Bank B (Switzerland)` is selected twice.

**Expected behavior**
The `mat-select-search` should use the provided `compareWith`-Function to check if two objects are the same.

**Additional Information**
It should be enough to change [mat-select-search#L553](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L553) from
```typescript
if (values.indexOf(previousValue) === -1 && optionValues.indexOf(previousValue) === -1)
```
to

```typescript
if (values.findIndex(v => this.matSelect.compareWith(v, previousValue)) === -1 && optionValues.findIndex(v => this.matSelect.compareWith(v, previousValue)) === -1)
```

**Comment by macjohnny** [comment]
thanks for reporting and the detailed analysis!

**Comment by macjohnny** [comment]
@Springrbua thanks for your fix. it was released with version 2.1.2

**Comment by saithis** [comment]
@Springrbua Thanks a lot! We had the same problem yesterday and I wanted to report it now, just to see that you already fixed it :) You are awesome.

**Comment by Springrbua** [comment]
@macjohnny than you for the quick response and the new release :)
@saithis I am glad that I could contribute to this project :)
