### ISSUE TITLE
Lazy Load the values in dropdown

### ISSUE THREAD

**Issue by gitalvininfo** [bithost-gmbh/ngx-mat-select-search#218]
**Is your feature request related to a problem? Please describe.**
I want to lazy load the values in dropdown because currently it loads all the data(*1000 records of data). My current setup is that, the dropdown is inside a modal, if I open the modal, the dropdown freezes for a bit of seconds (*cannot click) then displays all records (1000 records). For me it's a big deal because my user thinks this is a bug in my app.

**Describe the solution you'd like**
What I want to achieve is that, if ever I open the modal, the dropdown will not freeze for a bit of seconds or maybe and a placeholder inside the dropdown showing like "DATA IS LOADING"

By the way this is a great library!

Please tell me if this is possible, and if I'm missing something. Thanks Developers

**Comment by macjohnny** [comment]
I suggest to use infinity scrolling.
does this solution provided by @L-NiNo work for you? 
https://github.com/bithost-gmbh/ngx-mat-select-search/issues/205#issuecomment-582976826

keep in mind that there is an open issue: https://github.com/bithost-gmbh/ngx-mat-select-search/issues/200

**Comment by gitalvininfo** [comment]
Thanks @macjohnny will give it a try.

**Comment by macjohnny** [comment]
should be possible with https://github.com/bithost-gmbh/ngx-mat-select-search/pull/236
