### ISSUE TITLE
Default selection is not working. Using ID [value]="bank.id"

### ISSUE THREAD

**Issue by smartHasmukh** [bithost-gmbh/ngx-mat-select-search#220]
I have created an example for [stackblitz](https://stackblitz.com/edit/github-hipfbd-tygsep?file=src%2Fapp%2Fapp.component.html). Please check it.

Using `bank.id`  the value does not default select

`this.bankCtrl.setValue(this.banks[10].id)` This also not working

**Comment by macjohnny** [comment]
the bank control value will be the `id` of your object, so in your case
```
Selected Bank: {{bankCtrl.value}}
```
see https://stackblitz.com/edit/github-hipfbd-wcdchx?file=src/app/examples/01-single-selection-example/single-selection-example.component.html

**Comment by smartHasmukh** [comment]
@macjohnny but default selected value is wrong in mat-select. The default value is `Bank kolombia` and now selected first value. That's the my question.

I set ` this.bankCtrl.setValue(this.banks[10].id);` this value.

``

**Comment by macjohnny** [comment]
You also need to adapt the
‚this.singleSelect.compareWith = (a,b)=>a===b‘

See the updated example: https://stackblitz.com/edit/github-hipfbd-cpklq9?file=src/app/examples/01-single-selection-example/single-selection-example.component.ts
