### ISSUE TITLE
Server-side search and selected values

### ISSUE THREAD

**Issue by rick2ricks** [bithost-gmbh/ngx-mat-select-search#222]
It would be nice if we could use select multiple options with server side search. 

Right now when the list of options changes  the values that are not in it doesn't appear listed in the 
input.

That happens as well if I have any previous selected value before searching.

This is what I expect to see:
![image](https://user-images.githubusercontent.com/4560170/77004625-2487f480-693e-11ea-8a25-cb69c4447cd5.png)

This is what happens if I filter the options with no selected value:
![image](https://user-images.githubusercontent.com/4560170/77004739-6153eb80-693e-11ea-82ee-3e11cb787628.png)

**Comment by macjohnny** [comment]
This is due to the behavior of mat-select itself and can easily be resolved by making sure that the selected options are permanently rendered as mat-option elements

**Comment by rick2ricks** [comment]
I see, it just took me a while to notice it was happening.

Thanks.

**Comment by macjohnny** [comment]
@rick2ricks can I close this issue as the question is answered?

**Comment by guliano** [comment]
You can do it by
```ts
filteredServerSideBanks.next([modelValue])
```
This will populate options with an array of one element from your model
