### ISSUE TITLE
Search Showing Undefined

### ISSUE THREAD

**Issue by abhisheksharma662** [bithost-gmbh/ngx-mat-select-search#223]
<mat-select name="dealer" placeholder="Select" [(ngModel)]="filter.dealer_id">
               <ngx-mat-select-search  [(ngModel)]="searchCtrl" [placeholderLabel]="'Search...'"
                 [noEntriesFoundLabel]="'Not found'" name="search"></ngx-mat-select-search>
               <mat-option *ngFor="let item of dealerlisting_filter |stringFilterBy:searchCtrl:'item_text'" [value]="item.item_id">{{item.item_text}}</mat-option>
             </mat-select>

Above is my code all things are working fine but first time when i click and open the dropdown inside the search text is showing undefined first time 
can anyone please help me with the solution

**Comment by macjohnny** [comment]
Can you please post more details about the error message including a stack trace?

**Comment by macjohnny** [comment]
I guess you need to initialize 

searchCtrl = „“

**Comment by abhisheksharma662** [comment]
https://stackblitz.com/edit/angular-nzwzka?embed=1&file=src/app/app.component.html


i have created a demo here with same problem can you please check it sir 
thanks in advance

**Comment by abhisheksharma662** [comment]
please can anyone solve this problem because project is stuck due to this issue
