### ISSUE TITLE
Angular-material 5: Can't bind to 'disableOptionCentering

### ISSUE THREAD

**Issue by abhisheksharma662** [bithost-gmbh/ngx-mat-select-search#224]
"@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",

i am using this application on angular 5 version and upgrading angular is not possible for me because its running with universal version 

can anyone help me with possible solution 
because only upgrading material is not resolving the problem

**Comment by macjohnny** [comment]
the `disableOptionCentering`
https://github.com/angular/components/blob/master/src/material/select/select.ts#L403-L408
is an input property of the `mat-select` element.
However, it is not yet present in `5.x`, see
https://github.com/angular/components/blob/5.2.5/src/lib/select/select.ts

**Comment by abhisheksharma662** [comment]
is there any solution for the same ? 

one more thing i am using this select on template driven form and required validation is also not working

**Comment by macjohnny** [comment]
> is there any solution for the same ?

> one more thing i am using this select on template driven form and required validation is also not working

this is related to the `mat-select` element, see the docs in https://v5.material.angular.io/components/select/overview how to use it.
