### ISSUE TITLE
Angular Version 5 

### ISSUE THREAD

**Issue by abhisheksharma662** [bithost-gmbh/ngx-mat-select-search#225]
Required validations are not working i am using it with template driven form

**Comment by macjohnny** [comment]
can you please provide more context about the problem?

**Comment by abhisheksharma662** [comment]
<form (ngSubmit)= "sendrclistingdata()">
              <div class="col-sm-6">
              <div class="form-field">
                <label>RC Status*</label>
                <mat-select  name="rc_status" placeholder="Select" [(ngModel)]="rcdetailsparam.rc_status" required>
                  <ngx-mat-select-search  [(ngModel)]="select.rcst" [placeholderLabel]="'Search...'"
                    [noEntriesFoundLabel]="'Not found'" name="search"></ngx-mat-select-search>
                  <mat-option *ngFor="let item of rcstatuslist |stringFilterBy:select.rcst:'item_text'" [value]="item.item_id">{{item.item_text}}</mat-option>
                </mat-select >
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-field">
                <label>RC to be transfered by*</label>
                <mat-select  name="rc_transfered" placeholder="Select" [(ngModel)]="rcdetailsparam.rc_transfered" required>
                  <ngx-mat-select-search  [(ngModel)]="select.tr_by" [placeholderLabel]="'Search...'"
                    [noEntriesFoundLabel]="'Not found'" name="search"></ngx-mat-select-search>
                  <mat-option *ngFor="let item of rcstatustranferlist |stringFilterBy:select.tr_by:'item_text'" [value]="item.item_id">{{item.item_text}}</mat-option>
                </mat-select >


              </div>
            </div>
            <div *ngIf="rcdetailsparam.rc_status != '1'">
              <div class="col-sm-6" *ngIf='rcdetailsparam.rc_transfered == "2"'>
                <div class="form-field">
                  <label>RTO Works</label>
                  <mat-select multiple name="rto_works" placeholder="Select" [(ngModel)]="RTOworkspreselected" required (change)="rtoworks($event)" >
                    <ngx-mat-select-search  [(ngModel)]="select.works" [placeholderLabel]="'Search...'"
                      [noEntriesFoundLabel]="'Not found'" name="search"></ngx-mat-select-search>
                    <mat-option *ngFor="let item of rto_worksdata |stringFilterBy:select.works:'item_text'" [value]="item.item_id">{{item.item_text}}</mat-option>
                  </mat-select >



                </div>
              </div>
              <div class="col-sm-6"  *ngIf='rcdetailsparam.rc_transfered == "2"'>
                <div class="form-field">
                  <label>Assign To*</label>
                  <mat-select  name="assign_to" placeholder="Select" [(ngModel)]="rcdetailsparam.assign_to" required>
                    <ngx-mat-select-search  [(ngModel)]="select.asto" [placeholderLabel]="'Search...'"
                      [noEntriesFoundLabel]="'Not found'" name="search"></ngx-mat-select-search>
                    <mat-option *ngFor="let item of rto_assignto |stringFilterBy:select.asto:'name'" [value]="item.id">{{item.name}}</mat-option>
                  </mat-select >



                </div>
              </div>
              <div class="col-sm-6" *ngIf='rcdetailsparam.rc_transfered == "2"'>
                <div class="form-group">
                  <label for="">Assigned On</label>
                  <mat-form-field class="yeslabel">
                    <input matInput [matDatepicker]="assign_on" name="assign_on" placeholder="Assigned On" [(ngModel)]="rcdetailsparam.assign_on">
                    <mat-datepicker-toggle matSuffix [for]="assign_on"></mat-datepicker-toggle>
                    <mat-datepicker #assign_on></mat-datepicker>
                  </mat-form-field>
                </div>
              </div>
              <div class="col-sm-6" >
                <div class="form-field">
                  <label>RTO Slip No</label>
                  <input type=text class="form-control" name="rto_slip_no" id="rto_slip_no" [(ngModel)]="rcdetailsparam.rto_slip_no" #rto_slip_no="ngModel" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="Enter RTO Slip No">
                </div>
              </div>
            </div>

            <div class="col-md-12">
              <button class="btn btn-primary" type="submit">Save &amp; Continue</button>
            </div>
          </form>




Assign To* field is blank and still button is enabled 
i checked by showing the values {{rcdetailsparam | json}}

**Comment by macjohnny** [comment]
according to https://v5.material.angular.io/components/select/api#MatSelect the required property is supported on the `mat-select` element.
However, your button does not seem to have any logic to disable when the form is invalid. 
Have a look here for further help: https://v5.angular.io/guide/form-validation
