### ISSUE TITLE
[FEATURE] Check/Uncheck select all box

### ISSUE THREAD

**Issue by arucar** [bithost-gmbh/ngx-mat-select-search#226]
Hi there,

May be it's already existing but i don't find how to do it. Is it possible to check the select all box when you manually select all the value, and uncheck it if you have unselect all possible value manually ?

**Comment by macjohnny** [comment]
see https://github.com/bithost-gmbh/ngx-mat-select-search/issues/189#issuecomment-562099808 and https://github.com/bithost-gmbh/ngx-mat-select-search/issues/219

you have to provide the `check all` checked state in your application, but this can easily be done by setting the corresponding input.

does this help?

**Comment by arucar** [comment]
yes thank you that was i searching for :)
