### ISSUE TITLE
[FEATURE] Checkbox select all tooltip

### ISSUE THREAD

**Issue by arucar** [bithost-gmbh/ngx-mat-select-search#227]
Is it possible to add an @input to set text of a MatTooltip on the checkbox to select/unselect all ?

**Comment by macjohnny** [comment]
@arucar yes, feel free to open a PR

**Comment by arucar** [comment]
oh ok ^^... i'll do that, thanks

**Comment by arucar** [comment]
i'll probably look like a noob.. but.. i can't create a new branch to push the code... i get an access denied

**Comment by macjohnny** [comment]
Simply fork the repository and create a branch in your fork

**Comment by arucar** [comment]
ok.. i start to feel terrible lol...
i have clone the repo with: git clone https://github.com/bithost-gmbh/ngx-mat-select-search.git

**Comment by arucar** [comment]
oh i just receive a token.. may be i need to activate something first ? it's my first contribution ^^

**Comment by arucar** [comment]
ok wait i have find a tuto to fork the repo ^^

**Comment by macjohnny** [comment]
Simply click the „fork“ button on https://github.com/bithost-gmbh/ngx-mat-select-search

**Comment by arucar** [comment]
i think it's ok..
