### ISSUE TITLE
Angular 6 Support

### ISSUE THREAD

**Issue by Avejack** [bithost-gmbh/ngx-mat-select-search#23]
Hey!
What do you think about adding Angular 6 Support?
I am not sure but i think it would not be possible to support older versions then... Maybe a ng6 branch? The Problem is that Angular 6 is using the RxJS v6 and there imports have changed. Also "takeUntil" now needs to be piped and stuff. I can make a PR for that but i don't know how you feel about the fact that this may lead to a breaking change in a way where it won't support older Angular versions anymore...

**Comment by macjohnny** [comment]
I think this is a great idea, and I would appreciate it if you could help me with that.
We are already using piped rxjs operators, as e.g. in 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L18

so this shouldn't be an issue, don't you think so?
did you try using the existing version 1.0.5 with angular 6?

**Comment by Avejack** [comment]
Strange... You are right! It should work. But when i try to start my app i get this output:

`ERROR in ./node_modules/ngx-mat-select-search/esm5/ngx-mat-select-search.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\g-uni\Documents\Projekte\digital-fb-manager\node_modules\ngx-mat-select-search\esm5'
ERROR in ./node_modules/ngx-mat-select-search/esm5/ngx-mat-select-search.js
Module not found: Error: Can't resolve 'rxjs/operators/take' in 'C:\Users\g-uni\Documents\Projekte\digital-fb-manager\node_modules\ngx-mat-select-search\esm5'
ERROR in ./node_modules/ngx-mat-select-search/esm5/ngx-mat-select-search.js
Module not found: Error: Can't resolve 'rxjs/operators/takeUntil' in 'C:\Users\g-uni\Documents\Projekte\digital-fb-manager\node_modules\ngx-mat-select-search\esm5'`

**Comment by Avejack** [comment]
i guess this is the problem (after npm i ngx-mat-select-search):

`npm WARN ngx-mat-select-search@1.0.5 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.`

**Comment by macjohnny** [comment]
we could specify the dependency as follows:
```
"rxjs": "^5.5.2 || ^6.0.0"
```
but in your case, there should already be a rxjs version in the `node_modules` folder. could you please check that this is the case?

**Comment by Avejack** [comment]
Yeah i already have the `rxjs 6.1.0` in my `node_modules` folder. Its kind of strange. For some reason it can't be resolved in the esm5 folder...

**Comment by macjohnny** [comment]
in https://stackblitz.com/github/Avejack/ngx-mat-select-search it seems to work with angular 6...
maybe it is related to packaging...

**Comment by macjohnny** [comment]
@Avejack I can reproduce your errors with a new angular project with the following versions:
Angular CLI: 6.0.0
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0

```
Module not found: Error: Can't resolve 'rxjs/Subject'
```

**Comment by Avejack** [comment]
yeah... totally strange.

**Comment by Avejack** [comment]
There is another problem:
in RxJS 6 `import { Subject } from 'rxjs/Subject';` is not valid.
you have to do: `import { Subject } from 'rxjs';`

**Comment by macjohnny** [comment]
@Avejack the imports could finally be changed to be compatible with Angular 5.x.x and 6.x.x by changing
```
import { Subject } from 'rxjs/Subject';	
import { take } from 'rxjs/operators/take';	
import { takeUntil } from 'rxjs/operators/takeUntil';
```
to
```
import { Subject } from 'rxjs';
import { take, takeUntil } from 'rxjs/operators';
```
