### ISSUE TITLE
[FEATURE] On press ESC only empty search field

### ISSUE THREAD

**Issue by nischi** [bithost-gmbh/ngx-mat-select-search#231]
It would be very nice to empty the search input with pressing "ESC". But it will close the Dropdown (also happen in your example). Maybe add an option to do this?

Please add an input which handle this feature. Ex. [emptySearchOnEsc]="false".

It could also be that the current behavior is a bug, but maybe some like it to close on ESC some like it to clear out the search box. 
Alternative could be to clear out the input on ESC and if the input is empty and you click ESC it will close. So you have both.

I tried to stopPropagation of the event, but it seems that this component add an event handler on body, but didn't find anything in code.

**Comment by macjohnny** [comment]
hi @nischi 

would you like to file a PR that implements this feature?
currently, keyboard events are handled here:

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/bfcff8cf954ba3a17c9780e37fdd3b49b504b216/src/app/mat-select-search/mat-select-search.component.ts#L373-L388

**Comment by nischi** [comment]
Will have a look into it.

**Comment by ThanosAlmighty** [comment]
Since the search input is tied to a control, it seems easier to just implement yourself @nischi. Why not create your own listener that's active when you focus the search or even the full dropdown control?

**Comment by nischi** [comment]
I tried this, but i can't stop the other listener on the Input, My listener will run after the other and so i can't stop bubbling.

**Comment by ThanosAlmighty** [comment]
Oh, I understand. This may not be a problem with this module, rather with the native html dropdown interface.

**Comment by nischi** [comment]
You got have a pull request :)
