### ISSUE TITLE
[BUG] Build Optimizer - TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by ThanosAlmighty** [bithost-gmbh/ngx-mat-select-search#233]
**Describe the bug**
Production builds with "buildOptimizer": true results in a failed build. Below is a screenshot of the full error

**To Reproduce**
1. Set buildOptimizer to true in angular.json
2. Go to command line and run production build with the following `ng build --prod`
2. Wait for build to fail.
3. See error in screenshots

**Expected behavior**

Build should not fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/32068435/83455108-4f58f380-a42b-11ea-820f-890792b71330.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: N/A

**Comment by macjohnny** [comment]
Which versions of angular / cli / mag-mat-select-search are you using? Please print the output of „ng version“
See https://github.com/bithost-gmbh/ngx-mat-select-search/issues/178

**Comment by ThanosAlmighty** [comment]
![image](https://user-images.githubusercontent.com/32068435/84080278-f00a5e80-a9a9-11ea-9f94-6eed9573a30d.png)

and the mat-select-search version is 2.20

**Comment by macjohnny** [comment]
can you please update to the latest @angular/cli, @angular-devkit/build-angular and @angular/core and see if the problem still persists?

**Comment by ThanosAlmighty** [comment]
I have already tried this. Unfortunately, due to the complexity of the application, and a few of the dependencies, I cannot upgrade to Angular 9 at this time.

**Comment by macjohnny** [comment]
this should be fixed with version `ngx-mat-select-search@3.0.0`
Please let me know whether this works.

**Comment by ThanosAlmighty** [comment]
This fixes the main issue, however I am now getting the an error saying ngx-mat-select-search must be contained in a mat-option element. I tried doing this, but the result is a search that obstructs the first option:

![image](https://user-images.githubusercontent.com/32068435/84826394-e491e580-aff0-11ea-8536-e9e1d0914134.png)

In 2.2.0, no error was thrown for the search not being contained in a mat-option element. Can you please allow that for future versions as well?

**Comment by macjohnny** [comment]
@ThanosAlmighty unfortunately, due to changes of the public API in mat-select, it is difficult to allow using ngx-mat-select-search without wrapping it into a mat-option.
However, could you open a new issue with an example how it obstructs the first element?
The examples in this repo work fine.

**Comment by macjohnny** [comment]
see also the discussion in https://github.com/bithost-gmbh/ngx-mat-select-search/pull/209
