### ISSUE TITLE
Change the German words to English

### ISSUE THREAD

**Issue by pp003** [bithost-gmbh/ngx-mat-select-search#242]
Can I change the language to English for : 
1. Label of the search placeholder : Suche,
2. Input() noEntriesFoundLabel = 'Keine Optionen gefunden';

**Comment by macjohnny** [comment]
you can change the labels as follows:
https://github.com/bithost-gmbh/ngx-mat-select-search#labels

**Comment by pp003** [comment]
> 
> 
> you can change the labels as follows:
> https://github.com/bithost-gmbh/ngx-mat-select-search#labels

Thanks for the help.
I tried but couldn't find where to do the changes. I think it's in the node-modules folder. Is it possible to change there ? 
I only need to change those two. **Suche** to **Search** . And, **Keine Optionen gefunden** to **No options found**.

**Comment by macjohnny** [comment]
You can pass the labels as an input to the ngx-mat-seleact-search element:

<ngx-mat-select-search [formControl]="bankFilterCtrl" 
                       placeholderLabel="Find bank..." 
                       noEntriesFoundLabel="'no matching bank found'"></ngx-mat-select-search>

**Comment by pp003** [comment]
It worked. Thanks for your help and valuable time.

**Comment by melroy89** [comment]
Thanks.. but still can it be by default English.. ? I think that make sense right?
