### ISSUE TITLE
[BUG] Not found message appears when all elements fits the search criteria

### ISSUE THREAD

**Issue by PabloPerezAguilo** [bithost-gmbh/ngx-mat-select-search#245]
**Describe the bug**
When every item fits the search criteria, the "not found" message appears

**To Reproduce**

1. Go to https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
2. Click on first select
3. Put "bank" in the search field
4. See the "not found" message before the search field

![image](https://user-images.githubusercontent.com/9373112/89134893-220eeb80-d529-11ea-8972-b05c49989ba6.png)

**Additional context**
I think it is a bug because if you add " a" in the search text (just show 1 element and its right) and later remove the " a" you can see all elements without the message

![image](https://user-images.githubusercontent.com/9373112/89134938-a19cba80-d529-11ea-9143-2e8114e5997b.png)

![image](https://user-images.githubusercontent.com/9373112/89134942-ac574f80-d529-11ea-8270-a4895ffad4fd.png)

**Comment by macjohnny** [comment]
@PabloPerezAguilo thanks for reporting this issue. a fixed version 3.0.2 will be released later today
