### ISSUE TITLE
[BUG] input width not updated correctly

### ISSUE THREAD

**Issue by saithis** [bithost-gmbh/ngx-mat-select-search#246]
**Describe the bug**

In some constellations when the width of the search results shrinks the input width isn't updated. Basically the same as in #175 

**To Reproduce**

1. checkout [https://github.com/prosoft-edv/components/tree/ngx-mat-select-search-bug](https://github.com/prosoft-edv/components/tree/ngx-mat-select-search-bug)
2. run 'npm install'
3. run 'npm start'
4. open http://localhost:4500/select
5. click in the select input with the label "FormControl"
6. Type in "0"

**Expected behavior**
width is updated

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1547453/89180833-de50cc00-d592-11ea-8f15-04636eab2745.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chome 83 and Firefox 79

**Possible solution**

In the dev tools if I add the following styles:
```
ngx-mat-select-search {
    display: block;
    position: relative;
}

.mat-select-search-inner {
    left: 0;
    right: 0;
}
```
and remove the calculated with, then this problem dissapears. But I don't know if this causes some other problems.

**Comment by macjohnny** [comment]
@saithis thanks for reporting this issue and providing a reproduction example.

After analyzing your repository, I found the following issue:

The option change notificatation

https://github.com/prosoft-edv/components/blob/7c8157dd2ecde557a4cd0b7170a63ac2b32be82b/projects/components/select/src/select-data.component.ts#L183

apparently happens before the UI is updated, thus

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/bc2e419a33e4a3120c5f14b3e90cbe9be72385f8/src/app/mat-select-search/mat-select-search.component.ts#L329-L333

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/bc2e419a33e4a3120c5f14b3e90cbe9be72385f8/src/app/mat-select-search/mat-select-search.component.ts#L360-L363

runs too early, so the width is updated before the width of the option panel actually changes.

The problem with your proposed solution
```css
ngx-mat-select-search {
    display: block;
    position: relative;
}

.mat-select-search-inner {
    left: 0;
    right: 0;
}
```

is that the search input field would not remain visible on top of the options when scrolling.

It would be great if you could come up with an alternative solution, as the 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/bc2e419a33e4a3120c5f14b3e90cbe9be72385f8/src/app/mat-select-search/mat-select-search.component.ts#L613
can be considered an ugly workaround.

**Comment by saithis** [comment]
@macjohnny Thanks for the quick response.

I now tried to come with css only a solution that doesn't have the problem with the search input visibillity, but I couldn't find one. Either the search input isn't visible or it hides the scrollbar :(

I then further investigated why the options aren't updated in the ui when the change event is forwarded. The problem is, that changing the search text doen't add/remove MatOptions in out case. It only changes a css class that sets the options that don't match to `display: none;`. If I change this to `*ngIf`, then the width is updated correctly. (I can't remember, why we use `display: none;` instead of `*ngIf`)

Is `updateInputWidth` considered public api? If yes, then I think I can fix it on our side by calling `updateInputWidth()` after updating the visibillity of the options.

**Comment by macjohnny** [comment]
@saithis updateInputWidth() can be considered public api as long as there is no css-only way of doing that.
And if it is ever removed, you can simply remove that one function call in your code, so I think for the time being it would be ok to use it in your code.
So do you think we can close this issue, as there is not much we can do about it in ngx-mat-select-search?

**Comment by saithis** [comment]
Yes, I'll close it.
