### ISSUE TITLE
virtual scroll example 8 issue

### ISSUE THREAD

**Issue by NitinMagdum** [bithost-gmbh/ngx-mat-select-search#253]
i am using this plugin for infinite scroll and search functionality but facing one issue 

https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?spm=a2c6h.14275010.0.0.4843743e0qwXH3&file=src%2Fapp%2Fapp.component.html

how to reproduce the issue
1 - click select box scroll for some time select a value remove focus from select by clicking outside the box
2 - then again click on select box dont do anything click outside the existing selected value is not getting attached to the box

verify the behavior with single selection example 1, here its working correctly after above step 2 the selected value in step 1 will be remain selected in the box

**Comment by macjohnny** [comment]
you can prevent resetting the options to the initial list by
```
filter(([isOpen,]) => isOpen === true && !this.ctrl.value),
```

https://stackblitz.com/edit/github-d1yhjs?file=src/app/examples/08-infinite-scroll-example/infinite-scroll-example.component.ts

I will update the example

**Comment by macjohnny** [comment]
@NitinMagdum Thanks for reporting this issue

**Comment by macjohnny** [comment]
unfortunately, #254 broke the search functionality, so I will fix the example
