### ISSUE TITLE
[BUG] No item highlighted if first option does not change

### ISSUE THREAD

**Issue by Ayoubane** [bithost-gmbh/ngx-mat-select-search#263]
This issue occurs "Sometimes" as shown in the picture below, where the pre-selector doesn't show on the elements of the list.
This doesn't allow us to choose an element by clicking the "Enter" button.

![image](https://user-images.githubusercontent.com/12896551/92691452-a2f4aa80-f353-11ea-9b09-86213be897eb.png)

**Comment by macjohnny** [comment]
@Ayoubane can you please add some more details? please use the template: https://raw.githubusercontent.com/bithost-gmbh/ngx-mat-select-search/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by macjohnny** [comment]
## Version affected
3.1.0
## steps to reproduce
* open https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example
* open the select in the "Single Selection" example
* type "sw"
* Observe that the first entry is not highlighted

This does not occur with version 3.0.3 (https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example/tree/3.0.3)

**Comment by macjohnny** [comment]
the fix was release with version 3.1.1
