### ISSUE TITLE
[BUG] multi selection with search does not refocus the search field after selection

### ISSUE THREAD

**Issue by bulldog98** [bithost-gmbh/ngx-mat-select-search#265]
**Describe the bug**
If you try out the multiselect example it does not refocus the search field after making the selection, this is bad for keyboard oriented use.

**To Reproduce**
1. Go to https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html
2. Go to the example with multiselect
3. Type something in the search
4. Select one item with an enter keypress
5. Try to get back to the search bar --> not possible except using escape and an enter to reopen the search

**Expected behavior**
If pressing escape or some other common key you should be able to refocus the search field to search for another item

**Comment by macjohnny** [comment]
@bulldog98 thanks for reporting this issue.
would you like to contribute a fix for this?

**Comment by bulldog98** [comment]
I'll have a look into it in the weekend.

**Comment by bulldog98** [comment]
I had a look into it and the behaviour I want for single select works with `enableClearOnEscapePressed` set to `true`, but this does not work with `multi` set to `true`.

**Comment by macjohnny** [comment]
the fix was release with version 3.1.1
thanks @bulldog98
