### ISSUE TITLE
No placeholder when appearance mode to `fill`

### ISSUE THREAD

**Issue by irowbin** [bithost-gmbh/ngx-mat-select-search#268]
**Describe the bug**

when applying `appearance="fill"` on form field, the placeholder of select is disappear.

**To Reproduce**

```html
<mat-form-field floatLabel="never"
                    appearance="fill"
    >
      <mat-select [formControl]="ctrl"
                  #singleSelect
                  placeholder="Select"
      >
        <mat-option>
          <ngx-mat-select-search [formControl]="filterCtrl"
                                 placeholderLabel="search.."
          >
            <i class="fas fa-times"
               ngxMatSelectSearchClear
            ></i>
          </ngx-mat-select-search>
        </mat-option>
        <mat-option *ngFor="let f of filteredFields | async"
                    [value]="f"
        >
          {{f.name}}
        </mat-option>
      </mat-select>
    </mat-form-field>
```

**Expected behavior**

the placeholder should be there for `fill` appearance.

**Screenshots**

**Desktop (please complete the following information):**

OS: win 10
Browser: Chrome 
version: 84

**Smartphone (please complete the following information):**

**Additional context**
Angular: 10.1.0
ngx-mat-select-search:  3.1.0

**Comment by macjohnny** [comment]
this does not seem to be related to `ngx-mat-select-search`, as it occurs without using the component, too:

https://stackblitz.com/edit/components-issue-8nftzp?file=src%2Fapp%2Fexample-component.html

please report the issue at https://github.com/angular/components/issues
