### ISSUE TITLE
[Question]:  Pressing ENTER toggles select all checkbox

### ISSUE THREAD

**Issue by jamiemac87** [bithost-gmbh/ngx-mat-select-search#274]
More of a question than anything else. 

Is it possible to toggle the select all checkbox when the user presses the 'ENTER' key whilst the search input is in focus?

**Comment by macjohnny** [comment]
the `ÈNTER` key toggles the selection of a single option in multi-selection mode.
The only behavior currently implemented in `ngx-mat-select-search` related to the `ENTER` key is the re-focusing of the search input field after pressing `ENTER`
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/3b37859e611b99f46976e48d2c58a377fb95754d/src/app/mat-select-search/mat-select-search.component.ts#L446-L449

you could handle the `keydown` event yourself like

```html
<ngx-mat-select-search [formControl]="bankMultiFilterCtrl" 
        (keydown)="handleKeyDown($event)"></ngx-mat-select-search>
```
see this example: https://stackblitz.com/edit/github-7oawwp?file=src/app/examples/02-multiple-selection-example/multiple-selection-example.component.html

does this answer your question?

**Comment by jamiemac87** [comment]
Yes this was a big help. Thank you for the prompt response.

For those who come to this later. If you want to set or patch the form control value I found that I had to call `event.stopPropagation();` in order to prevent the  form control value being updated twice
