### ISSUE TITLE
"placeholderLabel" should be "placeholder" according to the Angular Material naming conventions

### ISSUE THREAD

**Issue by KernelPanic92** [bithost-gmbh/ngx-mat-select-search#275]
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/3b37859e611b99f46976e48d2c58a377fb95754d/src/app/mat-select-search/mat-select-search.component.ts#L133

**Comment by macjohnny** [comment]
good idea. do you want to create an alias?

**Comment by KernelPanic92** [comment]
yea

**Comment by macjohnny** [comment]
closing to avoid a breaking change
