### ISSUE TITLE
default value of placeholder should be written in english

### ISSUE THREAD

**Issue by KernelPanic92** [bithost-gmbh/ngx-mat-select-search#276]
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/3b37859e611b99f46976e48d2c58a377fb95754d/src/app/mat-select-search/mat-select-search.component.ts#L133`

**Comment by macjohnny** [comment]
see https://github.com/bithost-gmbh/ngx-mat-select-search/issues/277#issuecomment-724246319
