### ISSUE TITLE
noEntriesFoundLabel default value should be written in english

### ISSUE THREAD

**Issue by KernelPanic92** [bithost-gmbh/ngx-mat-select-search#277]
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/3b37859e611b99f46976e48d2c58a377fb95754d/src/app/mat-select-search/mat-select-search.component.ts#L139

**Comment by macjohnny** [comment]
thanks for reporting.
english should have been chosen as the primary language. but in order to avoid breaking changes, I think we should close this issue
