### ISSUE TITLE
[BUG] [Angular 5] _countGroupLabelsBeforeOption' was not found in '@angular/material' 

### ISSUE THREAD

**Issue by KernelPanic92** [bithost-gmbh/ngx-mat-select-search#278]
**Describe the bug**

When I run the "ng serve" command I get an import warning 

**To Reproduce**

1. run in terminal "ng serve"
4. See warning --> WARNING in ./node_modules/ngx-mat-select-search/fesm5/ngx-mat-select-search.js
633: 29-58 "export '_countGroupLabelsBeforeOption' was not found in '@ angular / material'

**Additional context**

"@angular/core": "^5.0.0"
"@angular/material": "^5.0.0"
"ngx-mat-select-search": "1.8.0"

**Comment by KernelPanic92** [comment]
`_countGroupLabelsBeforeOption` was introduced in version 5.2.2

**Comment by macjohnny** [comment]
@KernelPanic92 thanks for reporting this. in your case, is it possible to update to material 5.2.2?

**Comment by KernelPanic92** [comment]
@macjohnny yes we are upgrading to angular 11 but it will take a while .. as soon as it is done we will use your component 😁

**Comment by macjohnny** [comment]
@KernelPanic92 maybe you could use a versin lower than `1.8.0`
