### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by tonyholt** [bithost-gmbh/ngx-mat-select-search#28]
Hello, when I try to use 1.2.0 in conjunction with ng-packagr and AOT, I get this error:

Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null

It's pointing to code within the angular compiler.  Once I comment out the use of the ngx-mat-select-search everything works fine.  It's a little tricky to reproduce.  It looks like a method calld _createNgFactoryStub in the AOT compiler is the origin of the issue.  If you can get to this compiler.umd.js, there's a function in there called removeSummaryDuplicates.  This is where its blowing up.  I have corrupted my code a bit so it's tough to get you exact lines right now, but if you cannot reproduce i'll get you something more thorough.

**Comment by macjohnny** [comment]
@tonyholt could you please explain what your setup looks like?
this sounds like an issue with an older version of `ng-packagr`, which version are you using?
AOT has been tested and worked so far...

**Comment by tonyholt** [comment]
I am using the new "library" feature from Angular 6.  From looking at the package.json, It's using ng-packagr 3.0.0 rc2.  There is another node package I see called "@angular-devkit/build-ng-packagr", but it too is using ng-packagr 3.0.0 rc2.  I do notice that this @angular-devkit is a few minor versions old, I may update that for giggles.  I will get together a good explanation of my particular use case shortly, to see if that helps at all.

**Comment by macjohnny** [comment]
@tonyholt could you try updating to `ng-packagr@3.0.0-rc.5`? 
maybe this could also be resolved by building `ngx-mat-select-search` with `ng-packagr@3.0.0-rc.2`, too. would you like to try that?

**Comment by tonyholt** [comment]
@macjohnny I did try ```ng-packager@3.0.0-rc.5```, but that did not work.  However, upon trying to reproduce this issue in the context of clean, isolated angular projects, I was unable to.  I still need to do some investigation.  I will comment again if I'm able to reproduce in an isolated fashion.  Thank you for your time.

**Comment by tonyholt** [comment]
I've realized that my issue is with regard to ng-packagr and how to handle local packages that have depdendencies.  If I make everything a "peerDependency" then everything seems to work.  My goal was to make certain dependencies "bundledDependencies" or just regular "dependencies" but that functionality may only work when dealing with npm pack.  I'll probably ask a question on the ng-packagr repo.  Thanks again

**Comment by macjohnny** [comment]
glad to hear you found a working solution ;-)
