### ISSUE TITLE
Use filter value as search value if it doesn't match with any of the option filteres

### ISSUE THREAD

**Issue by manuchadha1979** [bithost-gmbh/ngx-mat-select-search#284]
**Is your feature request related to a problem? Please describe.**
I have a large list of items. I want the list to contain only a subset of them. The user should be able to use filter control to search among these fields. However, if the value is not present, I would would like to use the value in filter control to do a search on server side. At the moment, if the value in filter doesn't match with any of the option items then the control's value stays invalid.

**Describe the solution you'd like**
A configuration parameter which would allow using filter control value as controls value and also change the other properties of the select control accordingly (eg. not show placeholder value but the filter control value when the select control loses focus)

**Describe alternatives you've considered**
As filter control is a form control element, I am able to add validators to check that either the filter control or select element has a value. But doing so doesn't change the `placeholder` of `ngx-mat-select-search`. 

Something like this

```
createForm() {

    this.languageSelectorForm = this.fb.group({
      tags: [null],
      tagsFilterCtrl:[null]
    },{validator: this.confirmTagIsPresent});
  }

confirmTagIsPresent = (tagSearchForm: AbstractControl) => {

    console.log("confirming at least one of tag or tag filter must be present:", tagSearchForm);
    const tagsValue = tagSearchForm.get('tags');
    const filterValue = tagSearchForm.get('tagsFilterCtrl');

 if (tagsValue.value !== null || filterValue.value !== null) {
      return null ;
    } else {
      return {
        tagSelectError: {
          valid: false,
          message: 'Value of tag must be provided'
        }
      };
    }
  }
```

**Additional context**

**Comment by manuchadha1979** [comment]
The issue is marked closed but it isn't what I have in mind. `clearSearchInput` would keep the value entered in the filter but when the `ngx-mat-select` loses focus, it doesn't show the filter value in the closed select. It shows placeholder. This would cause confusion to the user whether the value they entered in filter has been used or not.

**Comment by macjohnny** [comment]
@manuchadha1979 
Please note that `mat-select` will show a placeholder if no available option is selected.

you could create an additional `mat-option` element with your desired value and mark it as selected, so the `mat-select` will show this value when it is closed.

**Comment by almeidais** [comment]
@macjohnny did you get a solution for this problem? I'm facing the same using a paginated multiple mat-select that does server side filtering.

**Comment by macjohnny** [comment]
@almeidais does https://github.com/bithost-gmbh/ngx-mat-select-search/issues/284#issuecomment-731990665 work for you?

**Comment by almeidais** [comment]
@macjohnny I ended up doing that, but I was hoping there would be a more native way of achieving it without having to present potentially dozens of selected items at first.
