### ISSUE TITLE
[BUG] Options not adjusting to the component

### ISSUE THREAD

**Issue by eRamirezM** [bithost-gmbh/ngx-mat-select-search#292]
**Describe the bug**
When component is at the bottom on a scroll page the position of the options it is wrong

**To Reproduce**
Scroll the window and place the component near the bottom, like in this case **Single selection with custom clear icon** 

<img width="396" alt="Screen Shot 2020-12-15 at 19 17 05" src="https://user-images.githubusercontent.com/42077009/102292157-3c5eca00-3f0a-11eb-8085-64a139f3d021.png">

When i click to open the options, it shows correctly 

<img width="395" alt="Screen Shot 2020-12-15 at 19 18 52" src="https://user-images.githubusercontent.com/42077009/102292269-6fa15900-3f0a-11eb-89d0-a0c6b4f977bd.png">

But if I filter and got only one result the component keeps showing itself at the original position, and looks too high

<img width="395" alt="Screen Shot 2020-12-15 at 19 20 32" src="https://user-images.githubusercontent.com/42077009/102292363-9eb7ca80-3f0a-11eb-8e2d-14ccbe91132e.png">

**Expected Result**
The component should adjust to the mat-select

**Additional context**
Here is my stackblitz
https://stackblitz.com/edit/test-mat-select-search?file=src/app/app.component.html

**Comment by macjohnny** [comment]
@eRamirezM would you like to find a fix for this?
the panel is positioned after opening the select, see
https://github.com/angular/components/blob/3c37e4b1c1cb74a3d0a90d173240fc730d21d9d4/src/material/select/select.ts#L1214-L1222

however this is a private api
https://github.com/angular/components/blob/3c37e4b1c1cb74a3d0a90d173240fc730d21d9d4/src/material/select/select.ts#L1432-L1433
so I guess it will be difficult to solve this in ngx-mat-select-search, what do you think?

**Comment by macjohnny** [comment]
closing due to lack of public api for panel positioning. also, it would be difficult to get a proper UX that avoids jumping around too much.
