### ISSUE TITLE
Add second line as informative

### ISSUE THREAD

**Issue by exptjs** [bithost-gmbh/ngx-mat-select-search#293]
Please add the ability to display the second line as informative (not for selection).
```
let Bank = [
  {
    name: 'Bank A', id: 'A',
    branch: [
      {
        name: 'France', id: '1'
      }
    ]
  },
  {
    name: 'Bank B', id: 'B',
    branch: [
      {
        name: 'Italy', id: '1'
      }
    ]
  }
];
```
![add_second_line](https://user-images.githubusercontent.com/72014361/102473209-a3968e80-4070-11eb-9be7-e6f10d0952fe.png)

**Comment by macjohnny** [comment]
if I correctly understand your request, this would be a feature to be implemented in the angular material library.
https://github.com/angular/components

**Comment by bulldog98** [comment]
You might be able to do this with mat-select-trigger and lots of css to style the selection
