### ISSUE TITLE
[BUG]<ngx-mat-select-search>  is working in multi select but console is showing error

### ISSUE THREAD

**Issue by AhmadChishti** [bithost-gmbh/ngx-mat-select-search#294]
![image](https://user-images.githubusercontent.com/76586527/103133555-f4d7fb00-46cc-11eb-9d44-c8f6412c1aa6.png)

**Comment by macjohnny** [comment]
the error occurs as intended:
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/CHANGELOG.md#300

simply place the `<ngx-mat-select-search>` element inside a `<mat-option>`

**Comment by AhmadChishti** [comment]
placing inside a <mat-option> single select works as well, but multi select does not work correctly.
The problem which I noted is that **noEntriesFoundLabel** not working.
If the problem has been fixed, than tell me how should I use it. I am using 3.2.0 version of ngx-mat-select.

**Comment by AhmadChishti** [comment]
placing inside a **mat-option** single select works as well, but multi select does not work correctly.
 The problem which I noted is that **noEntriesFoundLabel** not working.
 If the problem has been fixed, than tell me how should I use it. I am using 3.2.0 version of ngx-mat-select.

**Comment by macjohnny** [comment]
please have a look at the example:
https://github.com/bithost-gmbh/ngx-mat-select-search#try-it

here is an example with customized no entries found label and multi-select:

https://stackblitz.com/edit/github-ewzn66?file=src/app/examples/02-multiple-selection-example/multiple-selection-example.component.html

<img width="1214" alt="Bildschirmfoto 2020-12-28 um 14 43 02" src="https://user-images.githubusercontent.com/5589029/103218373-15959000-491b-11eb-8589-4fa6e8ff5f95.png">

if you are still experiencing a problem, please open a new issue with a reproduction example
