### ISSUE TITLE
Improve Example: Multiple selection with Select All Checkbox - show indeterminate state

### ISSUE THREAD

**Issue by Naveen29** [bithost-gmbh/ngx-mat-select-search#296]
Hi,

Multiple selection with Select All Checkbox - after search and click select all its working fine,

when i remove the search text **Select All Checkbox** should show either with partial select or unselected because still i have not selected few items in my list.

![image](https://user-images.githubusercontent.com/29401430/104194179-f6345200-5446-11eb-9cd5-8571c9c8033f.png)

Source path : https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fexamples%2F06-multiple-selection-select-all-example%2Fmultiple-selection-select-all-example.component.html

**Comment by macjohnny** [comment]
you can use the following input to control the indeterminate state:

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/e35b16f2ff341f9a0a40bcb799121ba6df4403b4/src/app/mat-select-search/mat-select-search.component.ts#L181-L182

a contribution to improve the example would be appreciated

**Comment by achilehero** [comment]
Hi Esteban!

You suggestion with using the input works fine. However, if I unselect all the options, (thus having no selected option), the state of the checkbox would still be indeterminate, although the correct display would be `unchecked`.

![image](https://user-images.githubusercontent.com/14956052/104319447-8d51e600-54e9-11eb-97cc-63528f644fec.png)

**Comment by Naveen29** [comment]
Hi,

Check this [link](https://stackblitz.com/edit/angular-uuw7qh-ninwen?file=app%2Fcheckbox-configurable-example.ts)  this function what we need exactly.

**Comment by macjohnny** [comment]
@achilehero you need to set both of these inputs according the the current selection and the currently available options:
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/e35b16f2ff341f9a0a40bcb799121ba6df4403b4/src/app/mat-select-search/mat-select-search.component.ts#L178-L182

**Comment by achilehero** [comment]
@macjohnny , I am afraid I wasn't able to make it update correctly. If I set `toggleAllCheckboxIndeterminate = true` it doesn't matter if I set `toggleAllCheckboxChecked` to either true or false, it wouldn't clear the checkbox when no option is selected. Or maybe I didn't uderstand correctly what you said?

**Comment by macjohnny** [comment]
You need to update the value of toggleAllCheckboxIndeterminate According to the selection. The input is directly set on the checkbox, allowing to fully control the state of appearance

**Comment by achilehero** [comment]
So you mean I need to update that variable in my code, where I handle what's happening with selection, right?

**Comment by macjohnny** [comment]
Yes

**Comment by achilehero** [comment]
Here's an example where I tried to do what you suggested: https://github-vfjm6h.stackblitz.io . Even if the variable is updated, the view isn't. The only way I was able to make it work is by having a template reference to the mat-checkbox inside the ngx-select-search and setting the `checked` property on the MatCheckbox. So, please, if you have somewhere an example working with what you suggested, I'd like to take a look. Maybe I am still missing something.

**Comment by Naveen29** [comment]
> Here's an example where I tried to do what you suggested: https://github-vfjm6h.stackblitz.io . Even if the variable is updated, the view isn't. The only way I was able to make it work is by having a template reference to the mat-checkbox inside the ngx-select-search and setting the `checked` property on the MatCheckbox. So, please, if you have somewhere an example working with what you suggested, I'd like to take a look. Maybe I am still missing something.

Thanks for your effort, im not able to connect to above example url (https://github-vfjm6h.stackblitz.io/), can you plz check

**Comment by achilehero** [comment]
Yes, sorry for the wrong link. Here's the correct one: https://stackblitz.com/edit/github-vfjm6h?file=src/app/examples/06-multiple-selection-select-all-example/multiple-selection-select-all-example.component.ts

**Comment by macjohnny** [comment]
you need to update the state of the toggle all checkbox according to the current selection in your application, e.g.
```
          [toggleAllCheckboxIndeterminate]="bankMultiCtrl.value.length > 0 && bankMultiCtrl.value.length < allBanksSize"
          [toggleAllCheckboxChecked]="bankMultiCtrl.value.length === allBanksSize"
```
see this example:
https://stackblitz.com/edit/github-vfjm6h-cypg3b?file=src%2Fapp%2Fexamples%2F06-multiple-selection-select-all-example%2Fmultiple-selection-select-all-example.component.html

**Comment by achilehero** [comment]
I got the point on how to use it. Thanks for that! :) Still, I think there is a problem with the way MatCheckbox reacts to change and updates it's view when used with indetermined state. :( If you type something to restrict the matches, select all from the toggle checkbox and then unselect each selected option, you'll get the checkbox selected :(
![image](https://user-images.githubusercontent.com/14956052/104639762-76112500-56b0-11eb-8f96-94a9c065d1ac.png)
I fought with that the whole day trying to find a clean and proper solution.

**Comment by macjohnny** [comment]
@achilehero please open a new issue with detailed reproduction steps
