### ISSUE TITLE
Setting value for multiselect not working

### ISSUE THREAD

**Issue by martin11cortes** [bithost-gmbh/ngx-mat-select-search#299]
I'm currently using multiselect with a long list of options and implemented as follows:

* Request all options from server to be displayed `this.cities`
* Setting the multiselect options 
* Requesting the selected options from server `data.cities`
* Setting the selected values in the multiselect **not working somehow**

I'm unable to set the value with the data from the server, but I tried just (for testing) setting `this.cities` instead of `data.cities` and it works even though they are the same `typeof` just different values

I'm almost sure that I'm missing something but cannot find what, could someone help me please? 
Thanks

Here's my code

```
@Component({
  selector: 'app-my-form',
  templateUrl: './my-form.component.html',
  styleUrls: ['./my-form.component.css']
})

export class MyFormComponent implements OnInit {
  public form = this.fb.group({
    cities: ['', Validators.required],
    others: ['', Validators.required]
    ...
  })
  public cities: City[ ]
  public tooltipMessage = 'All / None';
  public filteredCities: ReplaySubject<City[]> = new ReplaySubject<City[]>(1);
  @ViewChild('multiSelect', { static: true }) multiSelect: MatSelect;
  protected _onDestroy = new Subject<void>()
  public multiFilterInput: FormControl = new FormControl()
  ...
  ngOnInit(): void {
    this.getFormData().subscribe(form => {
      this.cities = form['ciudades']
      this.filteredCities.next(this.cities.slice())
      this.route.paramMap.subscribe(params => {
        const id = params.get('id')
        if (id) {
          this.getData(id).subscribe((data) => {
            this.data.patchValue(data)
            this.form.controls['cities'].setValue(data.citites) // DOES NOT WORK
            this.form.controls['cities'].setValue(this.citites) // WORKS SOMEHOW
          })  
        }
      })
    })

    this.multiFilterInput.valueChanges.pipe(takeUntil(this._onDestroy)).subscribe(() => {
      this.filterMulti()
    })
  }

  ngOnDestroy() {
    this._onDestroy.next()
    this._onDestroy.complete()
  }

  toggleSelectAll(selectAllValue: boolean) {
    this.filteredCities.pipe(take(1), takeUntil(this._onDestroy)).subscribe(val => {
      if (selectAllValue) {
        this.form.controls['cities'].patchValue(val)
      } else {
        this.form.controls['cities'].patchValue([])
      }
    })
  }

  protected filterMulti() {
    if (!this.cities) {
      return
    }
    // get the search keyword
    let search = this.multiFilterInput.value
    if (!search) {
      this.filteredCities.next(this.cities.slice())
      return
    } else {
      search = search.toLowerCase()
    }
    // filter
    this.filteredCities.next(this.cities.filter(city => city.name.toLowerCase().indexOf(search) > -1))
  }
}
```

```
<form [formGroup]="form" (ngSubmit)="onSubmit()">
    ...
    <div fxLayout="row" fxLayout.xs="column" fxLayoutGap="1%">
      <mat-form-field appearance="outline">
        <mat-select formControlName="cities" required [multiple]="true" #multiSelect>
          <mat-option>
            <ngx-mat-select-search [showToggleAllCheckbox]="true" (toggleAll)="toggleSelectAll($event)"
              [formControl]="multiFilterInput" [toggleAllCheckboxTooltipMessage]="tooltipMessage" placeholderLabel="Search...">
            </ngx-mat-select-search>
          </mat-option>
          <mat-option *ngFor="let city of filteredCities | async" [value]="city">
            {{city.name}}
          </mat-option>
        </mat-select>
        <mat-label>
          <b>City</b>
        </mat-label>
      </mat-form-field>
    </div>
    ...
    <div fxLayout="row" fxLayout.xs="column" fxLayoutAlign="center center">
      <button mat-raised-button color="primary" [disabled]="!form.valid">Save</button>
    </div>
  </form>
```

**Comment by macjohnny** [comment]
in order to select objects as the value of the `mat-option`, you should use a `compareWith` function to compare objects by e.g. an id and not by reference.
see 
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/38a93b3c5911367bf7d002849cfac69be948b638/src/app/examples/02-multiple-selection-example/multiple-selection-example.component.ts#L67-L73

https://material.angular.io/components/select/api#MatSelect

does this resolve your problem?

**Comment by martin11cortes** [comment]
Thanks for your reply @macjohnny 

But what I don't understand is why the line 
`this.form.controls['cities'].setValue(this.citites)`
or even
`this.form.controls['cities'].setValue([this.citites[0], this.citites[100], this.citites[25], this.citites[45]])` for example
works without using the `compareWith` and the `setInitialValue` function, but the line
`this.form.controls['cities'].setValue(data.citites)`
does not work? even though they're the same thing

And I don't know how to use the `ngAfterViewInit` given that I'm using a http request to fetch the data which is going to set the values selected and those are executed in different times.

**Comment by macjohnny** [comment]
as far as I can guess, the difference between
```
this.form.controls['cities'].setValue(this.citites)
```
and
```
this.form.controls['cities'].setValue(data.citites)
```
is that although the content of `data.citites` and `this.citites` is the same, every time you load `data` from your backend, it will create a new object in the frontend, such that `data.citites !== this.citites` since the object references are not the same.

in your code, simply ensure the `compareWith` property is assigned after each `this.form.controls['cities'].setValue()` invocation.

I am closing this as this is not related to ngx-mat-select-search

**Comment by martin11cortes** [comment]
> in your code, simply ensure the compareWith property is assigned after each this.form.controls['cities'].setValue() invocation.

That was what I was looking for, that solved my problem. Thank you so much
