### ISSUE TITLE
[help wanted] Expression changed after it has been checked.

### ISSUE THREAD

**Issue by VanonckelenDieter** [bithost-gmbh/ngx-mat-select-search#301]
Hello,

I am using your component in a project and I got a recent bug report of an ExpressionChangedAfterItHasBeenCheckedError.

Normally or 99% of the time this is due to a programming bug of myself, but this time I can't find the cause of this error and I was hoping if I could get some extra information here to get this fixed.

This is a snapshot of the error thrown. I also want to point out that this happens only on a local build, not on the deployed one. To reproduce this error I need to enter some text and press spacebar sometimes.
![image](https://user-images.githubusercontent.com/37801224/105347535-59607a00-5be7-11eb-8719-b75e6a6f3d11.png)

**Comment by macjohnny** [comment]
Could you please create an example on stackblitz.com?
Could you please also paste your code?

**Comment by VanonckelenDieter** [comment]
@macjohnny thanks for the quick reaction.

I am not sure if I can share the code since I do not own it, I can't take that risk, I hope you understand that.

My usage is pretty similar to the implementation guide.

```
<mat-option>
      <ngx-mat-select-search
        *ngIf="searchable"
        [formControl]="filterCtrl"
        [placeholderLabel]="searchText"
        [noEntriesFoundLabel]="notFoundText"
      >
      </ngx-mat-select-search>
    </mat-option>

```
```
 ngOnInit(): void {
    // listen for search field value changes
    this.subs = this.filterCtrl.valueChanges.pipe(takeUntil(this.onDestroy)).subscribe((value: string) => {
      this.filterList(value);
    });
  }
```


When I enter a value that does not exist it crashes with the error. (ONLY LOCAL, that is the part I don't get)

**Comment by macjohnny** [comment]
you could copy the relevant parts only, transcribing it so it demonstrates the functionality, but is not an unwanted disclosure of information, removing any unrelated code, thus not infringing the copyright of the owner

**Comment by VanonckelenDieter** [comment]
@macjohnny I found the issue, its at my side. ngIf="searchable" is the problem due to being an @Input.

Thanks for the effort.

**Comment by jgragim** [comment]
I don't think this issue is solved.

The error _ExpressionChangedAfterItHasBeenCheckedError_ appears when using `*ngIf` in `<ngx-mat-select-search>` and filtering the options so no option is found.

From your demo page, you can just try this:

```
<mat-option>
    <ngx-mat-select-search *ngIf="true" [formControl]="bankFilterCtrl"></ngx-mat-select-search>
</mat-option>
```

The same error occurs if you place the `*ngIf` in the `mat-option` instead:

```
<mat-option *ngIf="true">
    <ngx-mat-select-search [formControl]="bankFilterCtrl"></ngx-mat-select-search>
</mat-option>
```

I think this should work and this issue should be open again.
Am I right?

Thank you very much for your work and support 🙌

**Comment by macjohnny** [comment]
@jgragim do you want to find a fix?

**Comment by jgragim** [comment]
> @jgragim do you want to find a fix?

I'm afraid I don't know how to fix this. When I face the error _ExpressionChangedAfterItHasBeenCheckedError_, it is always because of changes in the `*ngIf` value, and I always fix it using `setTimeout()`. But in this case the `*ngIf` value is static, there is no change. I don't understand why this is happening 😞 .

**Comment by mglennwithers** [comment]
In my case I was including my select options in a property of an input, so I had to implement ngDoCheck in order to pick up the changes. The error went away when I added a manual call to change detection at the end of my ngDoCheck.
My ngDoCheck code was:

```
ngDoCheck() {
	if(this.field.options && this.field.options != this._oldOptions){
		this._oldOptions = this.field.options;
		this.filterSelection();
		this.changeDetectorRef.detectChanges();
	}
}
```

I hope that helps.

**Comment by gustavovitor** [comment]
@macjohnny @jgragim 
The *ngIf need to be or in the select or in the mat-option with select inside like this:

`<mat-option *ngIf="searchable">
      <ngx-mat-select-search [formControl]="filter" placeholderLabel="Pesquise" noEntriesFoundLabel="Nenhum registro encontrado..."></ngx-mat-select-search>
    </mat-option>`
    
I think the search component is filtering the mat-option with the ngx-mat-select-search element.

Suggestion, when I created a simple search before using this library, I maked my search using only <div's> and positioning the elements with absolute position.

**Comment by gustavovitor** [comment]
The error is here:
![image](https://user-images.githubusercontent.com/37344068/116710461-2aa52d00-a9a8-11eb-9d14-4c9ed9bdd04b.png)

On: src/app/mat-select-search/mat-select-search.component.ts

**Comment by gustavovitor** [comment]
Well, simply change this line of code to this:
![image](https://user-images.githubusercontent.com/37344068/116711675-76a4a180-a9a9-11eb-859c-49745cc085b6.png)

The option list is here, so I can use it.

Why the check is > 1? Because the search element is one option inside the mat-select.

**Comment by macjohnny** [comment]
@gustavovitor I can't reproduce the issue. here is the code I used:
https://stackblitz.com/edit/github-2lbwu4?file=src%2Fapp%2Fexamples%2F01-single-selection-example%2Fsingle-selection-example.component.html

can you provide a link to an example that exhibits the behavior described?

**Comment by macjohnny** [comment]
for some reason I don't see this error in the console...

**Comment by gustavovitor** [comment]
Sorry, I haven't had time to see the bug yet, @macjohnny. I will try to see this weekend.

But you probably don't see the error because of the browser, I'm using Brave Web Browser.

**Comment by macjohnny** [comment]
@gustavovitor had to revert https://github.com/bithost-gmbh/ngx-mat-select-search/pull/313 due to https://github.com/bithost-gmbh/ngx-mat-select-search/pull/313#issuecomment-837165964

**Comment by ndjordjevic** [comment]
This worked for me:
`      setTimeout(() => {
        this.searchable= true;
      }, 0)`

**Comment by jemc300x** [comment]
I fixed it adding a class css with display none:

<mat-option [ngClass]="{ 'is-hidden': !showFilter }">
  <ngx-mat-select-search
    placeholderLabel="Filter"
    noEntriesFoundLabel="Not found"
    [formControl]="controlFilter"
  ></ngx-mat-select-search>
</mat-option>

Because with *ngIf always in development mode show this error:  Expression changed after it has been checked.
