### ISSUE TITLE
[BUG] Can you give option to rename this label "Suche"

### ISSUE THREAD

**Issue by dnsoumik** [bithost-gmbh/ngx-mat-select-search#307]
Just give an option to rename this label `"Suche"
![Screenshot from 2021-03-25 17-08-33](https://user-images.githubusercontent.com/30685539/112467515-26746700-8d8d-11eb-9ee2-9b74925c1a32.png)

**Comment by macjohnny** [comment]
The input „placeholderLabel“ allows to specify a custom label, see https://github.com/bithost-gmbh/ngx-mat-select-search#inputs

**Comment by dnsoumik** [comment]
Thanks for the help :)
