### ISSUE TITLE
[BUG] ng build --prod failed due to "kind" of undefined

### ISSUE THREAD

**Issue by dnsoumik** [bithost-gmbh/ngx-mat-select-search#308]
ERROR in ./node_modules/ngx-mat-select-search/fesm5/ngx-mat-select-search.js
Module build failed: TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (X:\github\xlayer\mtime\portal\service_provider\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:242:35)

"dependencies": {
        "@angular-devkit/core": "^0.6.8",
        "@angular/animations": "^6.0.6",
        "@angular/cdk": "^6.3.0",
        "@angular/common": "^6.0.6",
        "@angular/compiler": "^6.0.6",
        "@angular/core": "^6.0.3",
        "@angular/flex-layout": "^6.0.0-beta.16",
        "@angular/forms": "^6.0.3",
        "@angular/http": "^6.0.3",
        "@angular/material": "^6.3.0",
        "@angular/material-moment-adapter": "^6.4.7",
        "@angular/platform-browser": "^6.0.3",
        "@angular/platform-browser-dynamic": "^6.0.3",
        "@angular/router": "^6.0.3",
       "ngx-mat-select-search": "^3.2.0",
  }

"devDependencies": {
        "@angular-devkit/build-angular": "~0.6.6",
        "@angular/cli": "6.2.8",
        "@angular/compiler-cli": "^6.0.3",
        "@angular/language-service": "^6.0.3",
        "@types/googlemaps": "3.38.0",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslint": "^5.9.1",
        "typescript": "^2.8.2"
    }

can anyone help me on this

**Comment by macjohnny** [comment]
You should update angular devkit build tool, see https://github.com/bithost-gmbh/ngx-mat-select-search/issues/211#issuecomment-586960321
Please let me know if it is a different issue
