### ISSUE TITLE
[Feature Request] Elements lost when selecting elements using infinity-scroll

### ISSUE THREAD

**Issue by angelaki** [bithost-gmbh/ngx-mat-select-search#320]
Checking the components code I found out that you probably use the `initMultipleHandling()` method to reset selected elements that were lost due to an active filter on de- / selecting new values.

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/04253a3821f3abd0e481cc22a9aa80670459c37e/src/app/mat-select-search/mat-select-search.component.ts#L560

I've seen you're only doing this check if a filter is set (`if (this._formControl.value && this._formControl.value.length`) but is there a good reason for not always checking it? Or was it just to improve performance?

Since in lazy loading scenarios elements can even be missing with no filter set: https://stackblitz.com/edit/github-qbresz-r1ftsj?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:

1. Select `Bank 50`
2. Close Panel
3. Select `Bank 0`

You'll see that only `Bank 0` is selected. Always checking for missing deselected values (at least if panel is opened maybe?) could solve this issue.

Edit: I know this actually is a https://github.com/HaidarZ/ng-mat-select-infinite-scroll related problem, but since you currently need to handle your filtered values - can you take care of this issue, too? Would be great to have it solved 👍

**Comment by angelaki** [comment]
Hey @macjohnny, since I've seen you're going to update your lib due to MatSelect 12.0, how about respecting this bugfix with it? ;)

**Comment by macjohnny** [comment]
Thanks for the reminder, will look into this

**Comment by angelaki** [comment]
If you'll fix it, I have to thank you! It is actually pretty important to **me** 😅

**Comment by macjohnny** [comment]
@angelaki I am hesitant to enable the selected option restoration when filtering is not active, but I think we could add an input to make this configurable, would you like to implement this? could be released soon.

**Comment by angelaki** [comment]
Sure, here we go: https://github.com/bithost-gmbh/ngx-mat-select-search/pull/324
