### ISSUE TITLE
[BUG] Package breaks when updating Material to v12

### ISSUE THREAD

**Issue by Khazii** [bithost-gmbh/ngx-mat-select-search#321]
**Describe the bug**
Just finished updating my application to Angular v12 & Material v12 - it seems ngx-mat-select-search relied on some exports that no longer exist / are renamed in Material v12. Error below

**To Reproduce**
1. Update to Angular/Material v12
2. Embrace error message when serving application

**Additional context**

CLI Error:
```node_modules/ngx-mat-select-search/__ivy_ngcc__/fesm2015/ngx-mat-select-search.js:547:55-78 - Error: export 'SELECT_PANEL_MAX_HEIGHT' (imported as 'SELECT_PANEL_MAX_HEIGHT') was not found in '@angular/material/select' (possible exports: MAT_SELECT_CONFIG, MAT_SELECT_SCROLL_STRATEGY, MAT_SELECT_SCROLL_STRATEGY_PROVIDER, MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY, MAT_SELECT_TRIGGER, MatSelect, MatSelectChange, MatSelectModule, MatSelectTrigger, _MatSelectBase, matSelectAnimations)```

```./node_modules/ngx-mat-select-search/__ivy_ngcc__/fesm2015/ngx-mat-select-search.js:554:23-46 - Error: export 'SELECT_PANEL_MAX_HEIGHT' (imported as 'SELECT_PANEL_MAX_HEIGHT') was not found in '@angular/material/select' (possible exports: MAT_SELECT_CONFIG, MAT_SELECT_SCROLL_STRATEGY, MAT_SELECT_SCROLL_STRATEGY_PROVIDER, MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY, MAT_SELECT_TRIGGER, MatSelect, MatSelectChange, MatSelectModule, MatSelectTrigger, _MatSelectBase, matSelectAnimations)```

Hope this helps!

**Comment by macjohnny** [comment]
This is already addressed in https://github.com/bithost-gmbh/ngx-mat-select-search/pull/318 and will be released on 2021-05-17

**Comment by Khazii** [comment]
> This is already addressed in #318 and will be released on 2021-05-17

Cheers for fast reply, sorry - missed that post.

**Comment by macjohnny** [comment]
released in 3.2.1

**Comment by gkgeorgiev** [comment]
> released in 3.2.1

I have upgraded to 3.3.3 and I still can reproduce the problem.

**Comment by Lertis** [comment]
It happens again. With v.4.1.1 and Angular Material v.12 :(

**Comment by gkgeorgiev** [comment]
> It happens again. With v.4.1.1 and Angular Material v.12 :(

I could also confirm - v4.1.1 and Angular Material v 13.3.3 :/
