### ISSUE TITLE
[FEATURE] Clear selected value

### ISSUE THREAD

**Issue by Ajtak** [bithost-gmbh/ngx-mat-select-search#329]
I miss the cross for clear selected value in not-opened dropdown. `clearSearchInput = true` is only for clear input field, not for selected value.

**Comment by macjohnny** [comment]
Can you e.g. add a sketch how it should look like?

**Comment by Ajtak** [comment]
![Animation](https://user-images.githubusercontent.com/4963819/125728488-a7cbe415-78de-4dbd-ac3d-524cab24ec5a.gif)

**Comment by macjohnny** [comment]
I think this is out of scope for this project, as it would be a feature unrelated to searching the dropdown fields. However, feel free to implement it and publish it as a separate project.
