### ISSUE TITLE
How to set default value to particular dropdown in ngx-mat-select-search in multiple select? 

### ISSUE THREAD

**Issue by SanjanaRajasekar** [bithost-gmbh/ngx-mat-select-search#330]
I have n number of multiselect dropdown using ngx-mat-select search. I wanted to set default value to particular dropdown.Instead of setting particular value i am getting all value selected[see first image][1]. The expected output is [see second image][2]. The default value to all dropdowns have passed in selected_ids variable. If i console selected_ids, i get only the particular dropdown value other dropdowns are empty. refer image 3 [enter image description here][3]
![set_of_multiple_dropdowns](https://user-images.githubusercontent.com/67217695/126665808-a66fb89a-ccbd-4442-8194-575bfa139228.png)

![expected _ output](https://user-images.githubusercontent.com/67217695/126665721-0e17df21-2440-447d-a735-3090dd34d33e.png)
![selected_ids](https://user-images.githubusercontent.com/67217695/126665842-a3c773d7-2d52-4ed7-9ffe-93c7808e061e.png)
Below is my code:
HTML
<ng-container *ngIf="dataList && dataList.length > 0">
      <mat-form-field>

        <mat-select [formControl]="MultiselectCtrl"   [placeholder]="placeholder" [multiple]="true"  #multiSelect (selectionChange)="selectionsChange()"
        >
          <mat-option>
            <ngx-mat-select-search  
            [formControl]="searchFilterControl"
            [showToggleAllCheckbox]="true"  
            [noEntriesFoundLabel]="'No Search Results Found'" [placeholderLabel]="'Search...'" 
            [toggleAllCheckboxIndeterminate]="MultiselectCtrl.value.length > 0 && MultiselectCtrl.value.length < dataList.length"
            [toggleAllCheckboxChecked]="MultiselectCtrl.value.length === dataList.length"
            (toggleAll)="toggleSelectAll($event)"
            
          ></ngx-mat-select-search>
          </mat-option>
          <mat-option *ngFor="let dis of filteredDatas | async" [value]="dis">
            {{dis.display_name}}
          </mat-option>
        </mat-select>

      </mat-form-field> 
    </ng-container>
TS:
  @Input() displayName : string = '';
  @Input() displayValue : string = '';
  @Input() selected_ids:any[] = [];
  @Input() placeholder = '';
  @Input() disabled = false;
  @Output() selectChange = new EventEmitter();
  @Input() multiple : boolean = false;
    selectedOptions = [];
    selected = this.selectedOptions;

   public filteredDatas: ReplaySubject<any[]> = new ReplaySubject<any[]>(1);  
   @ViewChild('multiSelect', { static: true })
   multiSelect!: MatSelect;
   protected _onDestroy = new Subject<void>();
   public MultiselectCtrl: FormControl = new FormControl();
   public searchFilterControl: FormControl = new FormControl();

  @Input() set dataList(datas: any[]){
    if (datas) {
      this._bindDatas = datas;

      console.log('selected ids: ', this.selected_ids)
      this.filteredDatas.next(this.dataList.slice());
      this.setInputValue()
    }
  };
  
  get dataList(): any[] {
    return this._bindDatas;
   }

  private _bindDatas: any[];
  constructor() {}
  setInputValue() {
    this.filteredDatas.pipe(take(1), takeUntil(this._onDestroy))
    .subscribe((val) => {
    this.MultiselectCtrl.patchValue(val);
    this.onChange(val);
  });
  }
I have gone wrong somewhere in **setInputValue** function 
please someone help me to sort out the issue!!

**Comment by macjohnny** [comment]
Can you extend the snippet of your template? How do you render the multiple selects?

**Comment by SanjanaRajasekar** [comment]
import { Component, OnInit, Input, ViewChild, OnDestroy, EventEmitter, Output, Optional, Self, SimpleChanges, ChangeDetectorRef, forwardRef, AfterViewInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ControlValueAccessor, NgControl, NG_VALUE_ACCESSOR } from '@angular/forms';
import { takeUntil, take, distinctUntilChanged } from 'rxjs/operators';
import { MatSelect } from '@angular/material/select';
import { Subject, ReplaySubject } from 'rxjs';
import { FormControl } from '@angular/forms';
import _ from 'lodash';



@Component({
  selector: 'm-mat-select-autocomplete',
  templateUrl: './mat-select-autocomplete.component.html',
  styleUrls: ['./mat-select-autocomplete.component.scss'],  
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MatSelectAutocompleteComponent),
      multi: true
    }
  ],
})
export class MatSelectAutocompleteComponent implements OnInit , OnDestroy ,AfterViewInit,ControlValueAccessor{

  matAutoSelectForm : FormGroup;
  @Input() appearance : string ="standard";
  @Input() className : string  = '';
  @Input() displayName : string = '';
  @Input() displayValue : string = '';
  @Input() selected_ids:any[] = [];
  @Input() placeholder = '';
  @Input() disabled = false;
  @Output() selectChange = new EventEmitter();
  @Input() required : boolean = false;
  @Input() autoFocus: boolean = false;
  @Input() multiple : boolean = false;
  @Input() designType: 'material' | 'bootstrap' = 'material';
    selectedOptions = [];
    selected = this.selectedOptions;

   public filteredDatas: ReplaySubject<any[]> = new ReplaySubject<any[]>(1);  
   @ViewChild('multiSelect', { static: true })
   multiSelect!: MatSelect;
   protected _onDestroy = new Subject<void>();
   public MultiselectCtrl: FormControl = new FormControl();
   public searchFilterControl: FormControl = new FormControl();

  @Input() set dataList(datas: any[]){
    if (datas) {
      this._bindDatas = datas;
      console.log('selected ids: ', this.selected_ids)
      this.filteredDatas.next(this.dataList.slice());
      this.setInputValue()
    }
  };
  
  get dataList(): any[] {
    return this._bindDatas;
   
  }

  private _bindDatas: any[];
  
  constructor(
    @Optional() @Self() public ngControl: NgControl
  ) { 
    
    if (this.ngControl != null) {
      this.ngControl.valueAccessor = this;
    }
  }

  setInputValue() {
    this.filteredDatas.pipe(take(1), takeUntil(this._onDestroy))
    .subscribe((val) => {
    this.MultiselectCtrl.patchValue(val);
    this.onChange(val);
  });
  }

  ngOnInit() {
    this.MultiselectCtrl.setValue([this.dataList]);
    this.searchFilterControl.valueChanges
    .pipe(takeUntil(this._onDestroy))
    .subscribe(() => {
      this.filterSelectBoxData();
    });
  }

  ngAfterViewInit(): void {
  }


  ngOnDestroy() {
    this._onDestroy.next();
    this._onDestroy.complete();
  }

  onChange: Function = (_: any) => {};
  onTouched: Function = (_: any) => {};

  writeValue(value: any) { 
    this.MultiselectCtrl.setValue(value);
  }
  
  registerOnChange(fn: any) {
    this.onChange = fn
  }
  
  registerOnTouched(fn: any) { 
    this.onTouched = fn 
  }


  protected filterSelectBoxData() {
    if (!this.dataList) {
      return;
    }
    // get the search keyword
    let search =  this.searchFilterControl.value;
    if (!search) {
      this.filteredDatas.next(this.dataList.slice());
      return;
    } else {
      search = search.toLowerCase();
    }
    
    this.filteredDatas.next(
      this.dataList.filter(value => value.display_name.toLowerCase().indexOf(search) > -1)
    );
  }

  selectionsChange() {
    let value = this.MultiselectCtrl.value;
    this.selectChange.emit({
        value : value.map(a => a.com_lookup_id)
      });
    
  }

  toggleSelectAll(selectAllValue: boolean) {
    this.filteredDatas.pipe(take(1), takeUntil(this._onDestroy))
    .subscribe(val => {
      
        if (selectAllValue) {
          this.MultiselectCtrl.patchValue(val);
          this.selectChange.emit({
            value : val.map(a => a.com_lookup_id)
          });
         
        } else {
          this.MultiselectCtrl.patchValue([]);
          this.selectChange.emit({
            value : []
          });
        }
     });

   }
}

This is my full ts code.
  <m-mat-select-autocomplete [dataList]="searchObj.operationTypes"  [displayName]='"lookup_label"' 
                            placeholder="Type" [displayValue]='"com_lookup_id"'  
                            [selected_ids] = "advancedSearchObj.operation_type_ids" 
                            (selectChange)="advancedSearchObj.operation_type_ids=$event.value" ></m-mat-select-autocomplete>
These datas coming from server side

**Comment by macjohnny** [comment]
Please use markdown codeblocks to format your code: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
