### ISSUE TITLE
[BUG] I tried to input a text with underscore(_) for searching, but the searcher didn't fired. Same for all the text typed after typing underscore. But deleting any character invokes it. Eg input : 'test_1' will not invoke searcher. it will invoke searcher till 'test' 

### ISSUE THREAD

**Issue by myname-gokul** [bithost-gmbh/ngx-mat-select-search#333]
**Describe the bug**

**To Reproduce**

*Important* Please provide a reproduction example. You can use https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example as a starting point

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by macjohnny** [comment]
typing underscore works as expected:
https://stackblitz.com/edit/github-hscyuw?file=src%2Fapp%2Fexamples%2Fdemo-data.ts

<img width="1185" alt="Bildschirmfoto 2021-08-06 um 08 54 01" src="https://user-images.githubusercontent.com/5589029/128469099-7650c6e3-d5b4-44e1-a8b7-26bdb9fde823.png">

If you still believe this is an issue in ngx-mat-select-search, please open a new issue, fill in the issue template, and provide exact reproduction steps and preferrably a demo.
