### ISSUE TITLE
Angular 13 compatibility

### ISSUE THREAD

**Issue by ErVishalM** [bithost-gmbh/ngx-mat-select-search#340]
Hi,

I was trying to update to angular 13 but I am getting this error when I am running below command -
`npx @angular/cli@13 update @angular/material@13`
Error-
`npx @angular/cli@13 update @angular/material@13
Using package manager: 'npm'
Collecting installed dependencies...
Found 52 dependencies.
Fetching dependency metadata from registry...
                  Package "ngx-mat-select-search" has an incompatible peer dependency to "@angular/material" (requires "^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0", would install "13.0.0").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\UserName\AppData\Local\Temp\ng-8tuNbE\angular-errors.log" for further details.`
  
Screenshot also attached for your ref.
![image](https://user-images.githubusercontent.com/43669644/140513756-76bf9686-f634-492f-b646-a59d5ad3baee.png)

Can you please help me how can I update to Angular 13?

**Comment by macjohnny** [comment]
Currently, you need to use —force

i will soon update the package to officially add angular 13 compatibility

**Comment by macjohnny** [comment]
ngx-mat-select-search@3.3.2 is compatible with Angular 13
