### ISSUE TITLE
[FEATURE]  Support for Angular v13

### ISSUE THREAD

**Issue by sujeetsinha** [bithost-gmbh/ngx-mat-select-search#344]
Upgrading the application from Angular v12 to v13 which uses ngx-mat-select-search is breaking the build dependency. Can you please add support for v13?

**Comment by sujeetsinha** [comment]
![image](https://user-images.githubusercontent.com/54589960/141414217-7792013a-e598-4623-bfd7-05d47cde24a8.png)

Adding error message for more clarity

**Comment by macjohnny** [comment]
Please upgrade ngx-mat-select-search to version 3.3.2, which is officially compatible with angular 13:
https://github.com/bithost-gmbh/ngx-mat-select-search/issues/340#issuecomment-962482909

**Comment by sujeetsinha** [comment]
Thanks for the quick response. The version compatibility has not reflected on https://www.npmjs.com/package/ngx-mat-select-search/v/3.3.2 and hence the confusion.

**Comment by macjohnny** [comment]
thanks, the readme was updated in https://github.com/bithost-gmbh/ngx-mat-select-search/pull/342 and released in version 3.3.3
