### ISSUE TITLE
Component Height Issue and ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by ebenh** [bithost-gmbh/ngx-mat-select-search#346]
Hello,

I built [ngx-mat-tel-input](https://github.com/ebenh/ngx-mat-tel-input). It's an Angular Material component built on top of ngx-mat-select-search.

My component has two bugs which I think are directly related to ngx-mat-tel-input. I was hoping someone here could help figuring them out.

- [Issue one](https://github.com/ebenh/ngx-mat-tel-input/issues/8)
- [Issue two](https://github.com/ebenh/ngx-mat-tel-input/issues/9)

Thanks.

**Comment by macjohnny** [comment]
Closing as obsolete.
