### ISSUE TITLE
[BUG] ngx-mat-select-search is removing already selected options on searching

### ISSUE THREAD

**Issue by vikram-sapate** [bithost-gmbh/ngx-mat-select-search#348]
Another issue,
Assume some options are already selected & you search something, then it is clearing the selected options but I'm displaying selected items in the list (just below the select field) that remain unaffected. For chips & list I'm using the same data.

  This is a [Live example](https://ngx-mat-select-search-dy5gaa.stackblitz.io) 

   This is a [Stackblitz link](https://stackblitz.com/edit/ngx-mat-select-search-dy5gaa)

**Comment by vikram-sapate** [comment]
hey, @macjohnny & team , why not you hide option instead of filtering on search ?

**Comment by macjohnny** [comment]
Hi
The reason why the option elements are filtered instead of just hiding them is that mat-select depends on the list of available options for calculations like focused item, scrolling etc

**Comment by ilyakonrad** [comment]
This is still relevant, value of the field is hidden if the search input doesn't match it.

**Comment by macjohnny** [comment]
@ilyakonrad can you provide a stackblitz example and a description/repro of your issue?

**Comment by ilyakonrad** [comment]
@macjohnny Check your own examples:
![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/25200186/037370a5-82ec-4b2c-93bc-6cd2c85cfc1c)
![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/25200186/334dd582-b1a8-4136-856c-a30277f6cb97)

**Comment by ilyakonrad** [comment]
@macjohnny I mean that the actual value of mat-select disappears depending on the search term.

**Comment by macjohnny** [comment]
yes, this is how mat-select works when there is no option corresponding to the field value (i.e. the previously selected value). To avoid this, you can make sure that the selected option is always present, i.e. never filtered out.

**Comment by rfalken** [comment]
@macjohnny can you please elaborate on just how it can be achieved?

I'll try to explain what I mean here. I actually believe @ilyakonrad means exactly the same though. 

Now, I'm not referring to the filtered selection based on my keyword used when searching. It works just fine. What I'm referring to is the already-selected values(s) in the field. Imagine you've selected values A, B and C. Then you start looking for a D. But it's missing so the selection is empty, and that's okay. But the A, B and C disappear as soon as you type in D. However, I still want to see what has already been selected, just for reference's sake.

**Comment by macjohnny** [comment]
in your option filtering logic, you would make sure to never exclude an option if it is selected

**Comment by rfalken** [comment]
@macjohnny okay, sorry to pester you with this further but I'm still not sure we're on the same page. In your official Stackbiltz you can find the "Multiple selection with Select All Checkbox" example. Just underneath this field you can see the already-selected values. They do not disappear no matter what your keyword is. Now, I have selected these:

![Image](https://github.com/user-attachments/assets/a0b05fb4-78fc-4ea1-ba80-38a5864a749f)

Please note the field, it contains my selected values:

![Image](https://github.com/user-attachments/assets/9f0068b2-8f76-4ef0-a8f3-3b7dcef824ef)

Next I type in a value that's missing in the data source:

![Image](https://github.com/user-attachments/assets/017c65e8-6be0-456d-acd2-f384e4296e8b)

My selected values are still intact as is evident by the list below. However, within the field itself I get a placeholder "Banks":

![Image](https://github.com/user-attachments/assets/53b8f276-e5a7-465a-adae-757cda7ff2ec)

I would very much like for the previous selection to remain inside the field though. No placeholder, just the same content as before:

![Image](https://github.com/user-attachments/assets/b7053372-8572-4e2d-9d86-3ab184206729)

Can you please tell me just how I am to change the logic (in this specific case) to achieve the desired result.

**Comment by macjohnny** [comment]
the placeholder will change and can only show actually present options. during filtering, we have a special mechanism to ensure all selected options, including the temporarily removed ones are in the form field value. however, the placeholder is controlled by mat-select, and the only way tobmake sure a selected option is shown there is to make sure the option is present, even during filtering

**Comment by rfalken** [comment]
@macjohnny could you please demonstrate how to make sure the selected options are present during filtering without breaking the rest of the logic as applied to your official example I mentioned above?

**Comment by macjohnny** [comment]
i would change this line here: https://github.com/bithost-gmbh/ngx-mat-select-search/blob/d1faafa977139c59215d4a81784612efb448b68d/src/app/examples/02-multiple-selection-example/multiple-selection-example.component.ts#L91

**Comment by rfalken** [comment]
@macjohnny okay, I've done some tinkering with filtering and still have a question. When I include the previously selected options into the resultant set of options that match the search keyword during filtering, I have them all displayed both in the input field and among the options in the drop-down list. Is there any way I can manually exclude them from the drop-down list after the filtering was all done? If there's no API for that, what would you consider the best approach?

**Comment by macjohnny** [comment]
@rfalken unfortunately, i am not aware of an API in mat-select that would allow to achieve that, so we would need to suggest something there to be implemented
