### ISSUE TITLE
Question: ngx-mat-select-search placed inside mat-option

### ISSUE THREAD

**Issue by MickeWest** [bithost-gmbh/ngx-mat-select-search#361]
**Describe the bug**
First, thanks for the great work on this as it is very useful!

I get this Error with latest version of ngx-mat-select, which has worked for all the other versions.

**ngx-mat-select-search must be placed inside a mat-option element**

Below is an example how we use ngx-mat-select and it works great:

```
<mat-select
	#userDatabaseSelectionControl
	[formControl]="userDatabaseSelectionFormControl"
	[multiple]="false"
	#multiSelect
	placeholder="Database Target"
	(selectionChange)="onUserDatabaseSelectionChanged($event)"
	[(value)]="CurrentUserDatabaseSelection">
	
	<ngx-mat-select-search placeholderLabel="Search" noEntriesFoundLabel="No Entries Found" [clearSearchInput]="true" [showToggleAllCheckbox]="false" [formControl]="userDatabaseSelectionFilterCtrl"></ngx-mat-select-search>
	<mat-option *ngFor="let db of filteredUserDatabaseSelectionListMulti | async" [value]="db" class="selectionOptionValid">
		{{ db }}
	</mat-option>
</mat-select>


```
When I now check the source code of ngx-mat-select-search there is a check that triggers the above Error (see code snippet below) if the ngx-mat-select-search is NOT placed INSIDE the mat-option.
This was not needed prior (we then used Angular 8 and now Angular 13).
If we place the ngx-mat-select-search INSIDE the mat-option the list tools terrible and does not build the whole list of all the items we added.

```
// set custom mat-option class if the component was placed inside a mat-option
if (this.matOption) {
  this.matOption.disabled = true;
  this.matOption._getHostElement().classList.add('contains-mat-select-search');
} else {
  console.error('<ngx-mat-select-search> must be placed inside a <mat-option> element');
}

```
Has the usage of ngx-mat-select-search changed between its versions or when going from Angular 8 to Angular 13?
Any help would be much appreciated!

Thanks,

Michael

**To Reproduce**
Please see above code snippets. I did not add a stackblitz as one would not show any more info.

**Expected behavior**

**Screenshots**
List if ngx-mat-select-search placed INSIDE the Mat-Option

![List_When_Inside_MatOption](https://user-images.githubusercontent.com/71844639/156490584-81db3c58-309d-402e-87ac-7fc41e2e31ad.png)

List if ngx-mat-select-search  placed Outside the Mat-Option

![List_When_Outside_MatOption](https://user-images.githubusercontent.com/71844639/156490633-5e886f36-1cdd-4543-8907-4590a9b4822b.png)

**Comment by macjohnny** [comment]
Glad you like this project!

here is what your code should look like:

  <mat-select
	#userDatabaseSelectionControl
	[formControl]="userDatabaseSelectionFormControl"
	[multiple]="false"
	#multiSelect
	placeholder="Database Target"
	(selectionChange)="onUserDatabaseSelectionChanged($event)"
	[(value)]="CurrentUserDatabaseSelection">
	<mat-option>
	<ngx-mat-select-search placeholderLabel="Search" noEntriesFoundLabel="No Entries Found" [clearSearchInput]="true" [showToggleAllCheckbox]="false" [formControl]="userDatabaseSelectionFilterCtrl"></ngx-mat-select-search>
	</mat-option>
	<mat-option *ngFor="let db of filteredUserDatabaseSelectionListMulti | async" [value]="db" class="selectionOptionValid">
		{{ db }}
	</mat-option>
  </mat-select>

note the closing tag of mat-option right after the closing tag of ngx-mat-select-search

A stackblitz example usually helps me to debug the result, and see exactly how you use it.

the example

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/07542785d924af8cebcdc843a6f2089749bca81d/src/app/examples/01-single-selection-example/single-selection-example.component.html#L5-7

works properly, so I don‘t suspect a general issue

**Comment by macjohnny** [comment]
And for your information: the requirement to place ngx-mat-select-search inside mat-option was needed to avoid some bugs and simplify the layouting.

**Comment by MickeWest** [comment]
Thanks for your quick response!
I finally got time to test out your updated suggestion and it seems to work perfectly.

/Michael
