### ISSUE TITLE
[FEATURE] selet mat-group with their children

### ISSUE THREAD

**Issue by bnadem** [bithost-gmbh/ngx-mat-select-search#362]
your plugin work fine, but misses select  mat-group and their children (mat-option)
please help im my project

**Comment by macjohnny** [comment]
Can you give some more details what you want to achieve? In addition, A sketch of how it looks like would also be good.
Is this something that is reated to mat-select or ngx-mat-seect-search?

**Comment by bnadem** [comment]
here ist code 
  <mat-select [formControl]="bankGroupsCtrl" placeholder="Bank" [multiple]="true" #singleSelect>
                                <mat-option>
                                    <ngx-mat-select-search [formControl]="bankGroupsFilterCtrl"></ngx-mat-select-search>
                                </mat-option>
                                <mat-optgroup   *ngFor="let group of filteredBankGroups | async; let j=index;" >
                                    <div>
                                        <mat-checkbox [checked]="group.checked"   (change)="toggleParent($event,group)">
                                            {{group.value}}
                                        </mat-checkbox>
                                    </div>
                                    <mat-option *ngFor="let bank of group.items" [value]="bank.value">
                                        {{bank.value}}
                                    </mat-option>
                                </mat-optgroup>
                            </mat-select>
![Unbenannt](https://user-images.githubusercontent.com/18377721/160355857-a21800f5-4105-4998-b736-256af592de2c.png)

**Comment by macjohnny** [comment]
this does not seem to be implemented in mat-select, so it is out of scope for ngx-mat-select-search since it is not related to the search input functionality, but feel free to file a feature request at https://github.com/angular/components/issues
