### ISSUE TITLE
[FEATURE] rename close to clear

### ISSUE THREAD

**Issue by geyuqiu** [bithost-gmbh/ngx-mat-select-search#366]
https://user-images.githubusercontent.com/4540661/162740754-37c2f698-0a9d-4056-8012-c2560256fa9f.mov

**Comment by macjohnny** [comment]
see https://github.com/bithost-gmbh/ngx-mat-select-search/issues/165 and https://github.com/bithost-gmbh/ngx-mat-select-search/pull/364 and https://github.com/bithost-gmbh/ngx-mat-select-search#customize-clear-icon

can we close your issue?

**Comment by geyuqiu** [comment]
can you maybe add an icon only example to the example repo please ?
