### ISSUE TITLE
[BUG] using <mat-hint> element always throws ExpressionChangedAfterItHasBeenCheckedError error

### ISSUE THREAD

**Issue by Procisz** [bithost-gmbh/ngx-mat-select-search#375]
**Describe the bug**
mat-hint element throws "ExpressionChangedAfterItHasBeenCheckedError" error.

The complete error:
Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'attr.aria-describedby': 'null'. Current value: 'mat-hint-4'..

**To Reproduce**
Just simply insert a  `<mat-hint></mat-hint>` inside the mat-form-field element

**Expected behavior**
:)

**Additional context**
I couldn't solve with ChangeDetectorRef detectChanges() method. I tried with static data, but nothing changed.

Example:
`<mat-hint> Mat hint text example.</mat-hint>`

**Comment by macjohnny** [comment]
Hi
Are you sure this is related to ngx-mat-select-search?
Can you show the code you used?

**Comment by Procisz** [comment]
Okay, 
I just upgraded it to the latest version and it seem like the promlem gone.
I'll keep you updated.
Ty for your answer.

**Comment by macjohnny** [comment]
closing this for now. if this occurs again, please let me know
