### ISSUE TITLE
[FEATURE] Enable the use of a custom template for notFoundEntries

### ISSUE THREAD

**Issue by ruekart** [bithost-gmbh/ngx-mat-select-search#381]
**Is your feature request related to a problem? Please describe.**
When there are no options found for the user input then there's just the possibility to show a not found label, but sometimes you could want to add more than text, it could be an image or a button.

**Describe the solution you'd like**
I would like to use ng-content to show a custom element when there are no options as with the custom clear icon.

**Describe alternatives you've considered**
I have considered to add an EventEmitter as pointed out in #345 but I think it could be confusing for the user to know the option to press enter to add a new element or something else.

**Additional context**
Here there are some not found messages with custom content
![image](https://user-images.githubusercontent.com/9154610/173148139-e518c826-0ba1-42e0-a3eb-691658822cf5.png)

![image](https://user-images.githubusercontent.com/9154610/173148023-801461f0-55b1-48d6-8e46-fe0eb2b10e55.png)

**Comment by macjohnny** [comment]
This sounds good. We could use a directive similar to https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search-clear.directive.ts to mark the content.

Do you want to implement this?

**Comment by ruekart** [comment]
Sure, I'm working on it.

**Comment by ruekart** [comment]
I sent this PR #382

**Comment by macjohnny** [comment]
thanks for your contribution. it is released in version 4.2.0
