### ISSUE TITLE
[FEATURE] Disable browser autocomplete

### ISSUE THREAD

**Issue by gokhanyildiz** [bithost-gmbh/ngx-mat-select-search#385]
Hi,
How to disable search input browser autocomplete history? Can we define autocomplete in ngx-mat-select-search? Can you add this option in the next version?

Thanks.

**Comment by macjohnny** [comment]
The search input already has the

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/092aaf963d2b9cb3cb36f79cab1f6d3c6f35aa63/src/app/mat-select-search/mat-select-search.component.html#L22

attribute. What other attribute are you thinking of?

**Comment by gokhanyildiz** [comment]
Hello, I think I found the problem. I having a similar problem but solved this. https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off 

I added type="search" attribute to ngx-mat-select-search and problem solved. Thank you for your support.
