### ISSUE TITLE
Module not found NgxMatSelectSearchModule on jest running.

### ISSUE THREAD

**Issue by Tayyba23** [bithost-gmbh/ngx-mat-select-search#386]
my project is using jest for testing. I have successfully used this module inside my application and is running as well but for jest
it is failing with the following logs, despite adding an import statement to the required component's spec.ts file.

    Cannot find module 'ngx-mat-select-search' from 'src/app/myComp.component.spec.ts'

      17 |     NGX_MAT_DATE_FORMATS,
      18 | } from '@angular-material-components/datetime-picker';
    > 19 | import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';
         | ^
      20 |
      21 | import { ToastrModule } from 'ngx-toastr';
      22 | import { CookieService } from 'ngx-cookie-service';

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:322:11)
      at Object.<anonymous> (src/app/myComp.component.spec.ts:19:1)

I have tried adding the "module path" of node modules in jest.config.ts . I am new to angular testing.Can you help me out in it? What am  missing here.

Reference : https://timdeschryver.dev/blog/integrate-jest-into-an-angular-application-and-library#splitting-up-jest

**Comment by macjohnny** [comment]
Hi
If you remove 
  
  import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';


Does the 

  import { ToastrModule } from 'ngx-toastr';
  
Work?

which version of ngx-mat-select-search are you using?

**Comment by macjohnny** [comment]
@Tayyba23 any update here?

**Comment by andreacasarella** [comment]
Hi, I have same issue using:

`    "ngx-mat-select-search": "^4.2.1",
`

```
Test suite failed to run
Jest encountered an unexpected token
...
 ...\node_modules\ngx-mat-select-search\fesm2020\ngx-mat-select-search.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { A, Z, ZERO, NINE, SPACE, HOME, END, ENTER, ESCAPE, UP_ARROW, DOWN_ARROW } from '@angular/cdk/keycodes';
                                                                                      ^^^^^^
SyntaxError: Cannot use import statement outside a module
> 23 | import {NgxMatSelectSearchModule} from 'ngx-mat-select-search';   
```

any suggestion?

**Comment by macjohnny** [comment]
Do you have a minimal reproduction example?

**Comment by andreacasarella** [comment]
Unfortunately not, but I'm importing the module as usual and like other libraries. But when I run test it will fail during initialization on the component.

deps
```
"@angular/material": "^12.2.13",
...
"ngx-mat-select-search": "^4.2.1",
...
"jest": "^27.5.1",
```

The component use: 
```
...
 <mat-option [formGroup]="filterSubCategoryForm">
    <ngx-mat-select-search [formControlName]="fields.SUB_CATEGORY"
                           [disableScrollToActiveOnOptionsChanged]="true"
                           [placeholderLabel]="'actions.search' | translate"
                           [noEntriesFoundLabel]="'labels.noResultsFound' | translate"></ngx-mat-select-search>
  </mat-option>
...
```

Then in the test suite:
```

import {NgxMatSelectSearchModule} from 'ngx-mat-select-search';

describe('SupportRequestFormComponent', () => {
  let component: SupportRequestFormComponent;
  let fixture: ComponentFixture<SupportRequestFormComponent>;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpClientTestingModule,
        RouterTestingModule,
        BrowserAnimationsModule,
        TranslateModule.forRoot(),
        ReactiveFormsModule,
        MaterialModule,
        RecaptchaModule,
        RecaptchaFormsModule,
        NgxMatSelectSearchModule
      ],
      declarations: [
        SupportRequestFormComponent,
       ...
      ],
      providers: [
        ...
      ]
    })
      .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(SupportRequestFormComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

Result see comment above.

Thanks for your help!

**Comment by Tayyba23** [comment]
Hi,

For me, changing the version of ngx-mat-select-search worked. Version : "3.3.3"worked for me with following jest versions, 
        "@types/jest": "^27.0.2" ,
        "jest": "^27.2.1",
        "jest-html-reporters": "^2.1.6",
        "jest-preset-angular": "^10.0.0"

**Comment by macjohnny** [comment]
Hmm might be related to the update of ng-packagr that we did for version 4.0.0: https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/CHANGELOG.md#400

**Comment by macjohnny** [comment]
@Tayyba23 can you check whether this is still an issue with version 6.0.0?

**Comment by macjohnny** [comment]
closing as obsolete
