### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by basor-dali** [bithost-gmbh/ngx-mat-select-search#390]
[This package](https://www.jsdelivr.com/package/npm/ngx-mat-select-search) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by macjohnny** [comment]
@basor-dali thanks for the suggestion
Can you elaborate why this is useful for this package?
