### ISSUE TITLE
[FEATURE] Angular 15 compatibility

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/ngx-mat-select-search#395]

**Comment by AhsanAyaz** [comment]
@macjohnny could you share what compatibility considerations you have?

**Comment by macjohnny** [comment]
@AhsanAyaz I think we will release one version that is compatible with ng 15 and the legacy material select, and a subsequent release that supports the new select only

**Comment by macjohnny** [comment]
@AhsanAyaz are you interested in preparing those releases?

**Comment by AhsanAyaz** [comment]
@macjohnny . Sure. I do believe that's gonna be in November though :) end of November that is.

**Comment by JeremieLapert** [comment]
Hi, Angular 15 is out, have you planned the compatibility of the plugin ?

**Comment by macjohnny** [comment]
@JeremieLapert yes, I hope I can get to it next week, or maybe someone else can give a hand preparing the releases

**Comment by macjohnny** [comment]
[Version 6.0.0](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/6.0.0) has been released  and updates compatibility to `@angular/material@15` with `MatLegacySelectModule` (`@angular/material/legacy-select`)

**Comment by macjohnny** [comment]
compatibility with the new material mdc mat-select is tracked in a separate bug: https://github.com/bithost-gmbh/ngx-mat-select-search/issues/411
