### ISSUE TITLE
Enchanment: support svg icon for delete button

### ISSUE THREAD

**Issue by OvidijusStukas** [bithost-gmbh/ngx-mat-select-search#41]
Hello,

I'm currently using material 6 and using SVG icons. I would like a way to set svgIcon for delete button since now it's hardcoded to "close" google icon font.

Currently I workaround by globally changing '.mat-select-search-clear' to display none. Better without button than text of 'clear'

**Comment by macjohnny** [comment]
@OvidijusStukas thanks for your feature request. I think it is a good idea to make the clear icon configurable.
how about changing https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.html#L23
to
```
<mat-icon *ngIf="!hasCustomCloseIcon">close</mat-icon>
<ng-content select=".ngx-mat-select-search-custom-close-icon"></ng-content>
```
and adding a
```
@Input() hasCustomCloseIcon
```
?

Would you like to create a PR and maybe add an example?

**Comment by OvidijusStukas** [comment]
Created a pull request for feature changes. Added a custom directive which allows to completly override default icon. So end users can define mat-icon.
