### ISSUE TITLE
[FEATURE] compatibility with material mdc

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/ngx-mat-select-search#411]
[Version 6.0.0](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/6.0.0) is the only version that is compatible with angular material 15 and the MatLegacySelectModule („@angular/material/legacy-select“)

in the upcoming version 7.0.0, we want to be compatible with the mdc-based version of mat-select, ie „@angular/material/select“ of angular material 15. this will be a breaking change, as we need to drop support for the legacy mat select

**Comment by macjohnny** [comment]
@AhsanAyaz would you want to take a stab at this one?
see this WIP PR: https://github.com/bithost-gmbh/ngx-mat-select-search/pull/412

**Comment by mtinnes** [comment]
Is there any way to get v6.0 working with non-legacy (MDC) material? I've tried importing the MatLegacySelectModule but I get the following error:

`Error: NG0300: Multiple components match node with tagname mat-form-field: MatFormField and MatLegacyFormField. Find more at https://angular.io/errors/NG0300`

**Comment by macjohnny** [comment]
@mtinnes version 6.0.0 is not compatible with the mdc mat select. There will be a new release that will be compatible, but there is some work left to do, see https://github.com/bithost-gmbh/ngx-mat-select-search/pull/412

**Comment by smnbbrv** [comment]
Thanks! You saved my day with v6.0.0
