### ISSUE TITLE
Pagination in the component

### ISSUE THREAD

**Issue by guilhermecostalopes** [bithost-gmbh/ngx-mat-select-search#423]
**Please describe.**
I need this component to be paginated, because when there are a lot of records, it gets a little slow. Even more so when there are several of these components on screen. I'm talking 1000 records upwards.

**Comment by macjohnny** [comment]
@guilhermecostalopes do you want to explore a solution and implementation?

**Comment by guilhermecostalopes** [comment]
@macjohnny 
I can yes. How does this implementation work?

**Comment by angelaki** [comment]
Check [MatSelectInfiniteScroll](https://www.npmjs.com/package/ng-mat-select-infinite-scroll), they work quite well together.

**Comment by macjohnny** [comment]
the solution with [MatSelectInfiniteScroll](https://www.npmjs.com/package/ng-mat-select-infinite-scroll) seems to be appropriate
