### ISSUE TITLE
Angular 16: Search field acting weird? 

### ISSUE THREAD

**Issue by GipHub123** [bithost-gmbh/ngx-mat-select-search#425]
**Describe the bug**
ngx-mat-select-search acting weird after updating angular 16.0.0. 

Field looked like disabled / clear button didn't do anything. I rolled back to version 15 and search field started to work as expected. 

It looked like some changes has been made to the Material's select -component. 
https://github.com/angular/components/tree/main/src/material/select

Can anyone else confirm this or it's just me doing something stupid?

**Comment by macjohnny** [comment]
@GipHub123 are you using the legacy field or the mdc based ones? See https://github.com/bithost-gmbh/ngx-mat-select-search/issues/411

**Comment by GipHub123** [comment]
Sorry that original description was missing this important detail. 

I'm using newer MDC based components imported from 
`{ MatSelectModule } from '@angular/material/select';`

**Comment by ewalke31** [comment]
Same issue, also using newer MDC based one

**Comment by macjohnny** [comment]
Can you please provide more information about which package versions you use, a screenshot, an example template etc? Ideally could you create a stackblitz example?

**Comment by ewalke31** [comment]
Updating all the dependencies and removing line 27 of polyfills.ts in the stackblitz provided in the readme replicates the issue: https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example

**Comment by macjohnny** [comment]
ok, could confirm, it seems to have changed since I last tested with Material Version: 16.0.0-next.2 (where it worked fine)

**Comment by macjohnny** [comment]
fixed with version [7.0.2](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/7.0.2), thanks for reporting!
