### ISSUE TITLE
Feature Request: Handle Control keys Pos1 & End in input field

### ISSUE THREAD

**Issue by geraldhe** [bithost-gmbh/ngx-mat-select-search#43]
Hello!

the keyboard-keys "Home/Pos1" (to set the cursor to the beginning) and "End" (to set the cursor to the end) are not working in the search-box.

**Comment by macjohnny** [comment]
@geraldhe thanks for your feedback.

The reason for Home / End being ignored by `ngx-mat-select-search` is that these keys are handled by the `mat-select`, see
https://github.com/angular/material2/blob/afb0ee37ebe0342020a9fe8c804b7b43de0ca12e/src/lib/select/select.ts#L699
the Home / End keys move the selection to the first / last item of the options.

The only key that is not propagated to `mat-select` is the `space` key, see
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/fc6ee7fb58246222151c0b0ffb9f3fc314d8a621/src/app/mat-select-search/mat-select-search.component.ts#L249

@geraldhe would you be up for filing a PR with an `@Input() dontPropagateHomeEndKeys: boolean = false;` to introduce an option for your feature request?

**Comment by macjohnny** [comment]
@geraldhe are you interested in implementing this feature?

**Comment by geraldhe** [comment]
sorry, no free time for this at the moment. maybe later...

**Comment by macjohnny** [comment]
this is released in `1.7.0`
