### ISSUE TITLE
[FEATURE] Support Angular material 16 in Version 6

### ISSUE THREAD

**Issue by jofrly** [bithost-gmbh/ngx-mat-select-search#433]
**Is your feature request related to a problem? Please describe.**
We're using Angular 16 and Angular material 16 but we're only using `MatLegacySelectModule` because the upgrade to the new components would take too much time right now.
Therefore we use Version `6.0.0` of `ngx-mat-select-search`.
However although angular material supports `MatLegacySelectModule` in Version 16, `ngx-mat-select-search` does not support Angular material 16 in Version `6.0.0`.

Would it be possible to release a Version `6.0.1` that also supports Angular 16 or are there any reasons why this would not be a good idea? I'm happy to create the PR.

**Describe the solution you'd like**
Change `peerDependencies` in `package.json` from

```
  "peerDependencies": {
    "@angular/material": "^15.0.0"
  },
```

to
```
  "peerDependencies": {
    "@angular/material": "^15.0.0 || ^16.0.0"
  },
```

**Describe alternatives you've considered**
`npm install --legacy-peer-deps` but that's just an ugly workaround

**Additional context**
None

**Comment by macjohnny** [comment]
@jofrly it seems the bug https://github.com/bithost-gmbh/ngx-mat-select-search/issues/431 also applies to angular material 16.2 with `MatLegacySelectModule`, but the fix https://github.com/bithost-gmbh/ngx-mat-select-search/issues/431#issuecomment-1696059475 does not work. if you want to investigate a fix that works for all themes, I am happy to release a version 6.0.1.

**Comment by jofrly** [comment]
![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/14360175/f47af76a-2418-4442-91db-a9cc1fc9701b)

We're not facing this bug in our application with angular material 16.1.1 and ngx-mat-select-search 6.0.0

**Comment by macjohnny** [comment]
@jofrly the problem arises with material 16.2

**Comment by ioanbin** [comment]
What worked for me for Angular Material >16.2 versions is this :
```
.mat-select-search-inner-multiple {
    &.mat-select-search-inner-toggle-all {
      background-color: var(--mat-select-panel-background-color);
    }
  }
```
In my opinion, this should be implemented in this part 
https://github.com/bithost-gmbh/ngx-mat-select-search/pull/434/files#diff-114f34682e5ad0081489bdbcabc0eec64a2611e2d60f79aae41700708fb03b7fL34

The other fix could be also removed! Please test to ensure that this is actually solving the issue and also if makes sense to implement it in the library as well!

**Comment by macjohnny** [comment]
@ioanbin moved your comment to a new issue: https://github.com/bithost-gmbh/ngx-mat-select-search/issues/435, since it is separate from this one

**Comment by jofrly** [comment]
> @jofrly the problem arises with material 16.2

Actually we're not facing any issues with angular material 16.2.2 in combination with `ngx-mat-select-search@6.0.0` except having to use `--legacy-peer-deps`.

Are you sure the bug is also present with the legacy components? It seems the stackblitz doesn't use the legacy components.

Anyways we're going to upgrade to the new components.

**Comment by macjohnny** [comment]
@jofrly when I found the [issue mentioned above](https://github.com/bithost-gmbh/ngx-mat-select-search/issues/433#issuecomment-1696154473) I was using material 16.2, ngx-mat-select-search 6.0.0 and the legacy module.

So do you double check there is no issue with all the use cases in the demo?

also, do you still need a 6.0.1 release or will you be using 7.0.3 anyway?

**Comment by jofrly** [comment]
I didn't check all possible use cases in our app. We're going to be using 7.0.3 anyways but thanks!
