### ISSUE TITLE
background issue for Angular Material >16.2 with toggle all button

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/ngx-mat-select-search#435]
What worked for me for Angular Material >16.2 versions is this :
```
.mat-select-search-inner-multiple {
    &.mat-select-search-inner-toggle-all {
      background-color: var(--mat-select-panel-background-color);
    }
  }
```
In my opinion, this should be implemented in this part 
https://github.com/bithost-gmbh/ngx-mat-select-search/pull/434/files#diff-114f34682e5ad0081489bdbcabc0eec64a2611e2d60f79aae41700708fb03b7fL34

The other fix could be also removed! Please test to ensure that this is actually solving the issue and also if makes sense to implement it in the library as well!

_Originally posted by @ioanbin in https://github.com/bithost-gmbh/ngx-mat-select-search/issues/433#issuecomment-1700873149_

**Comment by ioanbin** [comment]
@macjohnny sure, I will do it!

**Comment by ioanbin** [comment]
@macjohnny Unfortunately, I can't implement the fix, because the project is not migrated to Angular 16 yet! This fix is valid only for Angular >16 versions.

**Comment by macjohnny** [comment]
@ioanbin what you can do is to implement the fix, build the library locally, and copy over the build to the node_modules folder of https://github.com/bithost-gmbh/ngx-mat-select-search-example (which was migrated to ng 16). we don't migrate https://github.com/bithost-gmbh/ngx-mat-select-search on purpose, to make sure we are still compatible with that version and upwards

**Comment by ioanbin** [comment]
@macjohnny But this will not fix the issue with the actual library though, am I right?  My solution is not valid for 15 though and will cause styling issues! I will try to find a better solution, otherwise, when updating the library to 16.2 we can implement the fix. What do you think?
