### ISSUE TITLE
[BUG] Set `compareWith` on ngAfterViewInit

### ISSUE THREAD

**Issue by angelaki** [bithost-gmbh/ngx-mat-select-search#442]
In all your Stackblitz examples you are running this code on `ngAfterViewInit`:

```
    this.filteredBanks
      .pipe(take(1), takeUntil(this._onDestroy))
      .subscribe(() => {
        // setting the compareWith property to a comparison function
        // triggers initializing the selection according to the initial value of
        // the form control (i.e. _initializeSelection())
        // this needs to be done after the filteredBanks are loaded initially
        // and after the mat-option elements are available
        this.singleSelect.compareWith = (a: Bank, b: Bank) => a && b && a.id === b.id;
      });
```

I can't find a difference to just setting it directly. Is it actually required **after** the options change? Or is this just some kind of leftover?

**Comment by macjohnny** [comment]
@angelaki this was needed to properly display the selected value when loading the options asynchronously. It might be that its not needed anymore with the latest material version, but I havent checked

**Comment by angelaki** [comment]
Ah, ok! Thank you for the information! And yes, seams like it's not neccessary any more.
