### ISSUE TITLE
[BUG] select search should compare values of options

### ISSUE THREAD

**Issue by lorenzbaier** [bithost-gmbh/ngx-mat-select-search#445]
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/d2f18e8af0fb199374cbf52a85bb4e562c2d3bf8/src/app/mat-select-search/mat-select-search.component.ts#L351

compares the actual `MatOption` elements instead of their values

the `compareWith` operates on the values of the options. see https://material.angular.io/components/select/api

![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/64407215/90e2f6a5-cb0a-4e92-ae74-d77a8ed90b0a)

**Comment by lorenzbaier** [comment]
Sure, i can look into it and propose a fix.

**Comment by macjohnny** [comment]
@lorenzbaier thanks for the fix, it is released in [7.0.5](https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/7.0.5)
