### ISSUE TITLE
Can you please clarify breaking changes between versions

### ISSUE THREAD

**Issue by doliG** [bithost-gmbh/ngx-mat-select-search#449]
**Describe the bug**
I have an angular 13 app with `ngx-mat-select@3.3.2`. I'm doing angular 14 migration.

Version 3.3.2 is not compatible with angular 14, but version 5.0.0 is. However, I cannot find anything in the README explaning if there are breaking changes between 3.3.2 and 5.0.0, and if yes how should I migrate.

Can you please clarify this ?

Thanks in advance for helping.

**Comment by macjohnny** [comment]
You can find the breaking changes in the changelog: https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/CHANGELOG.md
