### ISSUE TITLE
[BUG] issue on select when add this control in the for loop

### ISSUE THREAD

**Issue by sureshsinganamala** [bithost-gmbh/ngx-mat-select-search#458]
**Issue when we add this control in the for loop. When we select any one of the control and try to do search then already selected controls  selected values going into blank.**

**To Reproduce**
1. Add this control in the ng for loop and bind the respected data.
2. Select the value for any one of the control
3. Now click on the another select and try to search any values
4. you can observe the previous selected control value is empty if you search any random search text.

**Screenshots**

<img width="471" alt="image" src="https://github.com/bithost-gmbh/ngx-mat-select-search/assets/140687595/355e984f-37a7-4f72-9166-223e7d19971b">

![image](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/140687595/bc1dfc5b-9737-4ba1-8175-ed04425aeb4f)

**Comment by macjohnny** [comment]
can you please post your template/controller code? it sounds like you are re-using a variable across the multiple instances of the select/search field

**Comment by sureshsinganamala** [comment]
I am using same bind variable for all the controls. I am using in the mat table.


```
  partfilter(search: string) {
    if (!this.partGroupsList) {
      return;
    }

    if (!search) {
      this.partGroupsFilteredList.next(this.partGroupsList.slice());
      return;
    }

    search = search.toLowerCase();
    this.partGroupsFilteredList.next(this.partGroupsList.filter(part => part.toLowerCase().indexOf(search) > -1));
  }
```

```
                            <ng-container matColumnDef="PART_ID">
                                <th mat-header-cell *matHeaderCellDef mat-sort-header> Part </th>
                                <td mat-cell *matCellDef="let element">
                                    <mat-form-field appearance="outline">
                                        <mat-select placeholder="Select Part" #singleSelect [disabled]="data.mode == 2"
                                            disableOptionCentering [(ngModel)]="element.PART_ID">
                                            <mat-option style="position: relative !important;">
                                                <ngx-mat-select-search placeholderLabel="Search"
                                                    (ngModelChange)="partfilter($event)"
                                                    [ngModelOptions]="{standalone: true}" ngModel
                                                    noEntriesFoundLabel="No matches found"></ngx-mat-select-search>
                                            </mat-option>
                                            <mat-option *ngFor="let part of partGroupsFilteredList | async"
                                                [disabled]="disablePart(part)" [value]="part">
                                                {{part}}
                                            </mat-option>
                                        </mat-select>
                                    </mat-form-field>
                                </td>
                            </ng-container>
```

**Comment by syclone** [comment]
You are getting this error because the component needs a unique name if you are using ngModel. You can try to add a unique name in your loop. 

For example:
                              
```
<ngx-mat-select-search name="UNIQUE_NAME_HERE"  placeholderLabel="Search"
          (ngModelChange)="partfilter($event)"
          [ngModelOptions]="{standalone: true}" ngModel
          noEntriesFoundLabel="No matches found"></ngx-mat-select-search>
```

You may also need the name attribute in your `mat-search` to be safe. 

I didn't have `ngx-mat-select-search` in a loop, but putting multiple of them on a page caused the same issue. I solve it by adding a unique name for each.

**Comment by macjohnny** [comment]
@syclone would you want to add a note about this (i.e. a new section) in the https://github.com/bithost-gmbh/ngx-mat-select-search?tab=readme-ov-file#how-to-use-it ?

**Comment by chutzemischt** [comment]
I experience the same behavior using a reactive form:

```html
<mat-form-field>
	<mat-label>Cars</mat-label>
	<mat-select [formControlName]="formControls.cars" multiple>
	  <mat-option>
		<ngx-mat-select-search [formControlName]="formControls.filteredCars" placeholderLabel="Search ...">
		  <mat-icon ngxMatSelectSearchClear (click)="clearCarSearch()">clear</mat-icon>
		</ngx-mat-select-search>
	  </mat-option>
	  @for (car of filteredCars | async; track car.id) {
		<mat-option [value]="car.id">
		  {{ user.name }}
		</mat-option>
	  }
	</mat-select>
</mat-form-field>
```

To me it seems to be a bug, as I can see the same behavior at the example page on https://bithost-gmbh.github.io/ngx-mat-select-search:

Before search, the selected values are displayed in the form field:

![image](https://github.com/user-attachments/assets/77ded741-a8bd-411a-9e71-1a927dd43cf2)

When searching, the selected values disappear in the form field:

![image](https://github.com/user-attachments/assets/77c5a2f3-5049-4bac-af59-919f4a78e520)

The search has to be cleared, to see again the selected values in the form field.

**Comment by macjohnny** [comment]
@chutzemischt i think the issue you describe is a different one, not related to the for loop, but rather to the fact that an option needs to be present in order to be selected. during filtering, the option is temporarily removed, so thats why the selection temporarily disappears. this is a known issue and somewhat I havent found a good solution for that.
