### ISSUE TITLE
Options Out of View If Initially Empty and Near Edge

### ISSUE THREAD

**Issue by rmegal** [bithost-gmbh/ngx-mat-select-search#464]
Using `ngx-mat-select-search` to dynamically load options from back end. The list of options is empty until the user enters some search criteria. If the control is near the bottom of the viewport, and the search input box fits below, it will be positioned below the form field. Once the user enters some criteria and the options load they get pushed out of the viewport. The user is unable to scroll all options into view.

**To Reproduce**
See this: https://stackblitz.com/edit/stackblitz-starters-uoakhh?file=src%2Fapp%2Fapp%2Fapp.component.ts

Enter a paragraph number near the bottom of your viewport; the number will change depending upon the size of your screen, resolution, etc.

Click in the form field and ensure the "Search Banks" appears below it. Enter some search criteria (e.g., lower-case L).

**Expected behavior**
The list of options would expand up, into the viewport if the scrollable area doesn't fit below it in the viewport.

**Screenshots**
![ngx-mat-select-search_20240527](https://github.com/bithost-gmbh/ngx-mat-select-search/assets/213904/78be00f7-d050-425a-93b8-10be1c91b9ef)

**Desktop (please complete the following information):**
Windows 10.
Edge - latest.

**Additional context**
The workaround is to have the user click away and then come back, which _usually_ causes the options list to reposition above the form field.

**Comment by macjohnny** [comment]
closing this as its not specific to ngx-mat-select-search, but rather to mat-select.
