### ISSUE TITLE
Need an input param for auto-focusing filter box

### ISSUE THREAD

**Issue by blackblood19** [bithost-gmbh/ngx-mat-select-search#47]
Right now, as soon as we open the select element, the filter box is focused. Is there any way to not do that?

**Comment by macjohnny** [comment]
@blackblood19 an option would be to add
```
@Input() disableInitialFocus: boolean = false;
```
and check for it in https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L292

would you like to add this and file a PR?

**Comment by macjohnny** [comment]
@blackblood19 version `1.4.0` contains an input `@Input() disableInitialFocus` to disable initial focusing of the input field.
