### ISSUE TITLE
Set selected value

### ISSUE THREAD

**Issue by saravanaams** [bithost-gmbh/ngx-mat-select-search#48]
I'm using ngx-mat-select-search in my application.It's working fine.But while editing the form i can't the set the selected option.

In sample based in array index it has been set as selected.

Below is my JSON loading into options.
```json
[
  {
    "countryId": "1",
    "countryName": "Afghanistan"
  },
  {
    "countryId": "10",
    "countryName": "Antigua and Barbuda"
  },
  {
    "countryId": "100",
    "countryName": "Hong Kong"
  }
]
```

I need to set the selection option based on countryId.

Below is my sample code.

```html
<mat-form-field class="county-part dropdown-inside-box">
  <mat-select [formControl]="countryCtrl" placeholder="" #singleSelect>
	<ngx-mat-select-search [formControl]="countryFilterCtrl" placeholderLabel="Search by name" noEntriesFoundLabel='No results found'></ngx-mat-select-search>
	<mat-option *ngFor="let sr of filteredCountry | async" [value]="sr.countryId" (click)="getCountryId(sr.countryId)">
	  {{sr.countryName}}
	</mat-option>
  </mat-select>
  <img src="../../assets/images/arrow-black-down.svg" class="black-arrow-img">
  <mat-error *ngIf="isFieldInvalid('countryCtrl')">
	Please enter Country
  </mat-error>
</mat-form-field>
```

And also how can set the selected options in multiselect?

Thanks,

**Comment by macjohnny** [comment]
@saravanaams instead of `(click)="getCountryId(sr.countryId)"` you should listen on changes of the form control value, i.e. `this.countryCtrl.valueChanges.subscribe((newValue) => {})`

Could you please provide a complete example by modifying this stackblitz example:  https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search

**Comment by macjohnny** [comment]
I think this issue is not a bug but wrong implementation of angular form components, since the example (https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example) works correctly.
