### ISSUE TITLE
Don't change the representation of the selected values (multi) on the input of the mat-select

### ISSUE THREAD

**Issue by ma-gamp** [bithost-gmbh/ngx-mat-select-search#498]
**Is your feature request related to a problem? Please describe.**
We think it's kind of strange that if you search a value on the mat-option list, the representation of the selected values on the mat-select (multi) also changes.

**Describe the solution you'd like**
We would expect that the representation of the selected values should only be affected if you change the selection but not while searching.

**Additional context**
I'm not sure if our expected behaviour is possible to implement but if you think it is a valid request and solveable we could make a PR in the future.

**Comment by macjohnny** [comment]
unfortunately this is a somewhat known behavior and hard to come by, since filtering works by temporarily removing options, which results in them temporarily being deselected (since only present options can be selected). i don't think there is an easy fix for this.
