### ISSUE TITLE
[BUG] Not works unit test in standAloneComponent need inject mat-select

### ISSUE THREAD

**Issue by AdamsContreras999** [bithost-gmbh/ngx-mat-select-search#499]
-all dependencies of angular in v18.0.1
-angular material v18.0.1

component parent
```
<mat-form-field
                appearance="outline"
                class="w-full"
                subscriptSizing="dynamic"
              >
                <mat-label class="text-base">Options</mat-label>
                <mat-select formControlName="valueToUpdateField">
                  <mat-option>
                    <app-ngx-search></app-ngx-search>
                  </mat-option>
                </mat-select>
                
</mat-form-field>
```

-this is spec of component parent 
```
fdescribe('UpdateFieldActionComponent', () => {
  let component: UpdateFieldActionComponent;
  let fixture: ComponentFixture<UpdateFieldActionComponent>;
  let userService: UserService;
  let stationService: StationService;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        UpdateFieldActionComponent,
        MatButtonModule,
        LoadingIndicatorComponent,
        MatFormFieldModule,
        FormsModule,
        MatSelectModule,
        ReactiveFormsModule,
        BrowserAnimationsModule,
        NoopAnimationsModule,
        NgxSearchComponent,
      ],
      providers: [
        { provide: StationService, useClass: MockStationService },
        { provide: ContainerService, useClass: MockContainerService },
        { provide: ErrorService, useClass: MockErrorService },
        { provide: UserService, useClass: MockUserService },
        { provide: PopupService, useClass: MockPopupService },
        { provide: ConditionHelper, useClass: ConditionHelper },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(UpdateFieldActionComponent);
    component = fixture.componentInstance;
    userService = TestBed.inject(UserService);
    stationService = TestBed.inject(StationService);
    component.actionToUpdate = actionToUpdateLocal;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

-Create new standAlone component 
component child 'ngx-search'
html
![image](https://github.com/user-attachments/assets/6f19c6d4-3edd-4b4b-beab-cd7e74562a5f)

ts
![image](https://github.com/user-attachments/assets/1283eba4-d6d5-4b02-bbc4-00a66b8dcf1d)

-this is spec of ngx-search
```
fdescribe('NgxSearchComponent', () => {
  let component: NgxSearchComponent;
  let fixture: ComponentFixture<NgxSearchComponent>;
  let componentRef: ComponentRef<NgxSearchComponent>;
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        NgxSearchComponent,
        FormsModule,
        ReactiveFormsModule,
        NoopAnimationsModule,
        NgxMatSelectSearchModule,
        BrowserModule,
        MatSelectModule
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(NgxSearchComponent);
    component = fixture.componentInstance;
    componentRef = fixture.componentRef;
    fixture.componentRef.setInput('insideSelect', false);
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

all works good but in unit test 

return this error
![image](https://github.com/user-attachments/assets/3a300f46-934a-4d8c-a6b9-a4845fb4bbe7)

Could you help me solve this problem?

**Comment by macjohnny** [comment]
this sounds a bit like ngx-mat-select-search not importing the same `MatSelect` as you do in your component.
it is weird that this only happens in the unit test, but it could be due to the test setup.

can you

- check whether there is a `node_modules/ngx-mat-select-search/node_modules/@angular/components`? if so, this should be deleted
- paste the code of your `app-ngx-search` component imports, and also the unit test imports and setup?
  - same for the component that consumes `app-ngx-search`

**Comment by AdamsContreras999** [comment]
> * check whether there is a `node_modules/ngx-mat-select-search/node_modules/@angular/components`? if so, this should be deleted
> * paste the code of your `app-ngx-search` component imports, and also the unit test imports and setup?
>   
>   * same for the component that consumes `app-ngx-search`

@macjohnny thanks for your response 



not i dont have
-directory: 'node_modules/ngx-mat-select-search/node_modules/@angular/components'
![image](https://github.com/user-attachments/assets/9723d1ac-42b4-464c-a1cd-0da6f9d6ac46)




-this is spec of component parent 
fdescribe('UpdateFieldActionComponent', () => {
  let component: UpdateFieldActionComponent;
  let fixture: ComponentFixture<UpdateFieldActionComponent>;
  let userService: UserService;
  let stationService: StationService;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        UpdateFieldActionComponent,
        MatButtonModule,
        LoadingIndicatorComponent,
        MatFormFieldModule,
        FormsModule,
        MatSelectModule,
        ReactiveFormsModule,
        BrowserAnimationsModule,
        NoopAnimationsModule,
        NgxSearchComponent,
      ],
      providers: [
        { provide: StationService, useClass: MockStationService },
        { provide: ContainerService, useClass: MockContainerService },
        { provide: ErrorService, useClass: MockErrorService },
        { provide: UserService, useClass: MockUserService },
        { provide: PopupService, useClass: MockPopupService },
        { provide: ConditionHelper, useClass: ConditionHelper },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(UpdateFieldActionComponent);
    component = fixture.componentInstance;
    userService = TestBed.inject(UserService);
    stationService = TestBed.inject(StationService);
    component.actionToUpdate = actionToUpdateLocal;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });



-this is spec of ngx-search
fdescribe('NgxSearchComponent', () => {
  let component: NgxSearchComponent;
  let fixture: ComponentFixture<NgxSearchComponent>;
  let componentRef: ComponentRef<NgxSearchComponent>;
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        NgxSearchComponent,
        FormsModule,
        ReactiveFormsModule,
        NoopAnimationsModule,
        NgxMatSelectSearchModule,
        BrowserModule,
        MatSelectModule
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(NgxSearchComponent);
    component = fixture.componentInstance;
    componentRef = fixture.componentRef;
    fixture.componentRef.setInput('insideSelect', false);
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

**Comment by macjohnny** [comment]
in the unit tests of NgxSearchComponent, you will have to wrap it with a test component that has a `<mat-select>` in the template that wraps the `app-ngx-search`

**Comment by AdamsContreras999** [comment]
> in the unit tests of NgxSearchComponent, you will have to wrap it with a test component that has a `<mat-select>` in the template that wraps the `app-ngx-search`

Can you help me how to do it?

@macjohnny

**Comment by macjohnny** [comment]
in your test you should have something like

```
@Component({
  selector: 'app-ngx-search-test',
  template: `
   <mat-select>
    <app-ngx-search></app-ngx-search>
   <mat-select>
  `,
})
class NgxSearchTestComponent {}

fdescribe('NgxSearchComponent', () => {
  let component: NgxSearchTestComponent;
  let fixture: ComponentFixture<NgxSearchTestComponent>;
  let componentRef: ComponentRef<NgxSearchTestComponent>;
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        NgxSearchComponent,
        NgxSearchTestComponent,
        FormsModule,
        ReactiveFormsModule,
        NoopAnimationsModule,
        NgxMatSelectSearchModule,
        BrowserModule,
        MatSelectModule
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(NgxSearchTestComponent);
    component = fixture.componentInstance;
    componentRef = fixture.componentRef;
    fixture.componentRef.setInput('insideSelect', false);
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

**Comment by AdamsContreras999** [comment]
> in your test you should have something like
> 
> ```typescript
> @Component({
>   selector: 'app-ngx-search-test',
>   template: `
>    <mat-select>
>     <app-ngx-search></app-ngx-search>
>    <mat-select>
>   `,
> })
> class NgxSearchTestComponent {}
> 
> fdescribe('NgxSearchComponent', () => {
>   let component: NgxSearchTestComponent;
>   let fixture: ComponentFixture<NgxSearchTestComponent>;
>   let componentRef: ComponentRef<NgxSearchTestComponent>;
>   beforeEach(async () => {
>     await TestBed.configureTestingModule({
>       imports: [
>         NgxSearchComponent,
>         NgxSearchTestComponent,
>         FormsModule,
>         ReactiveFormsModule,
>         NoopAnimationsModule,
>         NgxMatSelectSearchModule,
>         BrowserModule,
>         MatSelectModule
>       ],
>     }).compileComponents();
> 
>     fixture = TestBed.createComponent(NgxSearchTestComponent);
>     component = fixture.componentInstance;
>     componentRef = fixture.componentRef;
>     fixture.componentRef.setInput('insideSelect', false);
>     fixture.detectChanges();
>   });
> 
>   it('should create', () => {
>     expect(component).toBeTruthy();
>   });
> });
> ```

Thanks Mr @macjohnny
