### ISSUE TITLE
Enhancement: Change Input search placeholder value

### ISSUE THREAD

**Issue by super-jb** [bithost-gmbh/ngx-mat-select-search#50]
I noticed this is mentioned in the README file:
> ** Label of the search placeholder */
>  @Input() placeholderLabel = 'Suche';

But I don't understand how to change its value... Is there a way to provide a different value? If so, could you share an example? If not, could this be built in?

Thanks

**Comment by macjohnny** [comment]
@super-jb I added an example how to change labels in #51, see https://github.com/bithost-gmbh/ngx-mat-select-search#labels

This could also be interesting for @alirezajs and @michaelfamarques

**Comment by super-jb** [comment]
Thank you so much @macjohnny 

**JB**
