### ISSUE TITLE
[BUG] listening on valueChanges on form or element fires twice in multiple selection

### ISSUE THREAD

**Issue by jeelo** [bithost-gmbh/ngx-mat-select-search#500]
When listening for valueChanges on the surrounding form or on the select element itself the Observable is fired twice when the search is used compared to once when a mat-option is clicked directly without searching first.

Using the standard stackblitz example adding this to the ngOnInit() function in multiple-selection-example.component.ts:

[https://stackblitz.com/edit/github-vwmt3m?file=src%2Fapp%2Fexamples%2F02-multiple-selection-example%2Fmultiple-selection-example.component.ts](https://stackblitz.com/edit/github-vwmt3m?file=src%2Fapp%2Fexamples%2F02-multiple-selection-example%2Fmultiple-selection-example.component.ts)

```
this.bankMultiCtrl.valueChanges
      .pipe(takeUntil(this._onDestroy))
      .subscribe((changes) => {
        console.log(changes);
      });
```

When clicking on for instance "Bank I (Italy)" directly you get an expected single output:

```
Array(4) [ {…}, {…}, {…}, {…} ]
​0: Object { name: "Bank I (Italy)", id: "I" }
1: Object { name: "Bank Kolombia (United States of America)", id: "K" }
​2: Object { name: "Bank L (Germany)", id: "L" }
​3: Object { name: "Bank M (Germany)", id: "M" }
​length: 4
```

When first searching for "Bank I" and then clicking on "Bank I (Italy)" results in 2 outputs:

```
Array [ {…} ]​
0: Object { name: "Bank I (Italy)", id: "I" }
​1: Object { name: "Bank Kolombia (United States of America)", id: "K" }
​2: Object { name: "Bank L (Germany)", id: "L" }
​3: Object { name: "Bank M (Germany)", id: "M" }
​length: 4
```
and
```
Array(4) [ {…}, {…}, {…}, {…} ]
​0: Object { name: "Bank I (Italy)", id: "I" }
​1: Object { name: "Bank Kolombia (United States of America)", id: "K" }
​2: Object { name: "Bank L (Germany)", id: "L" }
​3: Object { name: "Bank M (Germany)", id: "M" }
​length: 4
```

When unselecting an item when first searching you also get 2 outputs.

This makes it hard to for instance load content dynamically on form changes.

Is this expected behavior?

Many thanks!

**Comment by macjohnny** [comment]
I think this is expected because the multi-selected values need to be reset after filtering is done: https://github.com/bithost-gmbh/ngx-mat-select-search/blob/ebb0a4c7a53e56c138bdac5ae6363ab51c6ba050/src/app/mat-select-search/mat-select-search.component.ts#L568

currently, I think the only solution is that on your side you use e.g. https://rxjs.dev/api/operators/distinct
