### ISSUE TITLE
[BUG] Overflow for server side search not correctly rendered

### ISSUE THREAD

**Issue by DariusCorp** [bithost-gmbh/ngx-mat-select-search#508]
**Describe the bug**
When searching a select and the results overflow downward, the last options are always unreachable. After reopening the select it renders correctly because it has a different length, but this should be the default behavior from the beginning. 

**To Reproduce**
1. Have a select at the bottom of the page
2. Have the select open downwards
3. Search something for which the select is going to overflow downwards
4. Scroll down
5. Last options are unreachable

**Expected behavior**
The option should change direction upward

**Screenshots**
![image](https://github.com/user-attachments/assets/27d3d9b9-23c3-4ad8-ab38-b5ec2c7d6742)

**Comment by macjohnny** [comment]
thanks for reporting. unfortunately this is a known problem without a clear solution: https://github.com/bithost-gmbh/ngx-mat-select-search/tree/master?tab=readme-ov-file#known-problems
