### ISSUE TITLE
Reset button not working if clearSearchInput=false

### ISSUE THREAD

**Issue by ofriedrich** [bithost-gmbh/ngx-mat-select-search#55]
If the option "clearSearchInput" is set to "false", it is not possible to clear the filter-input-field.

It looks like it depends on this condition:
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/ae61589ccecb34b3b501a358b82f8a48f08f1856/src/app/mat-select-search/mat-select-search.component.ts#L320

If the user clicks the reset-button, the variable "focus" is set to true. So it might work if this line will be changed to:

```    if (focus || this.clearSearchInput) {```

**Comment by macjohnny** [comment]
@ofriedrich thanks a good suggestion. would you like to create a PR to include your changes?
maybe you could also add an input for https://github.com/bithost-gmbh/ngx-mat-select-search/issues/47?

**Comment by macjohnny** [comment]
this is fixed in version `1.4.0`
@ofriedrich thanks for reporting!
