### ISSUE TITLE
Template parse errors: Can't bind to 'formControl' since it isn't a known property of 'mat-select'.

### ISSUE THREAD

**Issue by Wandang** [bithost-gmbh/ngx-mat-select-search#62]
Hello there,

There is probably a trivial import error that I fail to find in my app. I created a extremely simplified version of my app on stackblitz.
https://stackblitz.com/edit/angular-fsb1uy

Any help is greatly appreciated. Thank you for your hard work on this fork in any case!

**Comment by macjohnny** [comment]
@Wandang you are missing the `ReactiveFormsModule` import, see 
https://github.com/bithost-gmbh/ngx-mat-select-search-example/blob/master/src/app/app.module.ts#L18
