### ISSUE TITLE
Error when quickly selection option

### ISSUE THREAD

**Issue by olaf89** [bithost-gmbh/ngx-mat-select-search#69]
Cannot read property 'nativeElement' of undefined
    at MatSelectSearchComponent.push../node_modules/ngx-mat-select-search/esm5/ngx-mat-select-search.js.MatSelectSearchComponent._focus (ngx-mat-select-search.js:146)

 MatSelectSearchComponent.prototype._focus = function () {
        if (!this.searchSelectInput) {
            return;
        }
        var panel = this.matSelect.panel.nativeElement;

This is the code that is failing. There should be probably nullcheck added

**Comment by maechler** [comment]
Thanks for reporting that bug! I can reproduce this issue. Could you prepare a pull request to fix this issue?

**Comment by maechler** [comment]
Fixed with release `1.4.2`
