### ISSUE TITLE
problem when i scroll mat-select + ngx-mat-select-search on IOS 

### ISSUE THREAD

**Issue by giacomarco** [bithost-gmbh/ngx-mat-select-search#70]
When I scroll the select on IOS the input search is not fix on top. [Video DEMO](https://www.youtube.com/watch?v=TyFg4P6jktg&feature=youtu.be)

**Comment by macjohnny** [comment]
I can confirm the problem. However, I have no idea how to solve it, yet. @giacomarco would you like to help us and try to find out how to solve this?
