### ISSUE TITLE
adding icon to mat-select group name

### ISSUE THREAD

**Issue by st-clair-clarke** [bithost-gmbh/ngx-mat-select-search#76]
Hi,
This a request, NOT an issue.
Would you please consider adding the ability for the name of a group to support an icon as well as the name.

Consider the following:
```
<mat-select
                #multiSelect
                [formControl] = "multiOptionCtrl"
                [multiple] = "true"
                [placeholder] = 'placeholder'>
              <ngx-mat-select-search
                  [formControl] = "multiOptionCtrl"></ngx-mat-select-search>
              <mat-optgroup
                  *ngFor = "let group of multiOptionsFilter | async"
                  [label] = "group.name">
                <mat-icon
                    [svgIcon] = 'group?.icon'
                    class = 'mrg-rt-5px'
                    color = 'accent'></mat-icon>
                <mat-option
                    *ngFor = "let option of group.options"
                    [value] = "option.value">
                  <mat-icon
                      [svgIcon] = 'option?.icon'
                      class = 'mrg-rt-5px'
                      color = 'accent'></mat-icon>
                  {{option.viewValue}}
                </mat-option>
              </mat-optgroup>
            </mat-select>
```

  <mat-icon
                    [svgIcon] = 'group?.icon'
                    class = 'mrg-rt-5px'
                    color = 'accent'></mat-icon>

does not display the icon.

I suggest maybe group.icon. Please let me know what you think.

Thanks

**Comment by maechler** [comment]
@st-clair-clarke This seems to be more like an issue that has to be solved in the component `mat-optgroup`. It looks like this has been fixed in `material2` `7.0`, please see:

https://github.com/angular/material2/issues/11489
https://github.com/angular/material2/releases/tag/7.0.0-rc.1

`select: allow extra content to be projected after label in mat-optgroup (#13396) (cb5b15e), closes #11489`

**Comment by st-clair-clarke** [comment]
I am attempting the trasclusion with ng-content without success
Below is my multi-select-group segement:

```
 <mat-select
                #multiSelect
                [formControl] = "multiOptionCtrl"
                [multiple] = "true"
                [placeholder] = 'placeholder'>
              <ngx-mat-select-search
                  [formControl] = "multiOptionCtrl"></ngx-mat-select-search>
              <mat-optgroup
                  *ngFor = "let group of multiOptionsFilter | async"
                  [label] = "group.name">
                <ng-content
                    select = 'mat-icon'></ng-content>
                <mat-option
                    *ngFor = "let option of group.options"
                    [value] = "option.value">
                  <mat-icon
                      [svgIcon] = 'option?.icon'
                      class = 'mrg-rt-5px'
                      color = 'accent'></mat-icon>
                  {{option.viewValue}}
                </mat-option>
              </mat-optgroup>
            </mat-select>
```
And here is my projected content

 <nhncd-mat-multi-select-group>
                  <mat-icon
                      [svgIcon] = 'group?.icon'
                      class = 'mrg-rt-5px'
                      color = 'accent'></mat-icon>
                </nhncd-mat-multi-select-group>

Any ideas why the transclusion is not displaying the icon to the right of the group.name label?

**Comment by maechler** [comment]
I am afraid, I do not know what could be wrong. Please see `material2` to make this work. I will close this issue because it is not related to `ngx-mat-select-search`.

**Comment by st-clair-clarke** [comment]
@maechler Please have a look at https://github.com/angular/material2/commit/cb5b15e#diff-116eefc2192e5113737131ba1a3ac7b0. Adapting this to ngx-mat-select-search is a challenge.
