### ISSUE TITLE
Improve enter / leave animation

### ISSUE THREAD

**Issue by macjohnny** [bithost-gmbh/ngx-mat-select-search#85]
Due to positioning during the panel fade in / out animation, the search input instantly appears after the animation is done. 
This should be improved to smoothly fade in the search input. 
Probably the positioning during the animation needs to be fixed.

**Comment by Yavorss** [comment]
Yes, this effect is awful. I'm gonna try to fix it if I have time these days

**Comment by vvkotov** [comment]
Hi @macjohnny ,
what about making `mat-option` container sticky?
It seems this way there is no blinking option behind **ngx-mat-select-search**([check single selection example](https://stackblitz.com/edit/github-1knpuj?file=src/app/examples/01-single-selection-example/single-selection-example.component.scss))

**Comment by macjohnny** [comment]
Thanks for the suggestion. However, on a mobile device with iOS/Chrome, the search input is not visible initially:
![B2072376-E929-4B89-B8EF-3C089313AF6B](https://user-images.githubusercontent.com/5589029/116238897-461ef680-a762-11eb-914a-20011f98b4c6.jpeg)

**Comment by macjohnny** [comment]
seems to be obsolete with https://github.com/bithost-gmbh/ngx-mat-select-search/releases/tag/7.0.0
