### ISSUE TITLE
appreciation

### ISSUE THREAD

**Issue by xagon** [bithost-gmbh/ngx-mat-select-search#9]
Man, this looks very nice. I have started to use this select-search component in my project and it is working just fine so far. Few issues already identified - should be easy to fix / address. I've wrapped the control in another component which I can reuse. Starred the repo, and whenever there is a new version of this code / new implementation (probably from Angular/Material team) I will just switch the content where needed.

Good job.

**Comment by macjohnny** [comment]
@xagon thanks for your feedback. I am glad you appreciate the component.
If you find any issue or want to improve the code, feel free to to so.
