### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by vancan1ty** [bithost-gmbh/ngx-mat-select-search#97]
Just a heads up that your demo at https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example is not working as of today 1/10/2019.  error message below:

![image](https://user-images.githubusercontent.com/2806839/50979230-4cb2d280-14b3-11e9-8948-88955e134817.png)

**Comment by macjohnny** [comment]
@vancan1ty thanks for reporting. indeed the demo currently isn't working. 
However, it worked yesterday. Need to check what the issue is. Maybe a problem on stackblitz.

**Comment by macjohnny** [comment]
the demo is working again. as suggested in https://github.com/angular/angular/issues/27531 and https://github.com/stackblitz/core/issues/758, the following line is necessary for angular 7 on stackblitz:

https://github.com/bithost-gmbh/ngx-mat-select-search/blob/b29e03bd5773ab5357fd69a83330577a9857e865/src/polyfills.ts#L45-L46
