### ISSUE TITLE
error in multiple select

### ISSUE THREAD

**Issue by jkhadivi** [bithost-gmbh/ngx-mat-select-search#98]
Hi
im using "@angular/material": "^7.1.1" & "@angular/material": "^7.1.1", in single select its work normally but when i use multi select (multiple) , not displayed properly (css problem) =>
![image](https://user-images.githubusercontent.com/46120896/51135139-981c0680-184e-11e9-873a-7b0b08e753ac.png)

**Comment by macjohnny** [comment]
@jkhadivi thanks for reporting. I release version `1.5.1` which should fix the issue
